"""Điểm đến châu Âu, châu Mỹ cho mục Quốc tế (nối vào intl_src.py).

Cấu trúc giống intl_src.py; thông tin lập lịch trình (v, k, t, d, io, ss, ev, eo, mo, cl, h, a, trip, f) giải thích ở intl_plan.py.
Visa, tỷ giá tra cứu 10/2026 (tỷ giá bán Vietcombank 5/10/2026; lira Thổ theo Wise). Luôn ghi chú người dùng kiểm tra lại.
Giá v = nghìn đồng/người, quy đổi: 1 EUR ≈ 29.800đ, 1 GBP ≈ 34.900đ, 1 CHF ≈ 31.800đ, 1 USD ≈ 26.200đ, 1 CAD ≈ 18.500đ,
1 CZK ≈ 1.200đ, 1 TRY ≈ 530đ.
"""

SCHENGEN = ('Cần visa Schengen (lệ phí khoảng 90 EUR, nộp hồ sơ tại đại sứ quán/trung tâm tiếp nhận của nước ở lâu nhất). '
            'Một visa Schengen đi được cả Pháp, Ý, Thụy Sĩ, Đức, Hà Lan, Tây Ban Nha, Séc, Áo… Từ 10/4/2026 khi nhập cảnh lần đầu sẽ được chụp ảnh, lấy vân tay (hệ thống EES).')

COUNTRIES_W = [
    {'id': 'fr', 'name': 'Pháp', 'flag': '🇫🇷', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Bay thẳng khoảng 13 giờ từ Hà Nội, TP.HCM tới Paris (Vietnam Airlines)', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Mua Paris Museum Pass nếu đi nhiều bảo tàng.', 'Cẩn thận móc túi ở metro, tháp Eiffel, Montmartre.', 'Đặt vé lên tháp Eiffel, bảo tàng Louvre trực tuyến trước để khỏi xếp hàng.']},
    {'id': 'it', 'name': 'Ý', 'flag': '🇮🇹', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Chưa có bay thẳng; nối chuyến khoảng 15–18 giờ tới Rome, Milan, Venice', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Vào nhà thờ cần mặc kín vai, đầu gối.', 'Đi giữa các thành phố bằng tàu cao tốc Frecciarossa/Italo, đặt sớm giá rẻ hơn.', 'Nhiều thành phố thu thuế lưu trú theo đêm tại khách sạn.']},
    {'id': 'ch', 'name': 'Thụy Sĩ', 'flag': '🇨🇭', 'region': 'europe', 'currency': 'Franc Thụy Sĩ (CHF)', 'rate': '1 CHF ≈ 31.800đ',
     'flight': 'Chưa có bay thẳng; nối chuyến khoảng 14–16 giờ tới Zurich, Geneva', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Thẻ Swiss Travel Pass gồm tàu, thuyền, xe buýt và giảm giá tàu lên núi.', 'Chi phí ăn uống cao: siêu thị Coop, Migros có đồ ăn sẵn giá mềm.', 'Thời tiết trên núi thay đổi nhanh, mang áo ấm cả mùa hè.']},
    {'id': 'gb', 'name': 'Anh', 'flag': '🇬🇧', 'region': 'europe', 'currency': 'Bảng Anh (GBP)', 'rate': '1 GBP ≈ 34.900đ',
     'flight': 'Bay thẳng khoảng 13–14 giờ từ Hà Nội, TP.HCM tới London (Vietnam Airlines)',
     'visa': 'Cần visa Anh (Standard Visitor, lệ phí khoảng 135 GBP cho 6 tháng); visa Schengen không dùng được cho Anh.', 'visaFree': False,
     'tips': ['Chạm thẻ ngân hàng không tiếp xúc để đi tàu điện ngầm, xe buýt, có giới hạn trần mỗi ngày.', 'Nhiều bảo tàng lớn ở London miễn phí vào cửa.', 'Ổ cắm điện chuẩn Anh 3 chấu vuông.']},
    {'id': 'de', 'name': 'Đức', 'flag': '🇩🇪', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Bay thẳng khoảng 12–13 giờ tới Frankfurt, Munich (Vietnam Airlines)', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Chủ nhật hầu hết cửa hàng đóng cửa.', 'Vé Deutschlandticket đi tàu vùng, xe buýt không giới hạn trong tháng.', 'Nhiều quán chỉ nhận tiền mặt, mang theo ít euro.']},
    {'id': 'nl', 'name': 'Hà Lan', 'flag': '🇳🇱', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Bay thẳng khoảng 13 giờ Hà Nội – Amsterdam (Vietnam Airlines, từ 6/2026)', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Đặt vé bảo tàng Van Gogh, nhà Anne Frank trực tuyến trước.', 'Cẩn thận làn xe đạp, đi bộ không đứng trên làn màu đỏ.', 'Mùa hoa tulip Keukenhof khoảng cuối tháng 3 – giữa tháng 5.']},
    {'id': 'es', 'name': 'Tây Ban Nha', 'flag': '🇪🇸', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Chưa có bay thẳng; nối chuyến khoảng 16–18 giờ tới Barcelona, Madrid', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Người Tây Ban Nha ăn tối muộn (sau 20:30).', 'Đặt vé Sagrada Família, Park Güell trước nhiều ngày.', 'Cẩn thận móc túi ở La Rambla và tàu điện.']},
    {'id': 'cz', 'name': 'Séc', 'flag': '🇨🇿', 'region': 'europe', 'currency': 'Koruna Séc (CZK)', 'rate': '1 CZK ≈ 1.200đ',
     'flight': 'Chưa có bay thẳng; nối chuyến khoảng 14–16 giờ tới Praha', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Đổi tiền ở quầy uy tín, tránh quầy quảng cáo "0% phí".', 'Phố cổ đi bộ là chính; tàu điện mặt đất rất tiện.', 'Có cộng đồng người Việt lớn, dễ tìm quán ăn Việt.']},
    {'id': 'at', 'name': 'Áo', 'flag': '🇦🇹', 'region': 'europe', 'currency': 'Euro (EUR)', 'rate': '1 EUR ≈ 29.800đ',
     'flight': 'Chưa có bay thẳng; nối chuyến khoảng 14–16 giờ tới Vienna', 'visa': SCHENGEN, 'visaFree': False,
     'tips': ['Đặt vé hòa nhạc ở Nhà hát Opera, có vé đứng giá rẻ.', 'Quán cà phê Vienna là nét văn hóa: ngồi lâu không sao.', 'Hay đi kết hợp Praha – Vienna – Budapest bằng tàu.']},
    {'id': 'tr', 'name': 'Thổ Nhĩ Kỳ', 'flag': '🇹🇷', 'region': 'europe', 'currency': 'Lira (TRY)', 'rate': '1 TRY ≈ 530đ (biến động mạnh)',
     'flight': 'Bay thẳng khoảng 11 giờ Hà Nội, TP.HCM – Istanbul (Turkish Airlines)',
     'visa': 'Từ 9/2025 hộ chiếu Việt Nam được xin e-Visa (lưu trú tối đa 30 ngày), kèm điều kiện về vé khứ hồi, đặt phòng và có thể yêu cầu visa còn hạn của Schengen, Mỹ, Anh…; không đủ điều kiện thì xin tại Đại sứ quán. Kiểm tra trên evisa.gov.tr trước khi đi.',
     'visaFree': False,
     'tips': ['Vào nhà thờ Hồi giáo: nữ choàng khăn, mặc kín; tránh giờ cầu nguyện.', 'Mặc cả ở Grand Bazaar.', 'Khinh khí cầu Cappadocia bay sáng sớm, phụ thuộc thời tiết – nên ở 2 đêm để có ngày dự phòng.']},
    {'id': 'us', 'name': 'Mỹ', 'flag': '🇺🇸', 'region': 'america', 'currency': 'Đô la Mỹ (USD)', 'rate': '1 USD ≈ 26.200đ',
     'flight': 'Bay thẳng khoảng 13–14 giờ TP.HCM – San Francisco (Vietnam Airlines); các nơi khác nối chuyến 17–24 giờ',
     'visa': 'Cần visa du lịch B1/B2, phỏng vấn tại Đại sứ quán Hà Nội hoặc Tổng lãnh sự quán TP.HCM; lệ phí 185 USD, một số nơi đã bắt đầu thu thêm phí "visa integrity" 250 USD khi cấp visa.',
     'visaFree': False,
     'tips': ['Tiền tip nhà hàng khoảng 18–20%, giá niêm yết chưa gồm thuế.', 'Ở Los Angeles, Las Vegas nên thuê xe hoặc dùng Uber/Lyft.', 'Mua bảo hiểm du lịch vì chi phí y tế rất cao.']},
    {'id': 'ca', 'name': 'Canada', 'flag': '🇨🇦', 'region': 'america', 'currency': 'Đô la Canada (CAD)', 'rate': '1 CAD ≈ 18.500đ',
     'flight': 'Chưa có bay thẳng thường xuyên; nối chuyến khoảng 16–22 giờ tới Vancouver, Toronto',
     'visa': 'Cần visa du lịch Canada (TRV) và lấy sinh trắc học; hộ chiếu Việt Nam không thuộc diện xin eTA.', 'visaFree': False,
     'tips': ['Mùa lá đỏ khoảng cuối tháng 9 – giữa tháng 10.', 'Tip nhà hàng khoảng 15–20%.', 'Mùa đông rất lạnh ở Toronto (dưới −10°C).']},
]

E = 29.8   # nghìn đồng / EUR

CITIES_W = [
    # ---------------- PHÁP ----------------
    {'id': 'paris', 'country': 'fr', 'name': 'Paris', 'local': 'Paris', 'wiki': 'Paris', 'best': [4, 5, 6, 9, 10], 'days': '4–5 ngày',
     'intro': 'Kinh đô ánh sáng: tháp Eiffel, bảo tàng Louvre, đại lộ Champs-Élysées và những quán cà phê vỉa hè.',
     'places': [
        ('c', 'Tháp Eiffel', 'Eiffel Tower', 'Biểu tượng của Paris, lên tầng cao ngắm toàn thành phố', {'price': '~23–36 EUR', 'v': 900, 'd': 120, 't': 'pk', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('s', 'Bảo tàng Louvre', 'Louvre', 'Bảo tàng lớn nhất thế giới, nơi có nàng Mona Lisa', {'price': '~22 EUR', 'v': 660, 'd': 180, 't': 'hk', 'io': 'i', 'cl': [2], 'h': '9:00–18:00, nghỉ thứ Ba'}),
        ('s', 'Nhà thờ Đức Bà Paris', 'Notre-Dame de Paris', 'Nhà thờ Gothic đã mở cửa lại sau trùng tu', {'v': 0, 'd': 60, 't': 'hpk', 'io': 'm'}),
        ('c', 'Khải Hoàn Môn', 'Arc de Triomphe', 'Lên đỉnh ngắm 12 đại lộ tỏa ra như ngôi sao', {'price': '~16 EUR', 'v': 480, 'd': 60, 't': 'hpk', 'io': 'o', 'ss': 1, 'ev': 'all'}),
        ('c', 'Đại lộ Champs-Élysées', 'Champs-Élysées', 'Đại lộ mua sắm nổi tiếng nhất nước Pháp', {'k': 'check,cafe', 'v': 0, 'd': 75, 't': 'p', 'io': 'o', 'ev': 'all'}),
        ('c', 'Đồi Montmartre và nhà thờ Sacré-Cœur', 'Sacré-Cœur, Paris', 'Đồi họa sĩ, nhà thờ trắng trên đỉnh nhìn ra Paris', {'v': 0, 'd': 120, 't': 'hpc', 'io': 'o', 'ss': 1, 'f': 'o'}),
        ('s', 'Bảo tàng Orsay', "Musée d'Orsay", 'Tranh Ấn tượng của Monet, Van Gogh trong nhà ga cũ', {'price': '~16 EUR', 'v': 480, 'd': 150, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('s', 'Cung điện Versailles', 'Palace of Versailles', 'Cung điện hoàng gia lộng lẫy với Sảnh Gương và vườn Pháp', {'price': '~21–32 EUR', 'v': 800, 'd': 360, 't': 'hpk', 'io': 'm', 'cl': [1], 'trip': 1}),
        ('c', 'Du thuyền sông Seine', 'Bateaux Mouches', 'Ngắm các công trình hai bờ sông, đẹp nhất về đêm', {'price': '~16–18 EUR', 'v': 500, 'd': 75, 't': 'pr', 'io': 'o', 'ev': 'all', 'll': [48.8638, 2.3013]}),
        ('c', 'Vườn Luxembourg', 'Jardin du Luxembourg', 'Khu vườn đẹp của người Paris, ghế sắt xanh bên đài phun nước', {'v': 0, 'd': 60, 't': 'nr', 'io': 'o'}),
        ('f', 'Khu Le Marais', 'Le Marais', 'Phố cổ nhiều quán cà phê, falafel, cửa hàng nhỏ', {'k': 'trua,cafe,toi', 'v': 450, 't': 'sch', 'io': 'm'}),
        ('f', 'Khu La tinh (Quartier Latin)', 'Latin Quarter, Paris', 'Phố sinh viên, quán crêpe và nhà hàng bình dân', {'k': 'trua,toi,vat', 'v': 400, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('f', 'Café de Flore', 'Café de Flore', 'Quán cà phê lịch sử của giới văn nghệ sĩ Saint-Germain', {'k': 'cafe,sang', 'v': 350, 't': 'ch', 'io': 'm'}),
        ('f', 'Phố chợ Rue Cler', 'Rue Cler', 'Phố chợ gần tháp Eiffel: bánh mì, phô mai, trái cây', {'k': 'sang,trua', 'v': 300, 't': 's', 'io': 'o', 'cl': [1]}),
        ('c', 'Galeries Lafayette', 'Galeries Lafayette Haussmann', 'Trung tâm mua sắm mái vòm kính, sân thượng ngắm cảnh miễn phí', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'p', 'io': 'i'}),
        ('s', 'Disneyland Paris', 'Disneyland Park (Paris)', 'Công viên Disney, hợp đi cùng trẻ em', {'price': '~60–100 EUR', 'v': 2400, 'd': 480, 't': 'p', 'io': 'o', 'trip': 1}),
        ('s', 'Điện Panthéon', 'Panthéon', 'Lăng mộ các vĩ nhân nước Pháp ở khu La tinh', {'price': '~13 EUR', 'v': 390, 'd': 60, 't': 'h', 'io': 'i'}),
     ]},
    # ---------------- Ý ----------------
    {'id': 'rome', 'country': 'it', 'name': 'Rome', 'local': 'Roma', 'wiki': 'Rome', 'best': [4, 5, 6, 9, 10], 'days': '3–4 ngày',
     'intro': 'Thành phố vĩnh cửu: đấu trường Colosseum, Vatican, đài phun nước Trevi và mì Ý chính gốc.',
     'places': [
        ('s', 'Đấu trường Colosseum', 'Colosseum', 'Đấu trường La Mã gần 2.000 năm tuổi', {'price': '~18 EUR (vé gộp Forum)', 'v': 540, 'd': 120, 't': 'hpk', 'io': 'o', 'h': 'Khoảng 9:00 – trước hoàng hôn'}),
        ('s', 'Quảng trường La Mã cổ (Forum)', 'Roman Forum', 'Trung tâm chính trị Rome cổ đại, cạnh Colosseum', {'v': 0, 'd': 90, 't': 'hp', 'io': 'o'}),
        ('s', 'Bảo tàng Vatican và nhà nguyện Sistine', 'Vatican Museums', 'Kiệt tác trần nhà của Michelangelo', {'price': '~20–25 EUR', 'v': 700, 'd': 180, 't': 'hk', 'io': 'i', 'cl': [0], 'h': 'Thường 8:00–19:00, nghỉ Chủ nhật (trừ CN cuối tháng)'}),
        ('s', 'Vương cung thánh đường Thánh Phêrô', "St. Peter's Basilica", 'Nhà thờ lớn nhất thế giới, leo mái vòm ngắm Vatican', {'v': 0, 'd': 90, 't': 'hpk', 'io': 'm', 'mo': 1}),
        ('c', 'Đài phun nước Trevi', 'Trevi Fountain', 'Ném đồng xu để hẹn ngày trở lại Rome', {'v': 0, 'd': 30, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('s', 'Đền Pantheon', 'Pantheon, Rome', 'Đền cổ với mái vòm bê tông lớn nhất thời La Mã', {'price': '~5 EUR', 'v': 150, 'd': 45, 't': 'hk', 'io': 'i'}),
        ('c', 'Bậc thang Tây Ban Nha', 'Spanish Steps', 'Bậc thang nổi tiếng nối quảng trường Tây Ban Nha', {'v': 0, 'd': 30, 't': 'p', 'io': 'o', 'ev': 'all'}),
        ('c', 'Quảng trường Navona', 'Piazza Navona', 'Quảng trường Baroque với ba đài phun nước', {'k': 'check,cafe', 'v': 0, 'd': 45, 't': 'pc', 'io': 'o', 'ev': 'all'}),
        ('f', 'Khu Trastevere', 'Trastevere', 'Ngõ nhỏ quán ăn Rome truyền thống: carbonara, cacio e pepe', {'k': 'trua,toi', 'v': 500, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('f', 'Chợ Campo de\' Fiori', "Campo de' Fiori", 'Chợ buổi sáng và quảng trường nhiều quán ăn', {'k': 'sang,trua', 'v': 300, 't': 's', 'io': 'o', 'cl': [0]}),
        ('c', 'Vườn Villa Borghese', 'Villa Borghese gardens', 'Công viên rộng, sân Pincio ngắm hoàng hôn', {'v': 0, 'd': 75, 't': 'nr', 'io': 'o', 'ss': 1}),
        ('s', 'Lâu đài Thiên Thần', "Castel Sant'Angelo", 'Lăng mộ La Mã thành pháo đài bên sông Tiber', {'price': '~16 EUR', 'v': 480, 'd': 75, 't': 'hp', 'io': 'm'}),
        ('f', 'Khu Monti', 'Monti (rione of Rome)', 'Khu phố trẻ gần Colosseum, cà phê và pizza cắt lát', {'k': 'cafe,trua,sang', 'v': 300, 't': 'cs', 'io': 'm'}),
     ]},
    {'id': 'venice', 'country': 'it', 'name': 'Venice', 'local': 'Venezia', 'wiki': 'Venice', 'best': [4, 5, 6, 9, 10], 'days': '2 ngày',
     'intro': 'Thành phố trên mặt nước với kênh đào, thuyền gondola và quảng trường San Marco.',
     'places': [
        ('c', 'Quảng trường San Marco', "St Mark's Square", 'Trái tim của Venice, quán cà phê có ban nhạc', {'k': 'check,cafe', 'v': 0, 'd': 60, 't': 'hpk', 'io': 'o', 'ev': 'all'}),
        ('s', 'Vương cung thánh đường San Marco', "St Mark's Basilica", 'Nhà thờ dát vàng mosaic Byzantine', {'price': '~3–6 EUR', 'v': 180, 'd': 60, 't': 'hk', 'io': 'i'}),
        ('s', 'Cung điện Doge', "Doge's Palace", 'Cung điện các tổng trấn và cầu Than thở', {'price': '~30 EUR', 'v': 900, 'd': 120, 't': 'h', 'io': 'i'}),
        ('c', 'Cầu Rialto', 'Rialto Bridge', 'Cây cầu đá cổ nhất qua kênh Grand Canal', {'v': 0, 'd': 30, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('c', 'Đi thuyền gondola', 'Gondola', 'Thuyền gondola qua các kênh nhỏ', {'price': '~90–120 EUR/thuyền', 'v': 1600, 'd': 40, 't': 'pr', 'io': 'o', 'ss': 1, 'll': [45.4370, 12.3360]}),
        ('c', 'Kênh Grand Canal (thủy buýt số 1)', 'Grand Canal (Venice)', 'Đi vaporetto số 1 ngắm dinh thự hai bên kênh', {'price': '~9,5 EUR/lượt', 'v': 290, 'd': 60, 't': 'p', 'io': 'o'}),
        ('c', 'Đảo Burano', 'Burano', 'Đảo nhà nhiều màu và nghề làm ren', {'v': 290, 'd': 180, 't': 'p', 'io': 'o'}),
        ('s', 'Đảo Murano', 'Murano', 'Làng thủy tinh nổi tiếng, xem thổi thủy tinh', {'v': 0, 'd': 120, 't': 'h', 'io': 'm'}),
        ('f', 'Chợ Rialto', 'Rialto Market', 'Chợ cá, rau buổi sáng; quán cicchetti (tapas Venice) quanh chợ', {'k': 'sang,trua,vat', 'v': 300, 't': 's', 'io': 'o', 'mo': 1, 'cl': [0, 1]}),
        ('f', 'Khu Cannaregio', 'Cannaregio', 'Khu dân cư yên tĩnh, quán ăn địa phương giá mềm', {'k': 'trua,toi', 'v': 450, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('s', 'Nhà thờ Santa Maria della Salute', 'Santa Maria della Salute', 'Mái vòm trắng ở cửa kênh Grand Canal', {'v': 0, 'd': 30, 't': 'hp', 'io': 'm', 'ss': 1}),
     ]},
    {'id': 'florence', 'country': 'it', 'name': 'Florence', 'local': 'Firenze', 'wiki': 'Florence', 'best': [4, 5, 6, 9, 10], 'days': '2–3 ngày',
     'intro': 'Cái nôi Phục Hưng: mái vòm Duomo, tượng David và vùng đồi Tuscany.',
     'places': [
        ('s', 'Nhà thờ chính tòa Florence (Duomo)', 'Florence Cathedral', 'Mái vòm Brunelleschi biểu tượng của thành phố', {'price': '~20–30 EUR (leo mái vòm)', 'v': 750, 'd': 120, 't': 'hpk', 'io': 'm', 'f': 'o'}),
        ('s', 'Phòng tranh Uffizi', 'Uffizi', 'Tranh Botticelli, Leonardo, Raphael', {'price': '~25 EUR', 'v': 750, 'd': 150, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('s', 'Viện Accademia – tượng David', 'Galleria dell\'Accademia', 'Tượng David nguyên bản của Michelangelo', {'price': '~16 EUR', 'v': 480, 'd': 75, 't': 'hk', 'io': 'i', 'cl': [1]}),
        ('c', 'Cầu Ponte Vecchio', 'Ponte Vecchio', 'Cây cầu cổ có tiệm kim hoàn hai bên', {'v': 0, 'd': 30, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('c', 'Quảng trường Michelangelo', 'Piazzale Michelangelo', 'Điểm ngắm hoàng hôn toàn cảnh Florence', {'v': 0, 'd': 60, 't': 'p', 'io': 'o', 'ss': 1}),
        ('c', 'Quảng trường Signoria', 'Piazza della Signoria', 'Quảng trường tượng ngoài trời, cung Palazzo Vecchio', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'ev': 'all'}),
        ('s', 'Vườn Boboli', 'Boboli Gardens', 'Vườn Ý của gia tộc Medici sau cung Pitti', {'price': '~10 EUR', 'v': 300, 'd': 90, 't': 'nh', 'io': 'o'}),
        ('f', 'Chợ trung tâm Mercato Centrale', 'Mercato Centrale (Florence)', 'Tầng trên là khu ẩm thực, bánh mì lòng bò lampredotto', {'k': 'trua,toi,sang', 'v': 350, 't': 's', 'io': 'i'}),
        ('f', 'Khu Oltrarno', 'Oltrarno', 'Bờ nam sông Arno, quán ăn và xưởng thủ công', {'k': 'toi,cafe', 'v': 500, 't': 'sc', 'io': 'm', 'ev': 'all'}),
        ('s', 'Tháp nghiêng Pisa', 'Leaning Tower of Pisa', 'Tháp nghiêng nổi tiếng, đi tàu khoảng 1 giờ từ Florence', {'price': '~20 EUR (leo tháp)', 'v': 600, 'd': 240, 't': 'hpk', 'io': 'o', 'trip': 1}),
        ('c', 'Vùng rượu vang Chianti', 'Chianti', 'Đồi nho Tuscany, thử rượu vang tại trang trại', {'v': 1500, 'd': 360, 't': 'nr', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- THỤY SĨ ----------------
    {'id': 'swiss', 'country': 'ch', 'name': 'Thụy Sĩ (Lucerne – Interlaken – Zurich)', 'local': 'Schweiz', 'wiki': 'Lucerne', 'best': [6, 7, 8, 9, 12, 1, 2], 'days': '4–5 ngày',
     'intro': 'Hồ trong xanh, làng núi Alps, tàu lên đỉnh Jungfraujoch và thị trấn cổ Lucerne.',
     'places': [
        ('c', 'Cầu gỗ Chapel (Lucerne)', 'Chapel Bridge', 'Cây cầu gỗ có mái cổ nhất châu Âu', {'v': 0, 'd': 30, 't': 'hpk', 'io': 'o', 'a': 'Lucerne'}),
        ('s', 'Núi Pilatus', 'Pilatus', 'Tàu răng cưa dốc nhất thế giới và cáp treo ngắm Alps', {'price': '~70–110 CHF', 'v': 2900, 'd': 300, 't': 'nmk', 'io': 'o', 'a': 'Lucerne'}),
        ('s', 'Núi Rigi', 'Rigi', '"Nữ hoàng núi non", tàu lên đỉnh ngắm hồ', {'price': '~60–80 CHF', 'v': 2200, 'd': 300, 't': 'nm', 'io': 'o', 'a': 'Lucerne'}),
        ('c', 'Tượng Sư tử Lucerne', 'Lion Monument', 'Tượng sư tử khắc vào vách đá', {'v': 0, 'd': 20, 't': 'h', 'io': 'o', 'a': 'Lucerne'}),
        ('c', 'Hồ Lucerne (du thuyền)', 'Lake Lucerne', 'Du thuyền giữa núi và làng ven hồ', {'price': '~30–60 CHF', 'v': 1400, 'd': 120, 't': 'nr', 'io': 'o', 'ss': 1, 'a': 'Lucerne'}),
        ('f', 'Phố cổ Lucerne', 'Old Town Lucerne', 'Phố cổ nhà vẽ tranh tường, quán ăn ven sông Reuss', {'k': 'trua,toi,cafe', 'v': 650, 't': 'sh', 'io': 'm', 'ev': 'all', 'll': [47.0516, 8.3062], 'a': 'Lucerne'}),
        ('s', 'Jungfraujoch – "Nóc nhà châu Âu"', 'Jungfraujoch', 'Ga tàu cao nhất châu Âu, sông băng Aletsch', {'price': '~200 CHF khứ hồi', 'v': 6400, 'd': 420, 't': 'nmk', 'io': 'o', 'mo': 1, 'a': 'Interlaken'}),
        ('c', 'Làng Grindelwald', 'Grindelwald', 'Làng núi dưới chân vách Eiger, cáp treo First', {'v': 0, 'd': 180, 't': 'nm', 'io': 'o', 'a': 'Interlaken'}),
        ('c', 'Thung lũng Lauterbrunnen', 'Lauterbrunnen', 'Thung lũng 72 thác nước, thác Staubbach', {'v': 0, 'd': 150, 't': 'np', 'io': 'o', 'a': 'Interlaken'}),
        ('c', 'Harder Kulm', 'Harder Kulm', 'Đài ngắm hai hồ Thun, Brienz và núi Jungfrau', {'price': '~40 CHF', 'v': 1270, 'd': 90, 't': 'np', 'io': 'o', 'ss': 1, 'a': 'Interlaken'}),
        ('c', 'Hồ Brienz – làng Iseltwald', 'Lake Brienz', 'Hồ màu ngọc lam, bến tàu làng Iseltwald', {'v': 0, 'd': 120, 't': 'nrp', 'io': 'o', 'a': 'Interlaken'}),
        ('f', 'Phố Höheweg (Interlaken)', 'Interlaken', 'Phố chính Interlaken nhìn ra núi Jungfrau, nhà hàng fondue', {'k': 'trua,toi,cafe', 'v': 650, 't': 's', 'io': 'm', 'ev': 'all', 'a': 'Interlaken'}),
        ('c', 'Phố cổ Zurich', 'Old Town (Zurich)', 'Phố cổ hai bờ sông Limmat, nhà thờ Grossmünster', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'hp', 'io': 'o', 'll': [47.3717, 8.5434], 'a': 'Zurich'}),
        ('c', 'Hồ Zurich', 'Lake Zurich', 'Dạo bờ hồ, du thuyền ngắn', {'v': 0, 'd': 90, 't': 'nr', 'io': 'o', 'ss': 1, 'a': 'Zurich'}),
        ('f', 'Phố Bahnhofstrasse', 'Bahnhofstrasse', 'Phố mua sắm đắt đỏ nhất, chocolate Thụy Sĩ', {'k': 'cafe,trua', 'v': 550, 't': 'c', 'io': 'm', 'a': 'Zurich'}),
        ('s', 'Bảo tàng Quốc gia Thụy Sĩ', 'Swiss National Museum', 'Lịch sử và văn hóa Thụy Sĩ trong lâu đài cổ', {'price': '~10 CHF', 'v': 320, 'd': 90, 't': 'h', 'io': 'i', 'cl': [1], 'a': 'Zurich'}),
     ]},
    # ---------------- ANH ----------------
    {'id': 'london', 'country': 'gb', 'name': 'London', 'local': 'London', 'wiki': 'London', 'best': [5, 6, 7, 8, 9], 'days': '4–5 ngày',
     'intro': 'Thủ đô nước Anh: Big Ben, cung điện Buckingham, bảo tàng miễn phí và chợ ẩm thực.',
     'places': [
        ('c', 'Big Ben và Tòa nhà Quốc hội', 'Big Ben', 'Tháp đồng hồ biểu tượng bên sông Thames', {'v': 0, 'd': 30, 't': 'hpk', 'io': 'o', 'ev': 'all'}),
        ('s', 'Tu viện Westminster', 'Westminster Abbey', 'Nơi đăng quang của các vua Anh', {'price': '~30 GBP', 'v': 1050, 'd': 90, 't': 'hk', 'io': 'i', 'cl': [0]}),
        ('c', 'Cung điện Buckingham', 'Buckingham Palace', 'Xem lễ đổi gác trước cung điện', {'v': 0, 'd': 60, 't': 'hpk', 'io': 'o', 'mo': 1}),
        ('c', 'Vòng quay London Eye', 'London Eye', 'Ngắm toàn cảnh London từ cabin kính', {'price': '~30–40 GBP', 'v': 1200, 'd': 60, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('s', 'Tháp London', 'Tower of London', 'Pháo đài cổ cất giữ vương miện hoàng gia', {'price': '~35 GBP', 'v': 1220, 'd': 150, 't': 'hk', 'io': 'm'}),
        ('c', 'Cầu Tháp (Tower Bridge)', 'Tower Bridge', 'Cây cầu nâng biểu tượng London', {'v': 0, 'd': 30, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('s', 'Bảo tàng Anh', 'British Museum', 'Bảo tàng lịch sử lớn, miễn phí: đá Rosetta, xác ướp Ai Cập', {'v': 0, 'd': 180, 't': 'hk', 'io': 'i'}),
        ('s', 'Bảo tàng Lịch sử Tự nhiên', 'Natural History Museum, London', 'Khủng long và sảnh Hintze, miễn phí, hợp trẻ em', {'v': 0, 'd': 150, 't': 'h', 'io': 'i'}),
        ('c', 'Công viên Hyde Park', 'Hyde Park, London', 'Công viên lớn giữa trung tâm, hồ Serpentine', {'v': 0, 'd': 75, 't': 'nr', 'io': 'o'}),
        ('f', 'Chợ Borough', 'Borough Market', 'Chợ ẩm thực lâu đời: bánh pie, phô mai, đồ nướng', {'k': 'trua,vat,sang', 'v': 450, 't': 's', 'io': 'm', 'cl': [1]}),
        ('f', 'Covent Garden', 'Covent Garden', 'Khu chợ có mái, biểu diễn đường phố, quán ăn', {'k': 'trua,cafe,toi', 'v': 500, 't': 'sp', 'io': 'm', 'ev': 'all'}),
        ('f', 'Khu phố Tàu London', 'Chinatown, London', 'Quán vịt quay, dim sum gần Leicester Square', {'k': 'toi,trua', 'v': 450, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('c', 'Quảng trường Trafalgar', 'Trafalgar Square', 'Quảng trường trung tâm, Phòng tranh Quốc gia miễn phí', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o'}),
        ('c', 'Ga King\'s Cross – sân ga 9¾', "King's Cross station", 'Góc chụp ảnh xe đẩy Harry Potter', {'v': 0, 'd': 30, 't': 'p', 'io': 'i'}),
        ('s', 'Lâu đài Windsor', 'Windsor Castle', 'Lâu đài hoàng gia còn sử dụng lâu đời nhất, đi tàu khoảng 1 giờ', {'price': '~30 GBP', 'v': 1050, 'd': 300, 't': 'hk', 'io': 'm', 'cl': [2, 3], 'trip': 1}),
        ('s', 'Stonehenge', 'Stonehenge', 'Vòng đá cự thạch thời tiền sử', {'price': '~25–30 GBP', 'v': 1000, 'd': 360, 't': 'hn', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- ĐỨC ----------------
    {'id': 'munich', 'country': 'de', 'name': 'Munich', 'local': 'München', 'wiki': 'Munich', 'best': [5, 6, 7, 8, 9, 12], 'days': '3 ngày',
     'intro': 'Thủ phủ bang Bavaria: quảng trường Marienplatz, bia và xúc xích, cửa ngõ tới lâu đài Neuschwanstein.',
     'places': [
        ('c', 'Quảng trường Marienplatz', 'Marienplatz', 'Tòa thị chính mới, đồng hồ có hình nhân nhảy múa', {'v': 0, 'd': 45, 't': 'hpk', 'io': 'o', 'ev': 'all'}),
        ('f', 'Chợ Viktualienmarkt', 'Viktualienmarkt', 'Chợ ẩm thực ngoài trời: xúc xích, bánh pretzel', {'k': 'trua,vat,sang', 'v': 350, 't': 's', 'io': 'o', 'cl': [0]}),
        ('f', 'Hofbräuhaus', 'Hofbräuhaus am Platzl', 'Quán bia lịch sử từ 1589, nhạc dân gian Bavaria', {'k': 'toi,trua', 'v': 600, 't': 'sh', 'io': 'i', 'ev': 'all'}),
        ('s', 'Cung điện Residenz', 'Munich Residenz', 'Cung điện hoàng gia Bavaria với hơn 130 phòng', {'price': '~10–15 EUR', 'v': 450, 'd': 120, 't': 'h', 'io': 'i'}),
        ('s', 'Cung điện Nymphenburg', 'Nymphenburg Palace', 'Cung điện mùa hè Baroque và vườn rộng', {'price': '~10–20 EUR', 'v': 450, 'd': 120, 't': 'hn', 'io': 'm'}),
        ('c', 'Khu vườn Anh (Englischer Garten)', 'Englischer Garten', 'Công viên lớn, xem lướt sóng trên sông Eisbach', {'v': 0, 'd': 90, 't': 'nr', 'io': 'o'}),
        ('s', 'BMW Welt và bảo tàng BMW', 'BMW Welt', 'Trưng bày xe BMW, gần công viên Olympic', {'v': 0, 'd': 90, 't': 'p', 'io': 'i'}),
        ('c', 'Công viên Olympic', 'Olympiapark (Munich)', 'Tháp Olympic ngắm toàn thành phố và dãy Alps', {'price': '~13 EUR (lên tháp)', 'v': 390, 'd': 90, 't': 'p', 'io': 'o', 'ss': 1}),
        ('s', 'Nhà thờ Đức Bà Munich', 'Frauenkirche, Munich', 'Hai ngọn tháp mái vòm biểu tượng thành phố', {'v': 0, 'd': 30, 't': 'h', 'io': 'i'}),
        ('s', 'Bảo tàng Deutsches', 'Deutsches Museum', 'Bảo tàng khoa học kỹ thuật lớn nhất thế giới', {'price': '~15–20 EUR', 'v': 600, 'd': 180, 't': 'h', 'io': 'i'}),
        ('s', 'Lâu đài Neuschwanstein', 'Neuschwanstein Castle', 'Lâu đài cổ tích giữa núi, hình mẫu lâu đài Disney', {'price': '~20 EUR', 'v': 600, 'd': 360, 't': 'hnpk', 'io': 'm', 'trip': 1}),
        ('s', 'Đài tưởng niệm Dachau', 'Dachau concentration camp', 'Trại tập trung thời Thế chiến II, nay là nơi tưởng niệm', {'v': 0, 'd': 240, 't': 'h', 'io': 'm', 'trip': 1}),
     ]},
    # ---------------- HÀ LAN ----------------
    {'id': 'amsterdam', 'country': 'nl', 'name': 'Amsterdam', 'local': 'Amsterdam', 'wiki': 'Amsterdam', 'best': [4, 5, 6, 7, 8, 9], 'days': '3 ngày',
     'intro': 'Thành phố kênh đào, xe đạp và bảo tàng hội họa; mùa xuân có hoa tulip Keukenhof.',
     'places': [
        ('s', 'Bảo tàng Rijksmuseum', 'Rijksmuseum', 'Tranh Rembrandt "Đội tuần tra đêm", Vermeer', {'price': '~25 EUR', 'v': 750, 'd': 150, 't': 'hk', 'io': 'i'}),
        ('s', 'Bảo tàng Van Gogh', 'Van Gogh Museum', 'Bộ sưu tập tranh Van Gogh lớn nhất thế giới', {'price': '~22 EUR', 'v': 660, 'd': 120, 't': 'hk', 'io': 'i'}),
        ('s', 'Nhà Anne Frank', 'Anne Frank House', 'Nơi Anne Frank viết nhật ký khi lẩn trốn', {'price': '~16 EUR', 'v': 480, 'd': 75, 't': 'h', 'io': 'i'}),
        ('c', 'Du thuyền kênh đào', 'Canals of Amsterdam', 'Đi thuyền qua vành đai kênh di sản UNESCO', {'price': '~18–25 EUR', 'v': 600, 'd': 75, 't': 'pr', 'io': 'o', 'ss': 1, 'ev': 'all'}),
        ('c', 'Quảng trường Dam', 'Dam Square', 'Quảng trường trung tâm, Cung điện Hoàng gia', {'v': 0, 'd': 30, 't': 'h', 'io': 'o'}),
        ('c', 'Công viên Vondelpark', 'Vondelpark', 'Công viên lớn, đạp xe và dã ngoại', {'v': 0, 'd': 60, 't': 'nr', 'io': 'o'}),
        ('f', 'Khu Jordaan', 'Jordaan', 'Phố kênh nhỏ, quán cà phê nâu, bánh táo', {'k': 'cafe,trua', 'v': 400, 't': 'cs', 'io': 'm'}),
        ('f', 'Chợ Albert Cuyp', 'Albert Cuyp Market', 'Chợ đường phố: bánh stroopwafel, cá trích', {'k': 'sang,trua,vat', 'v': 250, 't': 's', 'io': 'o', 'cl': [0]}),
        ('f', 'Foodhallen', 'Foodhallen', 'Khu ẩm thực trong xưởng xe điện cũ', {'k': 'toi,trua', 'v': 450, 't': 's', 'io': 'i', 'ev': 'all'}),
        ('c', 'Đài A\'DAM Lookout', "A'DAM Tower", 'Đài ngắm cảnh có xích đu trên nóc tòa nhà', {'price': '~16 EUR', 'v': 480, 'd': 60, 't': 'p', 'io': 'm', 'ss': 1}),
        ('c', 'Làng cối xay gió Zaanse Schans', 'Zaanse Schans', 'Cối xay gió, xưởng guốc gỗ và phô mai', {'v': 0, 'd': 240, 't': 'hp', 'io': 'o', 'trip': 1}),
        ('c', 'Vườn hoa Keukenhof', 'Keukenhof', 'Vườn tulip lớn nhất thế giới (chỉ mở khoảng 3–5)', {'price': '~20 EUR', 'v': 600, 'd': 300, 't': 'np', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- TÂY BAN NHA ----------------
    {'id': 'barcelona', 'country': 'es', 'name': 'Barcelona', 'local': 'Barcelona', 'wiki': 'Barcelona', 'best': [5, 6, 9, 10], 'days': '3–4 ngày',
     'intro': 'Kiến trúc Gaudí, khu phố Gothic, bãi biển và ẩm thực tapas.',
     'places': [
        ('s', 'Nhà thờ Sagrada Família', 'Sagrada Família', 'Kiệt tác dang dở của Gaudí, ánh sáng kính màu tuyệt đẹp', {'price': '~26–36 EUR', 'v': 900, 'd': 120, 't': 'hpk', 'io': 'i'}),
        ('c', 'Công viên Park Güell', 'Park Güell', 'Công viên khảm gốm sặc sỡ của Gaudí', {'price': '~18 EUR', 'v': 540, 'd': 90, 't': 'pk', 'io': 'o', 'f': 'o'}),
        ('s', 'Casa Batlló', 'Casa Batlló', 'Ngôi nhà "xương rồng" của Gaudí', {'price': '~35 EUR', 'v': 1050, 'd': 75, 't': 'hp', 'io': 'i', 'ev': 'all'}),
        ('s', 'Casa Milà (La Pedrera)', 'Casa Milà', 'Mái nhà ống khói hình chiến binh', {'price': '~28 EUR', 'v': 840, 'd': 75, 't': 'h', 'io': 'm'}),
        ('c', 'Khu phố Gothic', 'Gothic Quarter, Barcelona', 'Ngõ đá cổ quanh nhà thờ chính tòa', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'hp', 'io': 'o', 'ev': 'all'}),
        ('f', 'Phố La Rambla', 'La Rambla, Barcelona', 'Đại lộ đi bộ sầm uất nhất thành phố', {'k': 'check,vat', 'v': 0, 'd': 45, 't': 'p', 'io': 'o', 'ev': 'all'}),
        ('f', 'Chợ La Boqueria', 'Mercat de la Boqueria', 'Chợ trái cây, jamón, hải sản; quầy ăn tại chỗ', {'k': 'sang,trua,vat', 'v': 350, 't': 's', 'io': 'm', 'cl': [0]}),
        ('f', 'Khu El Born', 'El Born', 'Phố quán tapas, bar rượu nhỏ', {'k': 'toi,cafe', 'v': 450, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('c', 'Bãi biển Barceloneta', 'Barceloneta beach', 'Bãi biển thành phố, quán paella ven biển', {'k': 'check,trua', 'v': 0, 'd': 120, 't': 'br', 'io': 'o', 'ss': 1}),
        ('c', 'Đồi Montjuïc', 'Montjuïc', 'Cáp treo, lâu đài và đài phun nước Magic', {'v': 0, 'd': 150, 't': 'np', 'io': 'o', 'ss': 1}),
        ('s', 'Sân Camp Nou', 'Camp Nou', 'Sân nhà FC Barcelona', {'price': '~30 EUR', 'v': 900, 'd': 90, 't': 'p', 'io': 'm'}),
        ('s', 'Tu viện Montserrat', 'Montserrat (mountain)', 'Tu viện trên núi đá răng cưa, đi tàu khoảng 1 giờ', {'v': 300, 'd': 300, 't': 'hn', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- SÉC ----------------
    {'id': 'prague', 'country': 'cz', 'name': 'Praha', 'local': 'Praha', 'wiki': 'Prague', 'best': [4, 5, 6, 9, 10, 12], 'days': '2–3 ngày',
     'intro': 'Thành phố trăm tháp: cầu Charles, lâu đài Praha và đồng hồ thiên văn cổ.',
     'places': [
        ('s', 'Lâu đài Praha', 'Prague Castle', 'Quần thể lâu đài cổ lớn nhất thế giới, nhà thờ St. Vitus', {'price': '~450–550 CZK', 'v': 600, 'd': 180, 't': 'hpk', 'io': 'm'}),
        ('c', 'Cầu Charles', 'Charles Bridge', 'Cây cầu đá cổ với 30 bức tượng, đẹp lúc bình minh', {'v': 0, 'd': 45, 't': 'hpk', 'io': 'o', 'ss': 1, 'ev': 'all'}),
        ('c', 'Quảng trường Phố cổ', 'Old Town Square', 'Nhà thờ Týn và đồng hồ thiên văn', {'k': 'check,cafe', 'v': 0, 'd': 60, 't': 'hpk', 'io': 'o', 'ev': 'all'}),
        ('s', 'Đồng hồ thiên văn Praha', 'Prague astronomical clock', 'Đồng hồ thiên văn từ 1410, tượng diễu hành mỗi giờ', {'price': '~300 CZK (lên tháp)', 'v': 360, 'd': 45, 't': 'h', 'io': 'm'}),
        ('c', 'Khu Malá Strana', 'Malá Strana', 'Phố Baroque dưới chân lâu đài', {'k': 'check,cafe', 'v': 0, 'd': 75, 't': 'hp', 'io': 'o'}),
        ('c', 'Đồi Petřín', 'Petřín', 'Tháp quan sát và vườn hồng nhìn ra thành phố', {'v': 180, 'd': 90, 't': 'np', 'io': 'o', 'ss': 1}),
        ('c', 'Bức tường John Lennon', 'Lennon Wall', 'Bức tường vẽ graffiti đầy màu sắc', {'v': 0, 'd': 20, 't': 'p', 'io': 'o'}),
        ('s', 'Khu Do Thái Josefov', 'Josefov', 'Giáo đường và nghĩa trang Do Thái cổ', {'price': '~500 CZK', 'v': 600, 'd': 90, 't': 'h', 'io': 'm', 'cl': [6]}),
        ('c', 'Quảng trường Wenceslas', 'Wenceslas Square', 'Đại lộ trung tâm thành phố mới', {'v': 0, 'd': 30, 't': 'h', 'io': 'o'}),
        ('f', 'Phố ẩm thực Naplavka', 'Náplavka', 'Bến sông có chợ nông sản cuối tuần, quán bar thuyền', {'k': 'trua,toi,vat', 'v': 300, 't': 's', 'io': 'o', 'ev': 'all'}),
        ('f', 'Chợ Sapa (khu người Việt)', 'Sapa (Prague)', 'Khu chợ của cộng đồng người Việt, nhiều quán phở, bún', {'k': 'trua,toi', 'v': 200, 't': 's', 'io': 'm'}),
        ('s', 'Český Krumlov', 'Český Krumlov', 'Thị trấn cổ tích di sản UNESCO, cách Praha ~3 giờ', {'v': 400, 'd': 300, 't': 'hp', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- ÁO ----------------
    {'id': 'vienna', 'country': 'at', 'name': 'Vienna', 'local': 'Wien', 'wiki': 'Vienna', 'best': [4, 5, 6, 9, 10, 12], 'days': '2–3 ngày',
     'intro': 'Thủ đô âm nhạc: cung điện Schönbrunn, nhà hát Opera và quán cà phê cổ.',
     'places': [
        ('s', 'Cung điện Schönbrunn', 'Schönbrunn Palace', 'Cung điện mùa hè của hoàng gia Habsburg, vườn rộng', {'price': '~30–45 EUR', 'v': 1100, 'd': 180, 't': 'hpk', 'io': 'm'}),
        ('s', 'Cung điện Hofburg', 'Hofburg', 'Cung điện hoàng gia, bảo tàng Sisi', {'price': '~20 EUR', 'v': 600, 'd': 120, 't': 'h', 'io': 'i'}),
        ('s', 'Nhà thờ St. Stephen', "St. Stephen's Cathedral, Vienna", 'Nhà thờ Gothic với mái ngói hoa văn', {'v': 0, 'd': 45, 't': 'hk', 'io': 'i'}),
        ('s', 'Nhà hát Opera Quốc gia', 'Vienna State Opera', 'Nhà hát opera nổi tiếng thế giới, có vé đứng giá rẻ', {'price': '~15–250 EUR', 'v': 800, 'd': 180, 't': 'hk', 'io': 'i', 'ev': 'all', 'eo': 1}),
        ('s', 'Cung điện Belvedere', 'Belvedere, Vienna', 'Tranh "Nụ hôn" của Klimt', {'price': '~17 EUR', 'v': 510, 'd': 90, 't': 'h', 'io': 'i'}),
        ('f', 'Chợ Naschmarkt', 'Naschmarkt', 'Chợ ẩm thực dài 1,5 km', {'k': 'trua,sang,vat', 'v': 350, 't': 's', 'io': 'o', 'cl': [0]}),
        ('f', 'Café Central', 'Café Central', 'Quán cà phê Vienna cổ điển từ 1876', {'k': 'cafe,sang', 'v': 350, 't': 'ch', 'io': 'i'}),
        ('c', 'Vòng đu quay Prater', 'Wiener Riesenrad', 'Vòng đu quay cổ trong công viên Prater', {'price': '~15 EUR', 'v': 450, 'd': 60, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('c', 'Nhà Hundertwasser', 'Hundertwasserhaus', 'Tòa nhà nhiều màu, mái phủ cây', {'v': 0, 'd': 30, 't': 'p', 'io': 'o'}),
        ('f', 'Khu MuseumsQuartier', 'MuseumsQuartier', 'Khu bảo tàng và quán ngoài trời', {'k': 'toi,cafe', 'v': 450, 't': 'c', 'io': 'm', 'ev': 'all'}),
        ('s', 'Thung lũng Wachau', 'Wachau Valley', 'Thung lũng rượu vang bên sông Danube, tu viện Melk', {'v': 900, 'd': 360, 't': 'nh', 'io': 'o', 'trip': 1}),
        ('s', 'Hallstatt', 'Hallstatt', 'Làng ven hồ đẹp như tranh (xa ~4 giờ)', {'v': 600, 'd': 300, 't': 'npk', 'io': 'o', 'trip': 1}),
     ]},
    # ---------------- THỔ NHĨ KỲ ----------------
    {'id': 'istanbul', 'country': 'tr', 'name': 'Istanbul', 'local': 'İstanbul', 'wiki': 'Istanbul', 'best': [4, 5, 9, 10, 11], 'days': '3–4 ngày',
     'intro': 'Thành phố nằm trên hai châu lục: Hagia Sophia, Thánh đường Xanh và chợ Grand Bazaar.',
     'places': [
        ('s', 'Hagia Sophia', 'Hagia Sophia', 'Công trình gần 1.500 năm: nhà thờ, thánh đường rồi bảo tàng', {'price': '~25 EUR (khách nước ngoài)', 'v': 750, 'd': 75, 't': 'hk', 'io': 'i'}),
        ('s', 'Thánh đường Xanh', 'Blue Mosque', 'Thánh đường sáu tháp với gạch men xanh', {'v': 0, 'd': 45, 't': 'hpk', 'io': 'i'}),
        ('s', 'Cung điện Topkapı', 'Topkapı Palace', 'Cung điện các vua Ottoman, kho báu và hậu cung', {'price': '~2.400 TRY', 'v': 1300, 'd': 150, 't': 'hk', 'io': 'm', 'cl': [2]}),
        ('s', 'Bể chứa nước ngầm Basilica', 'Basilica Cistern', 'Hầm chứa nước cổ với hàng trăm cột đá', {'price': '~1.300 TRY', 'v': 700, 'd': 45, 't': 'hp', 'io': 'i'}),
        ('f', 'Chợ Grand Bazaar', 'Grand Bazaar', 'Một trong những chợ có mái lớn nhất thế giới', {'k': 'check,trua,vat', 'v': 200, 't': 'sp', 'io': 'i', 'cl': [0]}),
        ('f', 'Chợ Gia vị', 'Spice Bazaar', 'Chợ gia vị, kẹo Thổ, trà táo', {'k': 'vat,trua', 'v': 150, 't': 's', 'io': 'i'}),
        ('c', 'Du thuyền eo biển Bosphorus', 'Bosporus', 'Thuyền giữa châu Âu và châu Á', {'price': '~300–600 TRY', 'v': 300, 'd': 120, 't': 'pr', 'io': 'o', 'ss': 1}),
        ('c', 'Tháp Galata', 'Galata Tower', 'Tháp đá thời trung cổ, ngắm toàn cảnh', {'price': '~30 EUR', 'v': 900, 'd': 60, 't': 'hp', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('f', 'Phố İstiklal và quảng trường Taksim', 'İstiklal Avenue', 'Phố đi bộ, tàu điện đỏ cổ, quán ăn', {'k': 'toi,cafe,vat', 'v': 250, 't': 's', 'io': 'o', 'ev': 'all'}),
        ('s', 'Cung điện Dolmabahçe', 'Dolmabahçe Palace', 'Cung điện xa hoa bên eo Bosphorus', {'price': '~1.800 TRY', 'v': 950, 'd': 120, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('f', 'Khu Karaköy', 'Karaköy', 'Quán cà phê, bánh baklava Karaköy Güllüoğlu', {'k': 'cafe,sang', 'v': 200, 't': 'cs', 'io': 'm'}),
        ('f', 'Chợ Kadıköy (bờ châu Á)', 'Kadıköy', 'Đi phà sang bờ châu Á ăn hải sản, đồ ăn vặt', {'k': 'trua,toi', 'v': 300, 't': 's', 'io': 'm', 'ss': 1}),
     ]},
    {'id': 'cappadocia', 'country': 'tr', 'name': 'Cappadocia', 'local': 'Kapadokya', 'wiki': 'Cappadocia', 'best': [4, 5, 6, 9, 10], 'days': '2–3 ngày',
     'intro': 'Thung lũng đá "ống khói tiên", khinh khí cầu lúc bình minh và khách sạn trong hang đá.',
     'places': [
        ('c', 'Bay khinh khí cầu', 'Göreme National Park', 'Bay lúc bình minh trên thung lũng đá', {'price': '~200–350 EUR', 'v': 7500, 'd': 240, 't': 'npk', 'io': 'o', 'mo': 1, 'f': 'x'}),
        ('s', 'Bảo tàng ngoài trời Göreme', 'Göreme Open Air Museum', 'Nhà thờ trong hang đá với bích họa Byzantine', {'price': '~20 EUR', 'v': 600, 'd': 120, 't': 'h', 'io': 'm'}),
        ('s', 'Thành phố ngầm Derinkuyu', 'Derinkuyu underground city', 'Thành phố dưới lòng đất sâu nhiều tầng', {'price': '~13 EUR', 'v': 400, 'd': 90, 't': 'h', 'io': 'i', 'f': 'o'}),
        ('c', 'Lâu đài đá Uçhisar', 'Uçhisar', 'Mỏm đá cao nhất vùng, ngắm hoàng hôn', {'v': 150, 'd': 60, 't': 'np', 'io': 'o', 'ss': 1}),
        ('c', 'Thung lũng Love Valley', 'Love Valley', 'Cột đá hình nấm, đi bộ dã ngoại', {'v': 0, 'd': 120, 't': 'np', 'io': 'o'}),
        ('c', 'Thung lũng Pasabag (Monks Valley)', 'Paşabağ', '"Ống khói tiên" nhiều đầu nổi tiếng', {'v': 150, 'd': 60, 't': 'np', 'io': 'o'}),
        ('c', 'Đồi Hồng (Red Valley)', 'Red Valley (Cappadocia)', 'Đá chuyển màu hồng đỏ lúc hoàng hôn', {'v': 0, 'd': 90, 't': 'np', 'io': 'o', 'ss': 1}),
        ('f', 'Thị trấn Göreme – quán ăn', 'Göreme', 'Món testi kebab nấu trong hũ đất', {'k': 'trua,toi,cafe,sang', 'v': 350, 't': 's', 'io': 'm', 'ev': 'all', 'll': [38.6431, 34.8289]}),
        ('f', 'Làng gốm Avanos', 'Avanos', 'Làng gốm bên sông Kızılırmak, xem làm gốm', {'k': 'trua,check', 'v': 300, 't': 'hs', 'io': 'm'}),
     ]},
    # ---------------- MỸ ----------------
    {'id': 'newyork', 'country': 'us', 'name': 'New York', 'local': 'New York City', 'wiki': 'New York City', 'best': [4, 5, 6, 9, 10, 12], 'days': '4–5 ngày',
     'intro': 'Thành phố không ngủ: tượng Nữ thần Tự do, Times Square, Central Park và các tòa nhà chọc trời.',
     'places': [
        ('s', 'Tượng Nữ thần Tự do', 'Statue of Liberty', 'Đi phà ra đảo Liberty và đảo Ellis', {'price': '~25 USD (phà)', 'v': 650, 'd': 240, 't': 'hpk', 'io': 'o'}),
        ('c', 'Quảng trường Times Square', 'Times Square', 'Ngã tư rực rỡ màn hình quảng cáo', {'v': 0, 'd': 45, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('c', 'Công viên Trung tâm (Central Park)', 'Central Park', 'Công viên lớn giữa Manhattan, thuê xe đạp, thuyền', {'v': 0, 'd': 120, 't': 'nr', 'io': 'o'}),
        ('c', 'Tòa nhà Empire State', 'Empire State Building', 'Đài quan sát tầng 86 biểu tượng New York', {'price': '~45–80 USD', 'v': 1500, 'd': 75, 't': 'pk', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('s', 'Bảo tàng Metropolitan (The Met)', 'Metropolitan Museum of Art', 'Một trong những bảo tàng nghệ thuật lớn nhất thế giới', {'price': '~30 USD', 'v': 790, 'd': 180, 't': 'hk', 'io': 'i', 'cl': [3]}),
        ('c', 'Cầu Brooklyn', 'Brooklyn Bridge', 'Đi bộ qua cầu ngắm đường chân trời Manhattan', {'v': 0, 'd': 60, 't': 'pk', 'io': 'o', 'ss': 1}),
        ('s', 'Đài tưởng niệm 11/9', 'National September 11 Memorial & Museum', 'Hai hồ tưởng niệm và bảo tàng sự kiện 11/9', {'price': '~35 USD (bảo tàng)', 'v': 920, 'd': 120, 't': 'h', 'io': 'm'}),
        ('c', 'Đài quan sát Top of the Rock', 'Rockefeller Center', 'Ngắm Empire State và Central Park từ trên cao', {'price': '~40–50 USD', 'v': 1200, 'd': 75, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('c', 'Công viên High Line', 'High Line', 'Công viên trên đường ray cũ, nối chợ Chelsea', {'v': 0, 'd': 60, 't': 'pr', 'io': 'o'}),
        ('f', 'Chợ Chelsea Market', 'Chelsea Market', 'Khu ẩm thực trong nhà máy bánh cũ', {'k': 'trua,cafe,sang', 'v': 500, 't': 's', 'io': 'i'}),
        ('f', 'Khu phố Tàu và Little Italy', 'Chinatown, Manhattan', 'Dim sum, mì kéo, quán Ý', {'k': 'trua,toi', 'v': 450, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('f', 'Khu Williamsburg (Brooklyn)', 'Williamsburg, Brooklyn', 'Quán cà phê, chợ ẩm thực cuối tuần, view Manhattan', {'k': 'cafe,toi', 'v': 500, 't': 'cs', 'io': 'm', 'ev': 'all'}),
        ('c', 'Nhà ga Grand Central', 'Grand Central Terminal', 'Nhà ga lịch sử với trần sao, khu ăn uống tầng hầm', {'k': 'check,trua', 'v': 0, 'd': 45, 't': 'hp', 'io': 'i'}),
        ('s', 'Xem nhạc kịch Broadway', 'Broadway theatre', 'Xem nhạc kịch ở Theater District', {'price': '~80–200 USD', 'v': 3500, 'd': 150, 't': 'p', 'io': 'i', 'ev': 'all', 'eo': 1}),
     ]},
    {'id': 'washington', 'country': 'us', 'name': 'Washington D.C.', 'local': 'Washington, D.C.', 'wiki': 'Washington, D.C.', 'best': [3, 4, 5, 9, 10], 'days': '2–3 ngày',
     'intro': 'Thủ đô nước Mỹ: Nhà Trắng, Điện Capitol và chuỗi bảo tàng Smithsonian miễn phí.',
     'places': [
        ('c', 'Nhà Trắng', 'White House', 'Chụp ảnh từ công viên Lafayette, ngắm Nhà Trắng', {'v': 0, 'd': 45, 't': 'hpk', 'io': 'o'}),
        ('s', 'Điện Capitol', 'United States Capitol', 'Trụ sở Quốc hội Mỹ, có tour miễn phí', {'v': 0, 'd': 90, 't': 'hk', 'io': 'm', 'cl': [0]}),
        ('c', 'Đài tưởng niệm Lincoln', 'Lincoln Memorial', 'Tượng Lincoln và hồ phản chiếu', {'v': 0, 'd': 45, 't': 'hpk', 'io': 'o', 'ss': 1, 'ev': 'all'}),
        ('c', 'Đài tưởng niệm Washington', 'Washington Monument', 'Tháp đá trắng cao 169 m giữa National Mall', {'v': 0, 'd': 60, 't': 'hp', 'io': 'o'}),
        ('s', 'Bảo tàng Hàng không Vũ trụ', 'National Air and Space Museum', 'Máy bay, tàu vũ trụ thật, miễn phí', {'v': 0, 'd': 150, 't': 'h', 'io': 'i'}),
        ('s', 'Bảo tàng Lịch sử Tự nhiên', 'National Museum of Natural History', 'Kim cương Hope, khủng long, miễn phí', {'v': 0, 'd': 150, 't': 'h', 'io': 'i'}),
        ('c', 'National Mall', 'National Mall', 'Đại lộ xanh nối các đài tưởng niệm', {'v': 0, 'd': 90, 't': 'hr', 'io': 'o'}),
        ('s', 'Thư viện Quốc hội', 'Library of Congress', 'Thư viện lớn nhất thế giới, sảnh chính lộng lẫy', {'v': 0, 'd': 75, 't': 'h', 'io': 'i', 'cl': [0, 1]}),
        ('f', 'Khu Georgetown', 'Georgetown (Washington, D.C.)', 'Phố cổ ven sông, quán ăn, bánh cupcake', {'k': 'trua,cafe,toi', 'v': 500, 't': 'sc', 'io': 'm', 'ev': 'all'}),
        ('f', 'Chợ Union Market', 'Union Market (Washington, D.C.)', 'Khu ẩm thực nhiều quầy nhỏ', {'k': 'trua,toi', 'v': 450, 't': 's', 'io': 'i'}),
        ('f', 'Chợ Eastern Market', 'Eastern Market (Washington, D.C.)', 'Chợ lâu đời gần Capitol, bữa sáng nổi tiếng', {'k': 'sang,trua', 'v': 350, 't': 's', 'io': 'm', 'cl': [1]}),
     ]},
    {'id': 'losangeles', 'country': 'us', 'name': 'Los Angeles', 'local': 'Los Angeles', 'wiki': 'Los Angeles', 'best': [3, 4, 5, 9, 10, 11], 'days': '3–4 ngày',
     'intro': 'Kinh đô điện ảnh Hollywood, bãi biển Santa Monica và công viên giải trí.',
     'places': [
        ('c', 'Đại lộ Danh vọng Hollywood', 'Hollywood Walk of Fame', 'Ngôi sao các nghệ sĩ trên vỉa hè, nhà hát TCL Chinese', {'v': 0, 'd': 75, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('c', 'Đài thiên văn Griffith', 'Griffith Observatory', 'Ngắm bảng chữ Hollywood và thành phố lúc hoàng hôn', {'v': 0, 'd': 90, 't': 'p', 'io': 'm', 'ss': 1, 'cl': [1]}),
        ('s', 'Universal Studios Hollywood', 'Universal Studios Hollywood', 'Công viên phim trường, khu Harry Potter, Nintendo', {'price': '~110–160 USD', 'v': 3700, 'd': 480, 't': 'p', 'io': 'o'}),
        ('c', 'Bến tàu Santa Monica', 'Santa Monica Pier', 'Vòng đu quay bên biển, điểm cuối Route 66', {'v': 0, 'd': 90, 't': 'bpr', 'io': 'o', 'ss': 1}),
        ('c', 'Bãi biển Venice', 'Venice Beach, Los Angeles', 'Phố đi bộ ven biển, nghệ sĩ đường phố', {'v': 0, 'd': 75, 't': 'bp', 'io': 'o'}),
        ('s', 'Bảo tàng Getty', 'Getty Center', 'Bảo tàng nghệ thuật trên đồi, vào cửa miễn phí', {'v': 0, 'd': 150, 't': 'hp', 'io': 'm', 'cl': [1]}),
        ('s', 'Disneyland (Anaheim)', 'Disneyland', 'Công viên Disney đầu tiên trên thế giới', {'price': '~110–200 USD', 'v': 4200, 'd': 480, 't': 'p', 'io': 'o', 'trip': 1}),
        ('c', 'Đồi Beverly Hills – Rodeo Drive', 'Rodeo Drive', 'Phố mua sắm xa xỉ của giới ngôi sao', {'k': 'check,cafe', 'v': 0, 'd': 60, 't': 'p', 'io': 'o'}),
        ('f', 'Chợ Grand Central Market', 'Grand Central Market', 'Khu ẩm thực lâu đời ở trung tâm LA', {'k': 'trua,sang', 'v': 400, 't': 's', 'io': 'i'}),
        ('f', 'Chợ nông sản The Original Farmers Market', 'Original Farmers Market', 'Chợ nông sản và quán ăn cạnh khu The Grove', {'k': 'trua,cafe', 'v': 400, 't': 's', 'io': 'm'}),
        ('f', 'Little Saigon (Westminster)', 'Little Saigon, Orange County', 'Khu người Việt lớn nhất nước Mỹ: phở, bánh mì, cà phê', {'k': 'trua,toi,cafe', 'v': 350, 't': 's', 'io': 'm'}),
     ]},
    {'id': 'sanfrancisco', 'country': 'us', 'name': 'San Francisco', 'local': 'San Francisco', 'wiki': 'San Francisco', 'best': [5, 6, 9, 10], 'days': '3 ngày',
     'intro': 'Cầu Cổng Vàng, xe điện leo dốc và nhà tù Alcatraz – có bay thẳng từ TP.HCM.',
     'places': [
        ('c', 'Cầu Cổng Vàng', 'Golden Gate Bridge', 'Cây cầu đỏ biểu tượng, đi bộ hoặc đạp xe qua cầu', {'v': 0, 'd': 90, 't': 'pk', 'io': 'o', 'ss': 1}),
        ('s', 'Nhà tù Alcatraz', 'Alcatraz Island', 'Nhà tù trên đảo nổi tiếng, đặt vé phà trước', {'price': '~45 USD', 'v': 1200, 'd': 180, 't': 'hk', 'io': 'm'}),
        ('f', 'Bến Fisherman\'s Wharf và Pier 39', "Fisherman's Wharf, San Francisco", 'Súp nghêu trong bánh mì tròn, xem sư tử biển', {'k': 'trua,toi,vat', 'v': 500, 't': 's', 'io': 'o', 'ev': 'all'}),
        ('c', 'Xe điện cáp treo', 'San Francisco cable car system', 'Leo các con dốc trên xe điện cáp từ thế kỷ 19', {'price': '~8 USD/lượt', 'v': 210, 'd': 45, 't': 'hp', 'io': 'o'}),
        ('c', 'Phố Lombard', 'Lombard Street (San Francisco)', 'Con phố ngoằn ngoèo nhiều hoa', {'v': 0, 'd': 30, 't': 'p', 'io': 'o'}),
        ('f', 'Khu phố Tàu San Francisco', 'Chinatown, San Francisco', 'Khu phố Tàu lâu đời nhất Bắc Mỹ', {'k': 'trua,toi,sang', 'v': 350, 't': 'sh', 'io': 'm'}),
        ('f', 'Nhà ga Ferry Building', 'San Francisco Ferry Building', 'Khu ẩm thực, chợ nông sản ven vịnh', {'k': 'sang,trua,cafe', 'v': 450, 't': 's', 'io': 'm'}),
        ('c', 'Công viên Golden Gate', 'Golden Gate Park', 'Công viên lớn với vườn Nhật, bảo tàng', {'v': 0, 'd': 120, 't': 'nr', 'io': 'o'}),
        ('c', 'Dãy nhà Painted Ladies', 'Painted ladies', 'Dãy nhà gỗ Victoria trước công viên Alamo Square', {'v': 0, 'd': 30, 't': 'p', 'io': 'o'}),
        ('c', 'Đồi Twin Peaks', 'Twin Peaks (San Francisco)', 'Điểm ngắm toàn cảnh thành phố', {'v': 0, 'd': 45, 't': 'p', 'io': 'o', 'ss': 1, 'ev': 'all'}),
        ('s', 'Thung lũng Napa', 'Napa Valley AVA', 'Vùng rượu vang nổi tiếng, cách ~1,5 giờ', {'v': 1500, 'd': 360, 't': 'nr', 'io': 'o', 'trip': 1}),
     ]},
    {'id': 'lasvegas', 'country': 'us', 'name': 'Las Vegas – Grand Canyon', 'local': 'Las Vegas', 'wiki': 'Las Vegas', 'best': [3, 4, 5, 10, 11], 'days': '2–3 ngày',
     'intro': 'Thành phố giải trí giữa sa mạc, show diễn đẳng cấp và cửa ngõ tới hẻm núi Grand Canyon.',
     'places': [
        ('c', 'Đại lộ Las Vegas Strip', 'Las Vegas Strip', 'Dãy khách sạn – sòng bài rực rỡ về đêm', {'v': 0, 'd': 120, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('c', 'Nhạc nước Bellagio', 'Fountains of Bellagio', 'Đài phun nước nhảy múa theo nhạc, miễn phí', {'v': 0, 'd': 30, 't': 'pk', 'io': 'o', 'ev': 'all'}),
        ('c', 'Phố Fremont', 'Fremont Street Experience', 'Phố cổ Las Vegas với mái màn hình LED', {'v': 0, 'd': 60, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('c', 'Biển "Welcome to Las Vegas"', 'Welcome to Fabulous Las Vegas sign', 'Tấm biển chụp ảnh nổi tiếng', {'v': 0, 'd': 20, 't': 'p', 'io': 'o'}),
        ('c', 'The Venetian', 'The Venetian Las Vegas', 'Khách sạn mô phỏng Venice, đi thuyền gondola trong nhà', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'p', 'io': 'i', 'ev': 'all'}),
        ('c', 'The Sphere', 'Sphere (venue)', 'Quả cầu màn hình LED khổng lồ, show trong nhà', {'price': '~100–250 USD', 'v': 3500, 'd': 120, 't': 'p', 'io': 'i', 'ev': 'all', 'eo': 1}),
        ('f', 'Buffet khách sạn trên Strip', 'Bacchanal Buffet', 'Buffet nổi tiếng của Las Vegas', {'k': 'toi,trua', 'v': 2000, 't': 's', 'io': 'i'}),
        ('s', 'Đập Hoover', 'Hoover Dam', 'Đập thủy điện khổng lồ trên sông Colorado', {'v': 300, 'd': 180, 't': 'hn', 'io': 'o'}),
        ('s', 'Grand Canyon – Bờ Nam', 'South Rim', 'Hẻm núi kỳ vĩ, điểm ngắm Mather Point (~4,5 giờ xe)', {'price': '~35 USD/xe', 'v': 500, 'd': 360, 't': 'npk', 'io': 'o', 'trip': 1}),
        ('s', 'Grand Canyon West – Skywalk', 'Grand Canyon Skywalk', 'Cầu kính hình móng ngựa treo trên hẻm núi (~2,5 giờ xe)', {'price': '~70–90 USD', 'v': 2100, 'd': 300, 't': 'np', 'io': 'o', 'trip': 1}),
        ('s', 'Công viên Red Rock Canyon', 'Red Rock Canyon National Conservation Area', 'Đá đỏ sa mạc gần Las Vegas, lái xe ngắm cảnh', {'v': 500, 'd': 180, 't': 'n', 'io': 'o'}),
     ]},
    # ---------------- CANADA ----------------
    {'id': 'toronto', 'country': 'ca', 'name': 'Toronto – Niagara', 'local': 'Toronto', 'wiki': 'Toronto', 'best': [5, 6, 7, 8, 9, 10], 'days': '3–4 ngày',
     'intro': 'Thành phố lớn nhất Canada, tháp CN và thác Niagara hùng vĩ cách 1,5 giờ xe.',
     'places': [
        ('c', 'Tháp CN', 'CN Tower', 'Tháp cao 553 m, sàn kính và EdgeWalk', {'price': '~45 CAD', 'v': 830, 'd': 90, 't': 'pk', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('f', 'Chợ St. Lawrence', 'St. Lawrence Market', 'Chợ lâu đời, bánh mì kẹp thịt lợn peameal', {'k': 'sang,trua', 'v': 300, 't': 's', 'io': 'i', 'cl': [0, 1]}),
        ('s', 'Thủy cung Ripley\'s', "Ripley's Aquarium of Canada", 'Đường hầm cá mập dưới chân tháp CN', {'price': '~45 CAD', 'v': 830, 'd': 120, 't': 'n', 'io': 'i'}),
        ('s', 'Bảo tàng Hoàng gia Ontario', 'Royal Ontario Museum', 'Bảo tàng lịch sử tự nhiên và văn hóa lớn nhất Canada', {'price': '~26 CAD', 'v': 480, 'd': 150, 't': 'h', 'io': 'i'}),
        ('c', 'Khu Distillery', 'Distillery District', 'Khu nhà máy rượu cổ thành phố đi bộ, quán cà phê', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'pc', 'io': 'o'}),
        ('f', 'Chợ Kensington', 'Kensington Market', 'Khu chợ đa văn hóa, quán ăn đường phố', {'k': 'trua,toi,vat', 'v': 300, 't': 's', 'io': 'o'}),
        ('c', 'Đảo Toronto', 'Toronto Islands', 'Đi phà ra đảo ngắm đường chân trời thành phố', {'price': '~9 CAD (phà)', 'v': 170, 'd': 180, 't': 'nrp', 'io': 'o', 'ss': 1}),
        ('s', 'Lâu đài Casa Loma', 'Casa Loma', 'Lâu đài kiểu Gothic giữa thành phố', {'price': '~40 CAD', 'v': 740, 'd': 90, 't': 'h', 'io': 'm'}),
        ('f', 'Phố Tàu Toronto', 'Chinatown, Toronto', 'Khu phố Tàu trên đường Spadina, có quán phở Việt', {'k': 'toi,trua', 'v': 300, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('s', 'Thác Niagara', 'Niagara Falls', 'Thác nước hùng vĩ, đi thuyền sát chân thác (~1,5 giờ xe)', {'price': '~35 CAD (thuyền)', 'v': 650, 'd': 360, 't': 'npk', 'io': 'o', 'trip': 1}),
     ]},
    {'id': 'vancouver', 'country': 'ca', 'name': 'Vancouver', 'local': 'Vancouver', 'wiki': 'Vancouver', 'best': [5, 6, 7, 8, 9], 'days': '3 ngày',
     'intro': 'Thành phố giữa núi và biển: công viên Stanley, cầu treo Capilano và Whistler.',
     'places': [
        ('c', 'Công viên Stanley', 'Stanley Park', 'Công viên ven biển, đạp xe quanh đê Seawall', {'v': 0, 'd': 150, 't': 'nrp', 'io': 'o', 'ss': 1}),
        ('f', 'Chợ đảo Granville', 'Granville Island', 'Chợ công cộng, quán ăn, xưởng nghệ thuật', {'k': 'trua,cafe,sang', 'v': 350, 't': 'sc', 'io': 'm'}),
        ('s', 'Cầu treo Capilano', 'Capilano Suspension Bridge', 'Cầu treo cao 70 m qua rừng mưa', {'price': '~70 CAD', 'v': 1300, 'd': 120, 't': 'np', 'io': 'o'}),
        ('c', 'Khu phố cổ Gastown', 'Gastown', 'Đồng hồ hơi nước, quán bar, cửa hàng', {'k': 'check,toi', 'v': 0, 'd': 60, 't': 'hp', 'io': 'o', 'ev': 'all'}),
        ('s', 'Núi Grouse', 'Grouse Mountain', 'Cáp treo lên núi ngắm thành phố, gấu xám', {'price': '~80 CAD', 'v': 1480, 'd': 180, 't': 'nm', 'io': 'o', 'ss': 1}),
        ('c', 'Canada Place', 'Canada Place', 'Bến tàu mái buồm, bay mô phỏng FlyOver Canada', {'v': 0, 'd': 45, 't': 'p', 'io': 'o'}),
        ('f', 'Phố Tàu Vancouver', 'Chinatown, Vancouver', 'Phố Tàu lớn, vườn cổ điển Tôn Trung Sơn', {'k': 'trua,toi', 'v': 300, 't': 'sh', 'io': 'm'}),
        ('c', 'Bãi biển English Bay', 'English Bay', 'Bãi biển ngắm hoàng hôn trong thành phố', {'v': 0, 'd': 60, 't': 'br', 'io': 'o', 'ss': 1}),
        ('f', 'Chợ đêm Richmond', 'Richmond Night Market', 'Chợ đêm châu Á lớn (mùa hè, cuối tuần)', {'k': 'toi,vat', 'v': 350, 't': 's', 'io': 'o', 'ev': 'weekend', 'eo': 1, 'cl': [1, 2, 3, 4]}),
        ('s', 'Whistler', 'Whistler, British Columbia', 'Khu nghỉ dưỡng núi, cáp treo Peak 2 Peak (~2 giờ xe)', {'v': 1800, 'd': 360, 't': 'nm', 'io': 'o', 'trip': 1}),
     ]},
]

# Thông tin lập lịch trình cấp thành phố (giống intl_plan.CITY)
CITY_W = {
    'paris':        {'hotel': [2200, 4500, 11000], 'fly': {'HAN': (24000, 13.0), 'SGN': (24000, 13.5)}, 'tr': 'metro', 'air': 'Paris (CDG)'},
    'rome':         {'hotel': [2000, 4000, 9000], 'fly': {'HAN': (25000, 16.0), 'SGN': (25000, 16.0)}, 'tr': 'metro', 'air': 'Rome (FCO)'},
    'venice':       {'hotel': [2500, 5000, 12000], 'fly': {'HAN': (26000, 17.0), 'SGN': (26000, 17.0)}, 'tr': 'metro', 'air': 'Venice (VCE)'},
    'florence':     {'hotel': [2000, 4000, 9000], 'fly': {'HAN': (26000, 17.0), 'SGN': (26000, 17.0)}, 'tr': 'metro', 'air': 'Florence/Pisa'},
    'swiss':        {'hotel': [3000, 6000, 13000], 'fly': {'HAN': (26000, 15.0), 'SGN': (26000, 15.0)}, 'tr': 'metro', 'air': 'Zurich (ZRH)',
                     'areas': ['Zurich', 'Lucerne', 'Interlaken']},
    'london':       {'hotel': [2800, 5500, 13000], 'fly': {'HAN': (25000, 13.5), 'SGN': (25000, 13.5)}, 'tr': 'metro', 'air': 'London (LHR)'},
    'munich':       {'hotel': [2200, 4300, 9500], 'fly': {'HAN': (24000, 12.5), 'SGN': (24000, 12.5)}, 'tr': 'metro', 'air': 'Munich (MUC)'},
    'amsterdam':    {'hotel': [2600, 5000, 11000], 'fly': {'HAN': (24000, 13.0), 'SGN': (25000, 15.0)}, 'tr': 'metro', 'air': 'Amsterdam (AMS)'},
    'barcelona':    {'hotel': [2000, 4200, 9500], 'fly': {'HAN': (25000, 16.0), 'SGN': (25000, 16.0)}, 'tr': 'metro', 'air': 'Barcelona (BCN)'},
    'prague':       {'hotel': [1300, 2600, 6500], 'fly': {'HAN': (23000, 14.0), 'SGN': (23000, 14.5)}, 'tr': 'metro', 'air': 'Praha (PRG)'},
    'vienna':       {'hotel': [1800, 3600, 8500], 'fly': {'HAN': (23000, 14.0), 'SGN': (23000, 14.5)}, 'tr': 'metro', 'air': 'Vienna (VIE)'},
    'istanbul':     {'hotel': [1000, 2200, 6000], 'fly': {'HAN': (17000, 11.0), 'SGN': (17000, 11.5)}, 'tr': 'metro', 'air': 'Istanbul (IST)'},
    'cappadocia':   {'hotel': [1200, 2800, 8000], 'fly': {'HAN': (19000, 13.5), 'SGN': (19000, 14.0)}, 'tr': 'car', 'air': 'Kayseri/Nevşehir'},
    'newyork':      {'hotel': [4000, 7000, 15000], 'fly': {'HAN': (32000, 22.0), 'SGN': (32000, 21.0)}, 'tr': 'metro', 'air': 'New York (JFK)'},
    'washington':   {'hotel': [3000, 5500, 11000], 'fly': {'HAN': (32000, 22.0), 'SGN': (32000, 21.0)}, 'tr': 'metro', 'air': 'Washington (IAD)'},
    'losangeles':   {'hotel': [2800, 5000, 11000], 'fly': {'HAN': (28000, 17.0), 'SGN': (27000, 16.0)}, 'tr': 'car', 'air': 'Los Angeles (LAX)'},
    'sanfrancisco': {'hotel': [3200, 5800, 12000], 'fly': {'HAN': (28000, 17.0), 'SGN': (26000, 13.5)}, 'tr': 'metro', 'air': 'San Francisco (SFO)'},
    'lasvegas':     {'hotel': [1800, 3500, 8000], 'fly': {'HAN': (30000, 19.0), 'SGN': (29000, 18.0)}, 'tr': 'car', 'air': 'Las Vegas (LAS)'},
    'toronto':      {'hotel': [2600, 4500, 9500], 'fly': {'HAN': (30000, 20.0), 'SGN': (30000, 20.0)}, 'tr': 'metro', 'air': 'Toronto (YYZ)'},
    'vancouver':    {'hotel': [2800, 5000, 10500], 'fly': {'HAN': (25000, 15.0), 'SGN': (25000, 15.0)}, 'tr': 'metro', 'air': 'Vancouver (YVR)'},
}

# Đi lại tại chỗ (nghìn đồng), bữa ăn trung bình (meal) và bữa sáng (bf) mỗi người
LOCAL_W = {
    'fr': {'metro': (65, 1), 'car': (120, 45), 'far': ('train', 60, 3.5), 'meal': 500, 'bf': 300},
    'it': {'metro': (45, 1), 'car': (150, 40), 'far': ('train', 60, 3), 'meal': 450, 'bf': 200},
    'ch': {'metro': (100, 3), 'car': (250, 90), 'far': ('train', 100, 8), 'meal': 750, 'bf': 400},
    'gb': {'metro': (100, 3), 'car': (150, 70), 'far': ('train', 150, 5), 'meal': 550, 'bf': 300},
    'de': {'metro': (110, 1.5), 'car': (130, 60), 'far': ('train', 100, 4), 'meal': 450, 'bf': 250},
    'nl': {'metro': (100, 2), 'car': (150, 75), 'far': ('train', 80, 4), 'meal': 500, 'bf': 300},
    'es': {'metro': (75, 1), 'car': (90, 35), 'far': ('train', 60, 3), 'meal': 400, 'bf': 180},
    'cz': {'metro': (40, 1), 'car': (80, 25), 'far': ('train', 40, 2), 'meal': 300, 'bf': 180},
    'at': {'metro': (75, 1), 'car': (120, 50), 'far': ('train', 60, 3), 'meal': 450, 'bf': 250},
    'tr': {'metro': (25, 1), 'car': (40, 15), 'far': ('hire', 600, 15), 'meal': 250, 'bf': 150},
    'us': {'metro': (75, 2), 'car': (130, 55), 'far': ('train', 300, 4), 'meal': 550, 'bf': 300},
    'ca': {'metro': (65, 1.5), 'car': (100, 40), 'far': ('train', 150, 3), 'meal': 500, 'bf': 280},
}
