"""Dữ liệu điểm đến quốc tế cho mục "Quốc tế" của Đi Đâu?.

Mỗi địa điểm ghi tên bài Wikipedia tiếng Anh (wiki) để công cụ tools/fetch_intl.py lấy TỌA ĐỘ + ẢNH thật
(không tự đoán tọa độ). Tạo file public/data/intl.json bằng: python3 tools/build_intl.py

Địa điểm: (loại, tên hiển thị, bài Wikipedia, vì sao nên đến, thêm)
  loại: f = ăn uống, c = check-in, s = tham quan
  thêm: {'price': giá tham khảo, 'tip': mẹo}  (có thể bỏ trống)
Visa/giờ bay/tỷ giá: tham khảo tại thời điểm cập nhật (UPDATED) – luôn ghi chú người dùng kiểm tra lại.
"""

UPDATED = '10/2026'

COUNTRIES = [
    {'id': 'th', 'name': 'Thái Lan', 'flag': '🇹🇭', 'currency': 'Baht (THB)', 'rate': '1 THB ≈ 750–800đ',
     'flight': 'Bay thẳng khoảng 1,5–2 giờ từ Hà Nội, TP.HCM',
     'visa': 'Miễn visa tối đa 60 ngày khi nhập cảnh đường hàng không (đường bộ 15 ngày). Khai thẻ nhập cảnh điện tử TDAC trước khi đến.',
     'visaFree': True,
     'tips': ['Vào chùa, cung điện cần mặc kín vai và đầu gối.', 'Đi lại trong Bangkok nhanh nhất bằng tàu BTS/MRT, tránh giờ tan tầm.', 'Mua SIM du lịch ngay tại sân bay.']},
    {'id': 'cn', 'name': 'Trung Quốc', 'flag': '🇨🇳', 'currency': 'Nhân dân tệ (CNY)', 'rate': '1 CNY ≈ 3.500–3.700đ',
     'flight': 'Bay thẳng khoảng 3,5–5 giờ tới Bắc Kinh, Thượng Hải; nhiều tour đi đường bộ qua Lào Cai, Lạng Sơn',
     'visa': 'Cần visa du lịch. Chính sách miễn visa quá cảnh 240 giờ (từ 20/8/2026) chỉ áp dụng khi có vé đi tiếp sang nước thứ ba, không áp dụng vé khứ hồi Việt Nam – Trung Quốc.',
     'visaFree': False,
     'tips': ['Cài sẵn Alipay hoặc WeChat Pay và liên kết thẻ quốc tế; nhiều nơi gần như không nhận tiền mặt.', 'Google, Facebook, Zalo bị chặn – mua eSIM/SIM quốc tế có chuyển vùng nếu cần.', 'Mang theo hộ chiếu khi mua vé tham quan, vé tàu.']},
    {'id': 'kr', 'name': 'Hàn Quốc', 'flag': '🇰🇷', 'currency': 'Won (KRW)', 'rate': '1.000 KRW ≈ 17.000–19.000đ',
     'flight': 'Bay thẳng khoảng 4,5–5 giờ tới Seoul (Incheon), Busan',
     'visa': 'Cần visa. Riêng đảo Jeju được miễn visa tối đa 30 ngày nếu bay thẳng vào Jeju (không quá cảnh sân bay khác của Hàn Quốc) và chỉ ở trong Jeju.',
     'visaFree': False,
     'tips': ['Thẻ giao thông T-money dùng cho tàu điện, xe buýt, cửa hàng tiện lợi.', 'Dùng Naver Map hoặc KakaoMap thay Google Maps để chỉ đường chính xác.', 'Mùa thu (lá đỏ) và mùa xuân (hoa anh đào) đông khách – đặt phòng sớm.']},
    {'id': 'jp', 'name': 'Nhật Bản', 'flag': '🇯🇵', 'currency': 'Yên (JPY)', 'rate': '1.000 JPY ≈ 165.000–180.000đ',
     'flight': 'Bay thẳng khoảng 5–6 giờ tới Tokyo, Osaka',
     'visa': 'Cần visa (nộp qua đại lý được ủy thác). Từ 11/2023 Nhật cấp visa điện tử cho khách đi tour trọn gói qua công ty du lịch được chỉ định (lưu trú tối đa 15 ngày).',
     'visaFree': False,
     'tips': ['Mua thẻ IC (Suica/ICOCA) để đi tàu, xe buýt và mua hàng.', 'Giữ trật tự, không ăn khi đi bộ, mang rác về khách sạn vì ít thùng rác công cộng.', 'Đi nhiều thành phố thì cân nhắc vé tàu Shinkansen theo chặng hoặc JR Pass.']},
    {'id': 'sg', 'name': 'Singapore', 'flag': '🇸🇬', 'currency': 'Đô la Singapore (SGD)', 'rate': '1 SGD ≈ 19.000–20.500đ',
     'flight': 'Bay thẳng khoảng 2 giờ từ TP.HCM, 3,5 giờ từ Hà Nội',
     'visa': 'Miễn visa tối đa 30 ngày. Khai SG Arrival Card trực tuyến trong 3 ngày trước khi đến.',
     'visaFree': True,
     'tips': ['Đi tàu MRT bằng thẻ ngân hàng không tiếp xúc hoặc thẻ EZ-Link.', 'Phạt nặng nếu xả rác, ăn uống trên tàu MRT, mang kẹo cao su.', 'Ăn ở các khu hawker (chợ ẩm thực) rẻ và ngon hơn nhà hàng.']},
    {'id': 'my', 'name': 'Malaysia', 'flag': '🇲🇾', 'currency': 'Ringgit (MYR)', 'rate': '1 MYR ≈ 5.500–6.200đ',
     'flight': 'Bay thẳng khoảng 2 giờ từ TP.HCM, 3,5 giờ từ Hà Nội tới Kuala Lumpur',
     'visa': 'Miễn visa tối đa 30 ngày. Khai thẻ nhập cảnh điện tử MDAC trong 3 ngày trước khi đến.',
     'visaFree': True,
     'tips': ['Dùng ứng dụng Grab để đi lại, giá rõ ràng.', 'Ổ cắm điện chuẩn Anh (3 chấu vuông) – mang theo đầu chuyển.', 'Vào đền thờ Hồi giáo cần mặc kín, nữ choàng khăn (thường được cho mượn).']},
    {'id': 'tw', 'name': 'Đài Loan', 'flag': '🇹🇼', 'currency': 'Đài tệ (TWD)', 'rate': '1 TWD ≈ 780–850đ',
     'flight': 'Bay thẳng khoảng 3–3,5 giờ tới Đài Bắc (Đào Viên), Cao Hùng',
     'visa': 'Cần visa (có visa điện tử). Miễn visa có điều kiện 14 ngày qua Giấy phép nhập cảnh trực tuyến nếu có visa/thẻ cư trú còn hạn hoặc hết hạn chưa quá 10 năm của Mỹ, Canada, Anh, Nhật, Hàn, Úc, New Zealand hoặc khối Schengen.',
     'visaFree': False,
     'tips': ['Thẻ EasyCard dùng cho tàu điện, xe buýt, cửa hàng tiện lợi.', 'Chợ đêm là nơi ăn ngon và rẻ nhất – đi bụng đói.', 'Đi Cửu Phần, Dã Liễu nên tránh cuối tuần.']},
    {'id': 'id', 'name': 'Indonesia (Bali)', 'flag': '🇮🇩', 'currency': 'Rupiah (IDR)', 'rate': '100.000 IDR ≈ 150.000–165.000đ',
     'flight': 'Khoảng 4–5 giờ bay tới Bali (Denpasar)',
     'visa': 'Miễn visa tối đa 30 ngày. Khách quốc tế đến Bali đóng phí du lịch 150.000 IDR (trả trực tuyến qua Love Bali hoặc tại sân bay).',
     'visaFree': True,
     'tips': ['Thuê xe máy/ô tô có tài xế theo ngày là cách đi lại tiện nhất.', 'Vào đền cần quấn sarong (thường cho mượn ở cổng).', 'Mùa khô (tháng 4–10) đẹp nhất, ít mưa.']},
]

# best: tháng đẹp; days: số ngày gợi ý
CITIES = [
    # ---------------- THÁI LAN ----------------
    {'id': 'bangkok', 'country': 'th', 'name': 'Bangkok', 'local': 'กรุงเทพฯ', 'wiki': 'Bangkok', 'best': [11, 12, 1, 2], 'days': '3–4 ngày',
     'intro': 'Thủ đô sôi động: chùa vàng, cung điện, trung tâm mua sắm và ẩm thực đường phố nổi tiếng thế giới.',
     'places': [
        ('s', 'Cung điện Hoàng gia & chùa Phật Ngọc', 'Grand Palace', 'Quần thể cung điện lộng lẫy nhất Thái Lan, có tượng Phật Ngọc', {'price': '~500 THB', 'tip': 'Mặc kín vai, gối; đến lúc mở cửa để tránh nóng và đông.'}),
        ('s', 'Chùa Phật Nằm (Wat Pho)', 'Wat Pho', 'Tượng Phật nằm dát vàng dài 46 m, cái nôi của massage Thái', {'price': '~300 THB'}),
        ('c', 'Chùa Bình Minh (Wat Arun)', 'Wat Arun', 'Tháp chùa khảm sứ bên sông Chao Phraya, đẹp nhất lúc hoàng hôn', {'price': '~200 THB', 'tip': 'Đi phà qua sông từ bến Tha Tien, gần Wat Pho.'}),
        ('f', 'Phố người Hoa Yaowarat', 'Yaowarat Road', 'Thiên đường ăn đêm: hải sản, tổ yến, bánh ngọt', {'tip': 'Đẹp và đông nhất sau 18:00; nhiều quán nghỉ thứ Hai.'}),
        ('f', 'Chợ cuối tuần Chatuchak', 'Chatuchak Weekend Market', 'Chợ trời khổng lồ hơn 10.000 gian hàng, ăn uống và mua sắm', {'tip': 'Chỉ họp thứ Bảy, Chủ nhật; đi buổi sáng cho mát.'}),
        ('c', 'ICONSIAM', 'Icon Siam', 'Trung tâm thương mại bên sông, có chợ nổi trong nhà', {}),
        ('c', 'Asiatique The Riverfront', 'Asiatique The Riverfront', 'Chợ đêm và vòng quay bên sông Chao Phraya', {}),
        ('c', 'Đài quan sát Mahanakhon SkyWalk', 'King Power MahaNakhon', 'Sàn kính trên tầng 78, ngắm toàn cảnh Bangkok', {}),
        ('s', 'Nhà Jim Thompson', 'Jim Thompson House', 'Bảo tàng nhà gỗ Thái truyền thống và lụa Thái', {}),
        ('s', 'Safari World', 'Safari World', 'Công viên thú hoang dã và biển, hợp đi cùng trẻ em', {}),
        ('f', 'Chợ nổi Damnoen Saduak', 'Damnoen Saduak Floating Market', 'Chợ trên thuyền nổi tiếng, cách Bangkok khoảng 100 km', {'tip': 'Đi sớm (7–9 giờ) để thấy chợ đông thuyền.'}),
     ]},
    {'id': 'pattaya', 'country': 'th', 'name': 'Pattaya', 'local': 'พัทยา', 'wiki': 'Pattaya', 'best': [11, 12, 1, 2, 3], 'days': '2–3 ngày',
     'intro': 'Thành phố biển cách Bangkok khoảng 2 giờ đi xe, nhiều show diễn và đảo gần bờ.',
     'places': [
        ('s', 'Đền Chân Lý', 'Sanctuary of Truth', 'Công trình gỗ chạm khắc khổng lồ bên bờ biển', {}),
        ('c', 'Vườn nhiệt đới Nong Nooch', 'Nong Nooch Tropical Botanical Garden', 'Vườn hoa, khủng long và show voi, show văn hóa', {}),
        ('c', 'Đảo Coral (Koh Larn)', 'Ko Lan', 'Đảo biển nước trong, đi phà từ bến Bali Hai', {'tip': 'Phà công cộng rẻ hơn tàu cao tốc; về trước 18:00.'}),
        ('f', 'Phố đi bộ Walking Street', 'Walking Street, Pattaya', 'Phố đêm sôi động, hải sản và quán bar', {}),
        ('c', 'Núi Phật vàng Khao Chi Chan', 'Khao Chi Chan', 'Tượng Phật khắc vàng trên vách núi', {}),
        ('s', 'Tiffany\'s Show', "Tiffany's Show", 'Show ca múa nổi tiếng của Pattaya', {'ll': [12.9477, 100.8880]}),
        ('f', 'Chợ nổi Pattaya', 'Pattaya Floating Market', 'Chợ nổi 4 miền Thái Lan, ăn vặt trên thuyền', {'ll': [12.8676, 100.9046]}),
        ('c', 'Bãi biển Jomtien', 'Jomtien Beach', 'Bãi biển dài, yên tĩnh hơn trung tâm', {}),
     ]},
    {'id': 'phuket', 'country': 'th', 'name': 'Phuket', 'local': 'ภูเก็ต', 'wiki': 'Phuket province', 'best': [11, 12, 1, 2, 3, 4], 'days': '3–4 ngày',
     'intro': 'Đảo lớn nhất Thái Lan: biển xanh, vịnh đá vôi và các tour đảo Phi Phi.',
     'places': [
        ('c', 'Tượng Phật lớn Phuket', 'Phuket Big Buddha', 'Tượng Phật đá cẩm thạch trắng trên đỉnh đồi, view toàn đảo', {'tip': 'Mặc kín vai, gối; có cho mượn khăn.'}),
        ('s', 'Quần đảo Phi Phi', 'Phi Phi Islands', 'Tour đảo nổi tiếng với vịnh Maya và nước biển xanh ngọc', {'tip': 'Đi tour trong ngày từ Phuket; biển êm nhất tháng 11–4.'}),
        ('s', 'Vịnh Phang Nga', 'Phang Nga Bay', 'Vịnh đá vôi giống Hạ Long, có đảo James Bond', {}),
        ('c', 'Bãi biển Patong', 'Patong', 'Bãi biển sôi động nhất Phuket', {}),
        ('f', 'Phố Bangla', 'Bangla Road', 'Phố đêm ăn uống, giải trí ở Patong', {'ll': [7.8934, 98.2969]}),
        ('c', 'Mũi Promthep', 'Laem Phromthep', 'Điểm ngắm hoàng hôn đẹp nhất đảo', {'ll': [7.7620, 98.3056]}),
        ('s', 'Chùa Chalong', 'Wat Chalong', 'Ngôi chùa lớn và linh thiêng nhất Phuket', {}),
        ('c', 'Phố cổ Phuket', 'Phuket (city)', 'Phố nhà Sino-Portuguese nhiều màu, quán cà phê đẹp', {'ll': [7.8857, 98.3883], 'tip': 'Chủ nhật có chợ đêm trên phố Thalang.'}),
        ('c', 'Bãi biển Kata', 'Kata Beach', 'Bãi biển đẹp, sóng vừa, hợp gia đình', {'ll': [7.8201, 98.2981]}),
     ]},
    {'id': 'chiangmai', 'country': 'th', 'name': 'Chiang Mai', 'local': 'เชียงใหม่', 'wiki': 'Chiang Mai', 'best': [11, 12, 1, 2], 'days': '3–4 ngày',
     'intro': 'Cố đô miền Bắc Thái Lan: khí hậu mát, hơn 300 ngôi chùa, núi rừng và chợ đêm.',
     'places': [
        ('s', 'Chùa Doi Suthep', 'Wat Phra That Doi Suthep', 'Chùa vàng trên núi, nhìn xuống toàn thành phố', {}),
        ('s', 'Chùa Chedi Luang', 'Wat Chedi Luang', 'Tháp cổ đổ nát hùng vĩ giữa phố cổ', {}),
        ('s', 'Chùa Phra Singh', 'Wat Phra Singh', 'Ngôi chùa đẹp nhất phố cổ, kiến trúc Lanna', {}),
        ('c', 'Cổng Tha Phae', 'Tha Phae Gate', 'Cổng thành cổ, điểm hẹn của phố đi bộ Chủ nhật', {}),
        ('f', 'Chợ đêm Chiang Mai', 'Chiang Mai Night Bazaar', 'Chợ đêm mua đồ thủ công, ăn khao soi', {}),
        ('c', 'Vườn quốc gia Doi Inthanon', 'Doi Inthanon National Park', 'Nóc nhà Thái Lan, thác nước và cặp tháp hoàng gia', {}),
        ('c', 'Chùa Trắng (Chiang Rai)', 'Wat Rong Khun', 'Ngôi chùa trắng độc đáo, đi trong ngày từ Chiang Mai', {}),
        ('s', 'Công viên voi Elephant Nature Park', 'Elephant Nature Park', 'Khu bảo tồn voi, tắm và cho voi ăn', {'tip': 'Đặt chỗ trước; chọn nơi không cưỡi voi.'}),
        ('f', 'Phố Nimman', 'Nimmanhaemin Road', 'Khu cà phê, quán ăn trẻ trung', {'ll': [18.7969, 98.9676]}),
     ]},
    # ---------------- TRUNG QUỐC ----------------
    {'id': 'beijing', 'country': 'cn', 'name': 'Bắc Kinh', 'local': '北京', 'wiki': 'Beijing', 'best': [4, 5, 9, 10], 'days': '4–5 ngày',
     'intro': 'Thủ đô ngàn năm với Cố Cung, Vạn Lý Trường Thành và ẩm thực vịt quay.',
     'places': [
        ('s', 'Cố Cung (Tử Cấm Thành)', 'Forbidden City', 'Cung điện hoàng gia lớn nhất thế giới', {'tip': 'Phải đặt vé trực tuyến trước bằng hộ chiếu; đóng cửa thứ Hai.'}),
        ('c', 'Quảng trường Thiên An Môn', 'Tiananmen Square', 'Quảng trường trung tâm, cổng vào Cố Cung', {'tip': 'Mang hộ chiếu để qua kiểm tra an ninh.'}),
        ('s', 'Vạn Lý Trường Thành – Mộ Điền Dụ', 'Mutianyu', 'Đoạn Trường Thành đẹp, ít đông hơn Bát Đạt Lĩnh', {'tip': 'Có cáp treo và máng trượt xuống núi.'}),
        ('s', 'Vạn Lý Trường Thành – Bát Đạt Lĩnh', 'Badaling', 'Đoạn Trường Thành nổi tiếng nhất, gần thành phố', {}),
        ('s', 'Thiên Đàn', 'Temple of Heaven', 'Nơi vua tế trời, kiến trúc tròn độc đáo', {}),
        ('s', 'Di Hòa Viên', 'Summer Palace', 'Cung điện mùa hè bên hồ Côn Minh', {}),
        ('f', 'Phố Vương Phủ Tỉnh', 'Wangfujing', 'Phố mua sắm và ăn vặt nổi tiếng', {}),
        ('f', 'Ngõ Nam La Cổ', 'Nanluoguxiang', 'Ngõ hutong cổ, quán ăn và cà phê', {}),
        ('c', 'Sân vận động Tổ Chim', 'Beijing National Stadium', 'Biểu tượng Olympic 2008, đẹp khi lên đèn', {}),
        ('s', 'Ung Hòa Cung', 'Yonghe Temple', 'Chùa Lạt Ma lớn nhất Bắc Kinh', {}),
        ('c', 'Hồ Thập Sát Hải', 'Shichahai', 'Hồ, hutong và phố bar về đêm', {}),
     ]},
    {'id': 'shanghai', 'country': 'cn', 'name': 'Thượng Hải', 'local': '上海', 'wiki': 'Shanghai', 'best': [4, 5, 10, 11], 'days': '3–4 ngày',
     'intro': 'Đô thị hiện đại bậc nhất Trung Quốc, kết hợp phố Tây cổ và nhà chọc trời.',
     'places': [
        ('c', 'Bến Thượng Hải (The Bund)', 'The Bund', 'Đại lộ kiến trúc châu Âu, ngắm toàn cảnh Phố Đông về đêm', {}),
        ('c', 'Tháp Minh Châu Phương Đông', 'Oriental Pearl Tower', 'Biểu tượng của Thượng Hải, có sàn kính', {}),
        ('c', 'Tháp Thượng Hải', 'Shanghai Tower', 'Tòa nhà cao nhất Trung Quốc, đài quan sát tầng 118', {}),
        ('s', 'Dự Viên', 'Yu Garden', 'Vườn cổ Giang Nam giữa lòng phố cổ', {}),
        ('f', 'Phố đi bộ Nam Kinh', 'Nanjing Road', 'Phố mua sắm sầm uất nhất', {}),
        ('f', 'Điền Tử Phường', 'Tianzifang', 'Mê cung ngõ nhỏ, quán ăn, cửa hàng thủ công', {}),
        ('c', 'Tân Thiên Địa', 'Xintiandi', 'Khu nhà Thạch Khố cải tạo thành phố ăn uống', {}),
        ('s', 'Cổ trấn Chu Gia Giác', 'Zhujiajiao', 'Thị trấn sông nước cổ, đi thuyền', {}),
        ('s', 'Shanghai Disneyland', 'Shanghai Disneyland Park', 'Công viên Disney, hợp đi cùng trẻ em', {}),
     ]},
    {'id': 'zhangjiajie', 'country': 'cn', 'name': 'Trương Gia Giới – Phượng Hoàng', 'local': '张家界', 'wiki': 'Zhangjiajie', 'best': [4, 5, 9, 10], 'days': '4–5 ngày',
     'intro': 'Rừng cột đá hùng vĩ (bối cảnh phim Avatar), núi Thiên Môn và cổ trấn Phượng Hoàng.',
     'places': [
        ('s', 'Công viên rừng quốc gia Trương Gia Giới', 'Zhangjiajie National Forest Park', 'Hàng nghìn cột đá sa thạch giữa mây', {'tip': 'Vé dùng nhiều ngày; đi thang máy Bách Long lên Viên Gia Giới.'}),
        ('s', 'Núi Thiên Môn', 'Tianmen Mountain', 'Cáp treo dài, cổng trời và đường kính bên vách núi', {}),
        ('c', 'Cầu kính Trương Gia Giới', 'Zhangjiajie Glass Bridge', 'Cầu đáy kính bắc qua hẻm núi', {}),
        ('c', 'Thang máy Bách Long', 'Bailong Elevator', 'Thang máy ngoài trời cao nhất thế giới', {}),
        ('s', 'Khu thắng cảnh Võ Lăng Nguyên', 'Wulingyuan', 'Di sản thiên nhiên thế giới UNESCO', {}),
        ('c', 'Phượng Hoàng cổ trấn', 'Fenghuang County', 'Phố cổ bên sông Đà Giang, lung linh về đêm', {'tip': 'Ở lại 1 đêm để ngắm đèn hai bên sông.'}),
        ('s', 'Động Hoàng Long', 'Huanglong Cave', 'Hang động thạch nhũ lớn, đi thuyền trong hang', {}),
     ]},
    {'id': 'yunnan', 'country': 'cn', 'name': 'Vân Nam (Lệ Giang – Đại Lý – Côn Minh)', 'local': '云南', 'wiki': 'Lijiang', 'best': [3, 4, 5, 9, 10, 11], 'days': '5–6 ngày',
     'intro': 'Phố cổ Lệ Giang, hồ Nhĩ Hải ở Đại Lý và núi tuyết Ngọc Long – hay đi kết hợp từ Côn Minh.',
     'places': [
        ('c', 'Phố cổ Lệ Giang', 'Old Town of Lijiang', 'Di sản UNESCO với kênh nước, mái ngói và đèn lồng', {}),
        ('s', 'Núi tuyết Ngọc Long', 'Jade Dragon Snow Mountain', 'Núi tuyết quanh năm, có cáp treo lên cao', {'tip': 'Lên độ cao lớn – mang áo ấm, bình oxy mini; không vận động mạnh.'}),
        ('c', 'Cổ trấn Thúc Hà', 'Shuhe', 'Thị trấn cổ yên tĩnh gần Lệ Giang', {}),
        ('c', 'Hồ Nhĩ Hải (Đại Lý)', 'Erhai Lake', 'Hồ cao nguyên xanh, đạp xe quanh hồ', {}),
        ('s', 'Tam Tháp chùa Sùng Thánh', 'Three Pagodas', 'Ba ngọn tháp cổ biểu tượng của Đại Lý', {}),
        ('c', 'Cổ thành Đại Lý', 'Dali Old Town', 'Phố cổ người Bạch dưới chân núi Thương Sơn', {}),
        ('s', 'Rừng đá Thạch Lâm (Côn Minh)', 'Stone Forest', 'Rừng đá vôi kỳ thú, di sản UNESCO', {}),
     ]},
    {'id': 'guilin', 'country': 'cn', 'name': 'Quế Lâm – Dương Sóc', 'local': '桂林', 'wiki': 'Guilin', 'best': [4, 5, 9, 10], 'days': '3–4 ngày',
     'intro': '"Quế Lâm sơn thủy giáp thiên hạ" – sông Ly, núi đá vôi và ruộng bậc thang.',
     'places': [
        ('s', 'Du thuyền sông Ly', 'Li River', 'Cảnh núi non in trên tờ 20 tệ', {'tip': 'Đi thuyền từ Quế Lâm xuống Dương Sóc khoảng 4 giờ.'}),
        ('c', 'Dương Sóc', 'Yangshuo County', 'Thị trấn giữa núi đá, đạp xe đồng quê', {}),
        ('f', 'Phố Tây Nhai (Dương Sóc)', 'West Street (Yangshuo)', 'Phố đi bộ ăn uống về đêm', {'ll': [24.7783, 110.4950]}),
        ('s', 'Động Lư Địch Nham', 'Reed Flute Cave', 'Hang động thạch nhũ rực rỡ ánh đèn', {}),
        ('c', 'Núi Voi', 'Elephant Trunk Hill', 'Biểu tượng của Quế Lâm bên sông Ly', {}),
        ('c', 'Ruộng bậc thang Long Tích', 'Longji Rice Terraces', 'Ruộng bậc thang trên núi của người Choang, Dao', {}),
        ('c', 'Sông Ngộ Long', 'Yulong River', 'Đi bè tre giữa đồng quê thơ mộng', {}),
     ]},
    # ---------------- HÀN QUỐC ----------------
    {'id': 'seoul', 'country': 'kr', 'name': 'Seoul', 'local': '서울', 'wiki': 'Seoul', 'best': [4, 5, 9, 10, 11], 'days': '4–5 ngày',
     'intro': 'Thủ đô Hàn Quốc: cung điện cổ, làng hanok, phố mua sắm và văn hóa K-pop.',
     'places': [
        ('s', 'Cung Gyeongbokgung', 'Gyeongbokgung', 'Cung điện lớn nhất triều Joseon, lễ đổi gác', {'tip': 'Mặc hanbok được vào cửa miễn phí; đóng cửa thứ Ba.'}),
        ('c', 'Làng Bukchon Hanok', 'Bukchon Hanok Village', 'Làng nhà truyền thống giữa phố', {'tip': 'Khu dân cư – giữ yên lặng, có giờ hạn chế khách.'}),
        ('c', 'Tháp N Seoul', 'N Seoul Tower', 'Ngắm toàn cảnh Seoul, ổ khóa tình yêu', {}),
        ('f', 'Myeongdong', 'Myeong-dong', 'Phố mua sắm mỹ phẩm và ăn vặt đường phố', {}),
        ('f', 'Chợ Gwangjang', 'Gwangjang Market', 'Chợ ẩm thực lâu đời: bánh xèo đậu xanh, kimbap', {}),
        ('s', 'Cung Changdeokgung', 'Changdeokgung', 'Cung điện di sản UNESCO với Hậu Uyển', {}),
        ('c', 'Lotte World Tower', 'Lotte World Tower', 'Tòa nhà cao nhất Hàn Quốc, đài Seoul Sky', {}),
        ('s', 'Lotte World', 'Lotte World', 'Công viên giải trí trong nhà lớn', {}),
        ('c', 'Dongdaemun Design Plaza', 'Dongdaemun Design Plaza', 'Kiến trúc tương lai, chợ đêm thời trang', {}),
        ('c', 'Đảo Nami', 'Namiseom', 'Hàng cây nổi tiếng trong phim, đi trong ngày', {}),
        ('f', 'Hongdae', 'Hongdae', 'Khu sinh viên, quán ăn, biểu diễn đường phố', {'ll': [37.5563, 126.9222]}),
     ]},
    {'id': 'busan', 'country': 'kr', 'name': 'Busan', 'local': '부산', 'wiki': 'Busan', 'best': [5, 6, 9, 10], 'days': '2–3 ngày',
     'intro': 'Thành phố cảng biển thứ hai Hàn Quốc: bãi biển, chợ cá và làng văn hóa sắc màu.',
     'places': [
        ('c', 'Bãi biển Haeundae', 'Haeundae Beach', 'Bãi biển nổi tiếng nhất Hàn Quốc', {}),
        ('c', 'Làng văn hóa Gamcheon', 'Gamcheon Culture Village', 'Làng nhà nhiều màu trên sườn đồi', {}),
        ('f', 'Chợ cá Jagalchi', 'Jagalchi Fish Market', 'Chợ hải sản lớn nhất Hàn Quốc, ăn tại chỗ', {}),
        ('s', 'Chùa Haedong Yonggungsa', 'Haedong Yonggungsa', 'Ngôi chùa hiếm hoi nằm sát mép biển', {}),
        ('c', 'Bãi biển Gwangalli', 'Gwangalli Beach', 'Ngắm cầu Gwangan lên đèn về đêm', {}),
        ('c', 'Taejongdae', 'Taejongdae', 'Vách đá và ngọn hải đăng bên biển', {}),
        ('c', 'Tháp Busan', 'Busan Tower', 'Ngắm toàn cảnh cảng Busan', {}),
     ]},
    {'id': 'jeju', 'country': 'kr', 'name': 'Đảo Jeju', 'local': '제주', 'wiki': 'Jeju Island', 'best': [4, 5, 9, 10], 'days': '3–4 ngày',
     'intro': 'Đảo núi lửa với miệng núi lửa, thác nước, hoa cải vàng – miễn visa nếu bay thẳng.',
     'places': [
        ('c', 'Đỉnh Seongsan Ilchulbong', 'Seongsan Ilchulbong', 'Miệng núi lửa ngắm bình minh, di sản UNESCO', {}),
        ('s', 'Núi Hallasan', 'Hallasan', 'Ngọn núi cao nhất Hàn Quốc', {'tip': 'Lên đỉnh cần đặt chỗ trước và đi từ sáng sớm.'}),
        ('s', 'Hang dung nham Manjanggul', 'Manjanggul', 'Ống dung nham dài, di sản UNESCO', {}),
        ('c', 'Thác Cheonjiyeon', 'Cheonjiyeon Waterfall', 'Thác nước giữa rừng, đẹp về đêm', {}),
        ('c', 'Thác Jeongbang', 'Jeongbang Waterfall', 'Thác nước đổ thẳng ra biển', {}),
        ('c', 'Đảo Udo', 'Udo (island)', 'Đảo nhỏ, đạp xe, bãi cát trắng', {}),
        ('c', 'Bãi biển Hyeopjae', 'Hyeopjae Beach', 'Nước biển xanh ngọc, cát trắng', {'ll': [33.3943, 126.2393]}),
        ('f', 'Chợ Dongmun', 'Dongmun Market', 'Chợ truyền thống: cam Jeju, thịt lợn đen', {'ll': [33.5119, 126.5273]}),
     ]},
    # ---------------- NHẬT BẢN ----------------
    {'id': 'tokyo', 'country': 'jp', 'name': 'Tokyo', 'local': '東京', 'wiki': 'Tokyo', 'best': [3, 4, 5, 10, 11], 'days': '4–5 ngày',
     'intro': 'Thủ đô hiện đại xen đền chùa cổ, ẩm thực phong phú, gần núi Phú Sĩ.',
     'places': [
        ('s', 'Chùa Sensō-ji (Asakusa)', 'Sensō-ji', 'Ngôi chùa cổ nhất Tokyo, cổng Sấm Kaminarimon', {}),
        ('c', 'Tokyo Skytree', 'Tokyo Skytree', 'Tháp truyền hình cao nhất Nhật Bản', {}),
        ('c', 'Ngã tư Shibuya', 'Shibuya Crossing', 'Ngã tư đông người qua lại nhất thế giới', {}),
        ('s', 'Đền Minh Trị', 'Meiji Shrine', 'Đền Thần đạo giữa rừng cây, gần Harajuku', {}),
        ('c', 'Tháp Tokyo', 'Tokyo Tower', 'Tháp đỏ trắng biểu tượng của Tokyo', {}),
        ('f', 'Chợ ngoài Tsukiji', 'Tsukiji fish market', 'Hải sản tươi, sushi, trứng cuộn', {'tip': 'Đi buổi sáng; nhiều quầy đóng cửa từ 14:00.'}),
        ('f', 'Akihabara', 'Akihabara', 'Phố điện tử, anime, quán cà phê hầu gái', {}),
        ('c', 'Vườn quốc gia Shinjuku Gyoen', 'Shinjuku Gyoen', 'Vườn hoa anh đào và lá đỏ đẹp nhất Tokyo', {}),
        ('s', 'Tokyo Disneyland', 'Tokyo Disneyland', 'Công viên Disney, hợp đi cùng trẻ em', {}),
        ('c', 'Hồ Kawaguchi – núi Phú Sĩ', 'Lake Kawaguchi', 'Ngắm núi Phú Sĩ, đi trong ngày từ Tokyo', {}),
        ('c', 'Công viên Ueno', 'Ueno Park', 'Công viên hoa anh đào, bảo tàng, sở thú', {}),
     ]},
    {'id': 'osaka', 'country': 'jp', 'name': 'Osaka – Nara', 'local': '大阪', 'wiki': 'Osaka', 'best': [3, 4, 5, 10, 11], 'days': '3 ngày',
     'intro': '"Căn bếp của Nhật Bản" – ăn vặt đường phố, lâu đài cổ và Universal Studios.',
     'places': [
        ('s', 'Lâu đài Osaka', 'Osaka Castle', 'Lâu đài biểu tượng giữa công viên hoa anh đào', {}),
        ('f', 'Dōtonbori', 'Dōtonbori', 'Phố ăn đêm: takoyaki, okonomiyaki, biển Glico', {}),
        ('s', 'Universal Studios Japan', 'Universal Studios Japan', 'Công viên giải trí, khu Super Nintendo World', {'tip': 'Mua vé và Express Pass trực tuyến trước.'}),
        ('f', 'Chợ Kuromon', 'Kuromon Market', 'Chợ hải sản, bò Wagyu nướng', {'ll': [34.6650, 135.5065]}),
        ('f', 'Shinsekai', 'Shinsekai', 'Khu phố cổ điển, món kushikatsu', {}),
        ('c', 'Umeda Sky Building', 'Umeda Sky Building', 'Đài quan sát lộ thiên ngắm hoàng hôn', {}),
        ('c', 'Công viên Nara', 'Nara Park', 'Hươu thả tự do, đi trong ngày từ Osaka', {}),
        ('s', 'Chùa Tōdai-ji (Nara)', 'Tōdai-ji', 'Tượng Đại Phật bằng đồng trong điện gỗ lớn', {}),
     ]},
    {'id': 'kyoto', 'country': 'jp', 'name': 'Kyoto', 'local': '京都', 'wiki': 'Kyoto', 'best': [3, 4, 10, 11], 'days': '2–3 ngày',
     'intro': 'Cố đô ngàn năm với hơn 1.600 ngôi chùa, phố geisha và rừng tre.',
     'places': [
        ('s', 'Đền Fushimi Inari', 'Fushimi Inari-taisha', 'Hàng nghìn cổng torii đỏ nối nhau lên núi', {'tip': 'Đến sớm trước 8 giờ để chụp ảnh vắng người.'}),
        ('s', 'Chùa Vàng Kinkaku-ji', 'Kinkaku-ji', 'Gác vàng soi bóng xuống hồ', {}),
        ('s', 'Chùa Kiyomizu-dera', 'Kiyomizu-dera', 'Sân gỗ treo trên vách đồi, view thành phố', {}),
        ('c', 'Rừng tre Arashiyama', 'Arashiyama', 'Lối đi giữa rừng tre và cầu Togetsukyō', {}),
        ('c', 'Phố Gion', 'Gion', 'Phố cổ geisha với nhà gỗ truyền thống', {}),
        ('f', 'Chợ Nishiki', 'Nishiki Market', '"Nhà bếp của Kyoto", ăn vặt và đặc sản', {}),
        ('s', 'Chùa Bạc Ginkaku-ji', 'Ginkaku-ji', 'Vườn cát và rêu tinh tế', {}),
        ('c', 'Triết lý chi đạo', "Philosopher's Walk", 'Con đường ven kênh trồng hoa anh đào', {}),
     ]},
    # ---------------- SINGAPORE ----------------
    {'id': 'singapore', 'country': 'sg', 'name': 'Singapore', 'local': 'Singapore', 'wiki': 'Singapore', 'best': [2, 3, 4, 5, 6, 7, 8, 9], 'days': '3–4 ngày',
     'intro': 'Quốc đảo sạch đẹp, hiện đại, nhiều khu vui chơi – rất hợp đi cùng gia đình.',
     'places': [
        ('c', 'Marina Bay Sands', 'Marina Bay Sands', 'Khách sạn biểu tượng, đài ngắm cảnh SkyPark', {}),
        ('c', 'Gardens by the Bay', 'Gardens by the Bay', 'Siêu cây phát sáng và nhà kính Cloud Forest', {'tip': 'Xem show ánh sáng Garden Rhapsody miễn phí buổi tối.'}),
        ('c', 'Công viên Merlion', 'Merlion Park', 'Tượng Sư tử biển biểu tượng Singapore', {}),
        ('s', 'Đảo Sentosa', 'Sentosa', 'Đảo giải trí: bãi biển, cáp treo, khu vui chơi', {}),
        ('s', 'Universal Studios Singapore', 'Universal Studios Singapore', 'Công viên giải trí trên đảo Sentosa', {}),
        ('f', 'Phố người Hoa (Chinatown)', 'Chinatown, Singapore', 'Đền chùa, chợ ẩm thực Maxwell gần đó', {}),
        ('f', 'Lau Pa Sat', 'Lau Pa Sat', 'Khu hawker cổ, phố sa tế về đêm', {}),
        ('f', 'Maxwell Food Centre', 'Maxwell Food Centre', 'Cơm gà Hải Nam nổi tiếng', {}),
        ('s', 'Sở thú Singapore', 'Singapore Zoo', 'Sở thú mở, có Night Safari bên cạnh', {}),
        ('c', 'Jewel Changi', 'Jewel Changi Airport', 'Thác nước trong nhà cao nhất thế giới tại sân bay', {}),
        ('c', 'Little India', 'Little India, Singapore', 'Khu phố Ấn Độ nhiều màu sắc', {}),
     ]},
    # ---------------- MALAYSIA ----------------
    {'id': 'kualalumpur', 'country': 'my', 'name': 'Kuala Lumpur', 'local': 'Kuala Lumpur', 'wiki': 'Kuala Lumpur', 'best': [5, 6, 7, 8, 12, 1, 2], 'days': '3 ngày',
     'intro': 'Thủ đô đa văn hóa với tháp đôi Petronas, động Batu và ẩm thực Mã – Hoa – Ấn.',
     'places': [
        ('c', 'Tháp đôi Petronas', 'Petronas Towers', 'Biểu tượng của Malaysia, cầu nối tầng 41', {'tip': 'Đẹp nhất khi lên đèn, chụp từ công viên KLCC.'}),
        ('s', 'Động Batu', 'Batu Caves', 'Đền Hindu trong hang đá, 272 bậc cầu thang nhiều màu', {}),
        ('f', 'Phố ẩm thực Jalan Alor', 'Jalan Alor', 'Phố ăn đêm nổi tiếng nhất KL', {'ll': [3.1457, 101.7085]}),
        ('c', 'Tháp KL', 'Kuala Lumpur Tower', 'Tháp truyền hình, sàn kính Sky Box', {'ll': [3.1528, 101.7039]}),
        ('c', 'Quảng trường Merdeka', 'Merdeka Square, Kuala Lumpur', 'Nơi tuyên bố độc lập, tòa nhà Sultan Abdul Samad', {}),
        ('f', 'Phố Petaling (Chinatown)', 'Petaling Street', 'Chợ người Hoa, ăn vặt và mua sắm', {}),
        ('s', 'Thành phố Putrajaya', 'Putrajaya', 'Thủ đô hành chính với nhà thờ Hồng', {}),
        ('s', 'Cao nguyên Genting', 'Genting Highlands', 'Khu nghỉ dưỡng trên núi, cáp treo, khu vui chơi', {}),
        ('s', 'Đền Thean Hou', 'Thean Hou Temple', 'Đền Hoa ba tầng trên đồi', {}),
     ]},
    {'id': 'penang', 'country': 'my', 'name': 'Penang', 'local': 'Pulau Pinang', 'wiki': 'Penang', 'best': [12, 1, 2, 3], 'days': '2–3 ngày',
     'intro': 'Đảo di sản với phố cổ George Town, tranh tường và thiên đường ẩm thực đường phố.',
     'places': [
        ('c', 'Phố cổ George Town', 'George Town, Penang', 'Di sản UNESCO, tranh tường đường phố', {}),
        ('c', 'Đồi Penang', 'Penang Hill', 'Tàu leo núi lên ngắm toàn đảo', {}),
        ('s', 'Chùa Cực Lạc', 'Kek Lok Si', 'Quần thể chùa Phật giáo lớn nhất Malaysia', {}),
        ('f', 'Gurney Drive', 'Gurney Drive', 'Khu hawker ven biển: char kway teow, laksa', {}),
        ('s', 'Dinh Cheong Fatt Tze (Nhà Xanh)', 'Cheong Fatt Tze Mansion', 'Dinh thự màu xanh lam của thương gia người Hoa', {}),
        ('s', 'Khoo Kongsi', 'Khoo Kongsi', 'Đền dòng họ chạm khắc tinh xảo', {}),
        ('c', 'Biển Batu Ferringhi', 'Batu Ferringhi', 'Bãi biển và chợ đêm', {}),
     ]},
    # ---------------- ĐÀI LOAN ----------------
    {'id': 'taipei', 'country': 'tw', 'name': 'Đài Bắc', 'local': '臺北', 'wiki': 'Taipei', 'best': [3, 4, 10, 11, 12], 'days': '3–4 ngày',
     'intro': 'Thành phố chợ đêm, trà sữa, suối nước nóng và phố núi Cửu Phần.',
     'places': [
        ('c', 'Tháp Taipei 101', 'Taipei 101', 'Tòa tháp biểu tượng, đài quan sát tầng 89', {}),
        ('s', 'Bảo tàng Cố Cung quốc gia', 'National Palace Museum', 'Kho báu cổ vật Trung Hoa', {}),
        ('f', 'Chợ đêm Sỹ Lâm', 'Shilin Night Market', 'Chợ đêm lớn nhất Đài Bắc', {}),
        ('f', 'Chợ đêm Nhiêu Hà', 'Raohe Street Night Market', 'Bánh tiêu hồ tiêu nổi tiếng', {}),
        ('c', 'Phố cổ Cửu Phần', 'Jiufen', 'Phố núi đèn lồng đỏ, quán trà ngắm biển', {'tip': 'Tránh cuối tuần; buổi chiều tối đẹp nhất.'}),
        ('s', 'Đài tưởng niệm Tưởng Giới Thạch', 'Chiang Kai-shek Memorial Hall', 'Quảng trường lớn, lễ đổi gác', {}),
        ('f', 'Tây Môn Đình', 'Ximending', 'Phố đi bộ mua sắm, ăn vặt của giới trẻ', {}),
        ('s', 'Chùa Long Sơn', 'Bangka Lungshan Temple', 'Ngôi chùa cổ linh thiêng nhất Đài Bắc', {}),
        ('c', 'Công viên địa chất Dã Liễu', 'Yehliu', 'Đá "nữ hoàng" kỳ lạ bên bờ biển', {}),
        ('c', 'Suối nước nóng Bắc Đầu', 'Beitou District', 'Suối nước nóng ngay trong thành phố', {}),
     ]},
    {'id': 'taichung', 'country': 'tw', 'name': 'Đài Trung – Nhật Nguyệt Đàm', 'local': '臺中', 'wiki': 'Taichung', 'best': [3, 4, 10, 11, 12], 'days': '2–3 ngày',
     'intro': 'Thành phố trẻ trung miền Trung Đài Loan, cửa ngõ đến hồ Nhật Nguyệt Đàm và núi A Lý.',
     'places': [
        ('c', 'Hồ Nhật Nguyệt Đàm', 'Sun Moon Lake', 'Hồ nước trên núi đẹp nhất Đài Loan, cáp treo', {}),
        ('c', 'Làng Cầu Vồng', 'Rainbow Village', 'Làng nhỏ vẽ tranh nhiều màu sắc', {}),
        ('f', 'Chợ đêm Phùng Giáp', 'Fengjia Night Market', 'Chợ đêm lớn, nơi ra đời nhiều món ăn vặt', {}),
        ('c', 'Đầm lầy Cao Mỹ', 'Gaomei Wetlands', 'Ngắm hoàng hôn và cối xay gió', {}),
        ('c', 'Nhà hát quốc gia Đài Trung', 'National Taichung Theater', 'Kiến trúc độc đáo của Toyo Ito', {}),
        ('s', 'Khu thắng cảnh A Lý Sơn', 'Alishan National Scenic Area', 'Tàu rừng, biển mây và bình minh trên núi', {}),
     ]},
    # ---------------- BALI ----------------
    {'id': 'bali', 'country': 'id', 'name': 'Bali', 'local': 'Bali', 'wiki': 'Bali', 'best': [4, 5, 6, 7, 8, 9, 10], 'days': '4–5 ngày',
     'intro': '"Đảo của các vị thần": đền biển, ruộng bậc thang Ubud, bãi biển và hoàng hôn.',
     'places': [
        ('s', 'Đền Tanah Lot', 'Tanah Lot', 'Ngôi đền trên mỏm đá giữa biển, ngắm hoàng hôn', {}),
        ('s', 'Đền Uluwatu', 'Uluwatu Temple', 'Đền trên vách đá, múa Kecak lúc hoàng hôn', {'tip': 'Giữ kính, mũ cẩn thận – khỉ hay giật đồ.'}),
        ('c', 'Ubud', 'Ubud', 'Trung tâm văn hóa nghệ thuật giữa rừng và ruộng lúa', {'ll': [-8.5069, 115.2625]}),
        ('c', 'Ruộng bậc thang Tegallalang', 'Tegallalang', 'Ruộng bậc thang và xích đu nổi tiếng', {}),
        ('c', 'Rừng khỉ Ubud', 'Sacred Monkey Forest Sanctuary', 'Khu rừng thiêng với hàng trăm chú khỉ', {}),
        ('s', 'Đền Ulun Danu Bratan', 'Pura Ulun Danu Bratan', 'Đền nổi trên hồ Bratan giữa núi', {}),
        ('s', 'Đền nước thánh Tirta Empul', 'Tirta Empul', 'Nghi lễ tắm nước thánh của người Bali', {}),
        ('c', 'Đảo Nusa Penida', 'Nusa Penida', 'Vách đá Kelingking, nước biển xanh ngọc', {'tip': 'Đi tàu nhanh từ Sanur; đường trên đảo xấu, nên thuê tài xế.'}),
        ('c', 'Bãi biển Kuta', 'Kuta, Bali', 'Bãi biển lướt sóng và hoàng hôn', {'ll': [-8.7184, 115.1686]}),
        ('f', 'Vịnh Jimbaran', 'Jimbaran', 'Hải sản nướng trên bãi cát lúc hoàng hôn', {}),
        ('s', 'Núi lửa Batur', 'Mount Batur', 'Leo núi đón bình minh', {'tip': 'Xuất phát khoảng 3–4 giờ sáng, đi cùng hướng dẫn viên.'}),
     ]},
]
