"""Dữ liệu cho TÍNH NĂNG LẬP LỊCH TRÌNH của mục Quốc tế (bổ sung cho intl_src.py).

- NEW: địa điểm thêm cho từng thành phố (nối vào CUỐI danh sách để không đổi mã các điểm cũ).
- META: thông tin lập lịch cho các điểm đã có, theo mã '<thành phố>-<số thứ tự>'.
- CITY: giá phòng, vé máy bay ước tính, cách đi lại tại chỗ, khu vực (nếu đi nhiều nơi).
- LOCAL: đơn giá đi lại tại chỗ theo nước (nghìn đồng).

Mọi giá là ƯỚC TÍNH theo mặt bằng chung (nghìn đồng), cập nhật theo intl_src.UPDATED, cần kiểm tra lại khi đặt.

Mã trong phần "thêm" của địa điểm:
  v   giá mỗi người (nghìn đồng); 0 = miễn phí            k   loại bữa của quán: sang, trua, toi, cafe, vat
  t   sở thích: h lịch sử–văn hóa, n thiên nhiên, b biển, p chụp ảnh, s ẩm thực đường phố, c cà phê, r nghỉ dưỡng, k nổi tiếng, m mát mẻ
  d   thời lượng (phút)      io  i trong nhà, o ngoài trời, m cả hai
  ss  ngắm hoàng hôn         ev  đẹp buổi tối ('all' | 'weekend')      eo  chỉ mở/đẹp buổi tối
  mo  chỉ nên đi buổi sáng   cl  ngày nghỉ trong tuần (0 = CN, 1 = T2 … 6 = T7)       h giờ mở cửa
  a   khu vực (thành phố có nhiều khu)     trip  điểm đi trong ngày (xa trung tâm, cần cả ngày)
  f   'x' vất vả (không hợp trẻ nhỏ, người lớn tuổi), 'o' nhiều bậc/dốc (không hợp người lớn tuổi)
"""

# Đi lại tại chỗ (nghìn đồng): metro = (giá mở cửa, mỗi km) / người; car = (mở cửa, mỗi km) / xe 4 chỗ;
# far = cách đi xa: ('hire', mở cửa, mỗi km) theo xe 6 chỗ, hoặc ('train', mở cửa, mỗi km) theo người
LOCAL = {
    'th': {'metro': (30, 2.5), 'car': (40, 9), 'far': ('hire', 150, 9)},
    'cn': {'metro': (15, 1.5), 'car': (35, 8), 'far': ('hire', 200, 10)},
    'kr': {'metro': (25, 1.5), 'car': (70, 18), 'far': ('train', 50, 2.2)},
    'jp': {'metro': (35, 4), 'car': (150, 45), 'far': ('train', 50, 3.3)},
    'sg': {'metro': (25, 2), 'car': (80, 15), 'far': ('hire', 300, 15)},
    'my': {'metro': (15, 1.2), 'car': (25, 6), 'far': ('hire', 150, 7)},
    'tw': {'metro': (20, 2), 'car': (50, 12), 'far': ('train', 20, 1.5)},
    'id': {'metro': None, 'car': (40, 8), 'far': ('hire', 150, 8)},
}

# hotel: giá phòng/đêm [tiết kiệm, tầm trung, cao cấp] (nghìn đồng)
# fly: {sân bay đi: (vé khứ hồi/người nghìn đồng, giờ bay một chiều)}  – ƯỚC TÍNH, thay đổi theo mùa và ngày đặt
# tr: 'metro' (có tàu điện) hoặc 'car' (taxi/Grab là chính); air: tên sân bay đến; extra: phí thêm từ sân bay (người, khứ hồi)
CITY = {
    'bangkok':     {'hotel': [600, 1500, 4000], 'fly': {'HAN': (4500, 1.9), 'SGN': (3800, 1.4)}, 'tr': 'metro', 'air': 'Bangkok'},
    'pattaya':     {'hotel': [500, 1200, 3500], 'fly': {'HAN': (4500, 1.9), 'SGN': (3800, 1.4)}, 'tr': 'car', 'air': 'Bangkok', 'extra': (500, 2.0)},
    'phuket':      {'hotel': [600, 1600, 5000], 'fly': {'HAN': (6000, 2.5), 'SGN': (4500, 1.6)}, 'tr': 'car', 'air': 'Phuket'},
    'chiangmai':   {'hotel': [450, 1100, 3000], 'fly': {'HAN': (5000, 1.7), 'SGN': (5500, 2.2)}, 'tr': 'car', 'air': 'Chiang Mai'},
    'beijing':     {'hotel': [800, 1800, 4500], 'fly': {'HAN': (7500, 3.5), 'SGN': (9000, 4.5)}, 'tr': 'metro', 'air': 'Bắc Kinh'},
    'shanghai':    {'hotel': [900, 2000, 5000], 'fly': {'HAN': (7500, 3.2), 'SGN': (8000, 3.8)}, 'tr': 'metro', 'air': 'Thượng Hải'},
    'zhangjiajie': {'hotel': [500, 1100, 2800], 'fly': {'HAN': (7000, 2.5), 'SGN': (8500, 3.5)}, 'tr': 'car', 'air': 'Trương Gia Giới',
                    'areas': ['Trương Gia Giới', 'Phượng Hoàng']},
    'yunnan':      {'hotel': [500, 1100, 2800], 'fly': {'HAN': (5500, 1.5), 'SGN': (7000, 2.5)}, 'tr': 'car', 'air': 'Côn Minh',
                    'areas': ['Côn Minh', 'Đại Lý', 'Lệ Giang']},
    'guilin':      {'hotel': [450, 1000, 2600], 'fly': {'HAN': (6500, 1.5), 'SGN': (7500, 2.5)}, 'tr': 'car', 'air': 'Quế Lâm',
                    'areas': ['Quế Lâm', 'Dương Sóc']},
    'seoul':       {'hotel': [1000, 2200, 5500], 'fly': {'HAN': (8500, 4.5), 'SGN': (8500, 5.0)}, 'tr': 'metro', 'air': 'Incheon'},
    'busan':       {'hotel': [900, 1900, 4500], 'fly': {'HAN': (8500, 4.3), 'SGN': (9000, 4.8)}, 'tr': 'metro', 'air': 'Gimhae (Busan)'},
    'jeju':        {'hotel': [900, 2000, 5000], 'fly': {'HAN': (9000, 4.5), 'SGN': (9000, 4.8)}, 'tr': 'car', 'air': 'Jeju'},
    'tokyo':       {'hotel': [1500, 3000, 7500], 'fly': {'HAN': (12000, 5.5), 'SGN': (12000, 6.0)}, 'tr': 'metro', 'air': 'Narita/Haneda'},
    'osaka':       {'hotel': [1300, 2600, 6500], 'fly': {'HAN': (11000, 5.0), 'SGN': (11000, 5.5)}, 'tr': 'metro', 'air': 'Kansai'},
    'kyoto':       {'hotel': [1400, 3000, 8000], 'fly': {'HAN': (11000, 5.0), 'SGN': (11000, 5.5)}, 'tr': 'metro', 'air': 'Kansai', 'extra': (700, 1.3)},
    'singapore':   {'hotel': [1600, 3500, 8000], 'fly': {'HAN': (5000, 3.3), 'SGN': (3500, 2.0)}, 'tr': 'metro', 'air': 'Changi'},
    'kualalumpur': {'hotel': [500, 1100, 3000], 'fly': {'HAN': (4500, 3.3), 'SGN': (3000, 2.0)}, 'tr': 'metro', 'air': 'Kuala Lumpur'},
    'penang':      {'hotel': [500, 1100, 2800], 'fly': {'HAN': (6000, 3.5), 'SGN': (4500, 2.0)}, 'tr': 'car', 'air': 'Penang'},
    'taipei':      {'hotel': [1000, 2000, 5000], 'fly': {'HAN': (6500, 3.0), 'SGN': (6500, 3.3)}, 'tr': 'metro', 'air': 'Đào Viên'},
    'taichung':    {'hotel': [800, 1600, 4000], 'fly': {'HAN': (7000, 3.0), 'SGN': (7000, 3.3)}, 'tr': 'car', 'air': 'Đài Trung',
                    'areas': ['Đài Trung', 'Nhật Nguyệt Đàm']},
    'bali':        {'hotel': [500, 1300, 4000], 'fly': {'HAN': (9000, 5.0), 'SGN': (7000, 4.0)}, 'tr': 'car', 'air': 'Denpasar',
                    'areas': ['Nam Bali', 'Ubud']},
}

# ---------- Thông tin lập lịch cho các điểm đã có ----------
META = {
    # Bangkok
    'bangkok-1': {'v': 390, 'd': 150, 't': 'hpk', 'io': 'm', 'h': '8:30–15:30'},
    'bangkok-2': {'v': 235, 'd': 75, 't': 'hpk', 'io': 'm', 'h': '8:00–18:30'},
    'bangkok-3': {'v': 160, 'd': 60, 't': 'hpk', 'io': 'o', 'ss': 1, 'h': '8:00–18:00'},
    'bangkok-4': {'k': 'toi,vat', 'v': 200, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'bangkok-5': {'k': 'trua,vat', 'v': 150, 'd': 150, 't': 'sp', 'io': 'm', 'cl': [1, 2, 3, 4, 5], 'h': 'T7, CN khoảng 9:00–18:00'},
    'bangkok-6': {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'pr', 'io': 'i', 'ev': 'all', 'h': '10:00–22:00'},
    'bangkok-7': {'v': 0, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1, 'h': '17:00–24:00'},
    'bangkok-8': {'v': 750, 'd': 75, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all', 'h': '10:00–24:00'},
    'bangkok-9': {'v': 160, 'd': 75, 't': 'h', 'io': 'i', 'h': '10:00–18:00'},
    'bangkok-10': {'v': 1000, 'd': 300, 't': 'n', 'io': 'o', 'h': '9:00–17:00'},
    'bangkok-11': {'k': 'sang,trua', 'v': 300, 'd': 240, 't': 'sp', 'io': 'o', 'mo': 1, 'trip': 1},
    # Pattaya
    'pattaya-1': {'v': 400, 'd': 120, 't': 'hpk', 'io': 'm', 'h': '8:00–18:00'},
    'pattaya-2': {'v': 450, 'd': 180, 't': 'np', 'io': 'o', 'h': '8:00–18:00'},
    'pattaya-3': {'v': 60, 'd': 300, 't': 'bnr', 'io': 'o'},
    'pattaya-4': {'k': 'toi,vat', 'v': 250, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'pattaya-5': {'v': 0, 'd': 45, 't': 'p', 'io': 'o'},
    'pattaya-6': {'v': 780, 'd': 90, 't': 'p', 'io': 'i', 'ev': 'all', 'eo': 1},
    'pattaya-7': {'k': 'trua,vat', 'v': 300, 'd': 120, 't': 'sp', 'io': 'o', 'h': '9:00–19:00'},
    'pattaya-8': {'v': 0, 'd': 90, 't': 'br', 'io': 'o', 'ss': 1},
    # Phuket
    'phuket-1': {'v': 0, 'd': 60, 't': 'phk', 'io': 'o', 'h': '8:00–19:00'},
    'phuket-2': {'v': 1500, 'd': 480, 't': 'bnk', 'io': 'o', 'trip': 1},
    'phuket-3': {'v': 1300, 'd': 420, 't': 'nb', 'io': 'o', 'trip': 1},
    'phuket-4': {'v': 0, 'd': 120, 't': 'br', 'io': 'o', 'ss': 1},
    'phuket-5': {'k': 'toi,vat', 'v': 300, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'phuket-6': {'v': 0, 'd': 60, 't': 'pn', 'io': 'o', 'ss': 1},
    'phuket-7': {'v': 0, 'd': 60, 't': 'hk', 'io': 'm'},
    'phuket-8': {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'pch', 'io': 'o'},
    'phuket-9': {'v': 0, 'd': 150, 't': 'br', 'io': 'o', 'ss': 1},
    # Chiang Mai
    'chiangmai-1': {'v': 40, 'd': 120, 't': 'hpkm', 'io': 'o', 'f': 'o'},
    'chiangmai-2': {'v': 40, 'd': 60, 't': 'hk', 'io': 'o'},
    'chiangmai-3': {'v': 20, 'd': 60, 't': 'h', 'io': 'm'},
    'chiangmai-4': {'v': 0, 'd': 30, 't': 'hp', 'io': 'o'},
    'chiangmai-5': {'k': 'toi,vat', 'v': 150, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'chiangmai-6': {'v': 250, 'd': 420, 't': 'nm', 'io': 'o', 'trip': 1},
    'chiangmai-7': {'v': 80, 'd': 480, 't': 'hp', 'io': 'o', 'trip': 1},
    'chiangmai-8': {'v': 2000, 'd': 420, 't': 'n', 'io': 'o', 'trip': 1},
    'chiangmai-9': {'k': 'cafe,trua,toi', 'v': 150, 'd': 90, 't': 'cs', 'io': 'm', 'ev': 'all'},
    # Bắc Kinh
    'beijing-1': {'v': 220, 'd': 180, 't': 'hk', 'io': 'm', 'cl': [1], 'h': '8:30–17:00, nghỉ thứ Hai'},
    'beijing-2': {'v': 0, 'd': 45, 't': 'hk', 'io': 'o', 'mo': 1},
    'beijing-3': {'v': 550, 'd': 360, 't': 'hnk', 'io': 'o', 'f': 'o', 'trip': 1},
    'beijing-4': {'v': 450, 'd': 360, 't': 'hnk', 'io': 'o', 'f': 'o', 'trip': 1},
    'beijing-5': {'v': 125, 'd': 120, 't': 'hk', 'io': 'o', 'h': '6:00–22:00'},
    'beijing-6': {'v': 110, 'd': 180, 't': 'hnp', 'io': 'o'},
    'beijing-7': {'k': 'toi,vat', 'v': 200, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all'},
    'beijing-8': {'k': 'trua,cafe,vat', 'v': 150, 'd': 90, 't': 'scp', 'io': 'o'},
    'beijing-9': {'v': 180, 'd': 60, 't': 'p', 'io': 'o', 'ev': 'all'},
    'beijing-10': {'v': 90, 'd': 75, 't': 'h', 'io': 'm', 'mo': 1, 'h': '9:00–16:30'},
    'beijing-11': {'v': 0, 'd': 90, 't': 'pr', 'io': 'o', 'ss': 1, 'ev': 'all'},
    # Thượng Hải
    'shanghai-1': {'v': 0, 'd': 75, 't': 'hpk', 'io': 'o', 'ss': 1, 'ev': 'all'},
    'shanghai-2': {'v': 700, 'd': 90, 't': 'pk', 'io': 'm', 'ev': 'all'},
    'shanghai-3': {'v': 650, 'd': 75, 't': 'p', 'io': 'i', 'ss': 1, 'ev': 'all'},
    'shanghai-4': {'v': 150, 'd': 90, 't': 'hp', 'io': 'o', 'cl': [1], 'h': '9:00–16:30, nghỉ thứ Hai'},
    'shanghai-5': {'k': 'toi,vat', 'v': 200, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all'},
    'shanghai-6': {'k': 'trua,cafe,vat', 'v': 150, 'd': 90, 't': 'scp', 'io': 'o'},
    'shanghai-7': {'k': 'check,cafe', 'v': 0, 'd': 75, 't': 'cp', 'io': 'o', 'ev': 'all'},
    'shanghai-8': {'v': 0, 'd': 240, 't': 'hp', 'io': 'o', 'trip': 1},
    'shanghai-9': {'v': 1800, 'd': 480, 't': 'p', 'io': 'o', 'trip': 1},
    # Trương Gia Giới – Phượng Hoàng
    'zhangjiajie-1': {'v': 900, 'd': 360, 't': 'npk', 'io': 'o', 'f': 'o', 'a': 'Trương Gia Giới'},
    'zhangjiajie-2': {'v': 1000, 'd': 300, 't': 'npk', 'io': 'o', 'f': 'o', 'a': 'Trương Gia Giới'},
    'zhangjiajie-3': {'v': 500, 'd': 120, 't': 'np', 'io': 'o', 'a': 'Trương Gia Giới'},
    'zhangjiajie-4': {'v': 260, 'd': 45, 't': 'np', 'io': 'o', 'a': 'Trương Gia Giới'},
    'zhangjiajie-5': {'v': 0, 'd': 240, 't': 'np', 'io': 'o', 'f': 'o', 'a': 'Trương Gia Giới'},
    'zhangjiajie-6': {'k': 'check,trua,toi,vat,cafe', 'v': 0, 'd': 180, 't': 'hpk', 'io': 'o', 'ev': 'all', 'a': 'Phượng Hoàng'},
    'zhangjiajie-7': {'v': 400, 'd': 120, 't': 'n', 'io': 'i', 'a': 'Trương Gia Giới'},
    # Vân Nam
    'yunnan-1': {'k': 'check,sang,toi,vat', 'v': 0, 'd': 180, 't': 'hpk', 'io': 'o', 'ev': 'all', 'a': 'Lệ Giang'},
    'yunnan-2': {'v': 1100, 'd': 360, 't': 'nmk', 'io': 'o', 'f': 'x', 'a': 'Lệ Giang'},
    'yunnan-3': {'v': 0, 'd': 120, 't': 'hpr', 'io': 'o', 'a': 'Lệ Giang'},
    'yunnan-4': {'v': 0, 'd': 180, 't': 'nrp', 'io': 'o', 'ss': 1, 'a': 'Đại Lý'},
    'yunnan-5': {'v': 270, 'd': 120, 't': 'hk', 'io': 'o', 'a': 'Đại Lý'},
    'yunnan-6': {'k': 'check,toi,cafe,vat', 'v': 0, 'd': 150, 't': 'hp', 'io': 'o', 'ev': 'all', 'a': 'Đại Lý'},
    'yunnan-7': {'v': 470, 'd': 300, 't': 'np', 'io': 'o', 'trip': 1, 'a': 'Côn Minh'},
    # Quế Lâm – Dương Sóc
    'guilin-1': {'v': 1300, 'd': 360, 't': 'npk', 'io': 'o', 'trip': 1, 'a': 'Quế Lâm'},
    'guilin-2': {'v': 0, 'd': 180, 't': 'npr', 'io': 'o', 'a': 'Dương Sóc'},
    'guilin-3': {'k': 'toi,vat,cafe', 'v': 200, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Dương Sóc'},
    'guilin-4': {'v': 450, 'd': 75, 't': 'n', 'io': 'i', 'a': 'Quế Lâm'},
    'guilin-5': {'v': 200, 'd': 60, 't': 'pk', 'io': 'o', 'ss': 1, 'a': 'Quế Lâm'},
    'guilin-6': {'v': 400, 'd': 300, 't': 'np', 'io': 'o', 'f': 'o', 'trip': 1, 'a': 'Quế Lâm'},
    'guilin-7': {'v': 600, 'd': 150, 't': 'npr', 'io': 'o', 'a': 'Dương Sóc'},
    # Seoul
    'seoul-1': {'v': 55, 'd': 120, 't': 'hpk', 'io': 'o', 'cl': [2], 'h': '9:00–18:00, nghỉ thứ Ba'},
    'seoul-2': {'v': 0, 'd': 75, 't': 'hp', 'io': 'o', 'h': 'Khách tham quan 10:00–17:00'},
    'seoul-3': {'v': 380, 'd': 90, 't': 'pk', 'io': 'm', 'ss': 1, 'ev': 'all'},
    'seoul-4': {'k': 'toi,vat', 'v': 250, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all'},
    'seoul-5': {'k': 'trua,toi,vat', 'v': 200, 'd': 75, 't': 's', 'io': 'm'},
    'seoul-6': {'v': 55, 'd': 120, 't': 'hp', 'io': 'o', 'cl': [1]},
    'seoul-7': {'v': 550, 'd': 90, 't': 'p', 'io': 'i', 'ss': 1, 'ev': 'all'},
    'seoul-8': {'v': 1100, 'd': 300, 't': 'p', 'io': 'i'},
    'seoul-9': {'v': 0, 'd': 60, 't': 'p', 'io': 'o', 'ev': 'all'},
    'seoul-10': {'v': 300, 'd': 300, 't': 'npr', 'io': 'o', 'trip': 1},
    'seoul-11': {'k': 'toi,vat,cafe', 'v': 250, 'd': 120, 't': 'scp', 'io': 'o', 'ev': 'all'},
    # Busan
    'busan-1': {'v': 0, 'd': 120, 't': 'brk', 'io': 'o'},
    'busan-2': {'v': 0, 'd': 120, 't': 'pk', 'io': 'o', 'f': 'o'},
    'busan-3': {'k': 'trua,toi', 'v': 400, 'd': 90, 't': 's', 'io': 'm'},
    'busan-4': {'v': 0, 'd': 75, 't': 'hpb', 'io': 'o', 'f': 'o', 'mo': 1},
    'busan-5': {'v': 0, 'd': 90, 't': 'bp', 'io': 'o', 'ss': 1, 'ev': 'all'},
    'busan-6': {'v': 70, 'd': 120, 't': 'np', 'io': 'o'},
    'busan-7': {'v': 220, 'd': 60, 't': 'p', 'io': 'm', 'ev': 'all'},
    # Jeju
    'jeju-1': {'v': 90, 'd': 90, 't': 'npk', 'io': 'o', 'f': 'o', 'mo': 1},
    'jeju-2': {'v': 0, 'd': 480, 't': 'n', 'io': 'o', 'f': 'x', 'mo': 1},
    'jeju-3': {'v': 70, 'd': 60, 't': 'n', 'io': 'i'},
    'jeju-4': {'v': 40, 'd': 45, 't': 'np', 'io': 'o', 'ev': 'all'},
    'jeju-5': {'v': 40, 'd': 45, 't': 'np', 'io': 'o'},
    'jeju-6': {'v': 200, 'd': 240, 't': 'bnr', 'io': 'o'},
    'jeju-7': {'v': 0, 'd': 120, 't': 'brp', 'io': 'o', 'ss': 1},
    'jeju-8': {'k': 'trua,toi,vat', 'v': 250, 'd': 75, 't': 's', 'io': 'm', 'ev': 'all'},
    # Tokyo
    'tokyo-1': {'v': 0, 'd': 90, 't': 'hpk', 'io': 'o', 'ev': 'all'},
    'tokyo-2': {'v': 600, 'd': 90, 't': 'pk', 'io': 'i', 'ss': 1, 'ev': 'all'},
    'tokyo-3': {'v': 0, 'd': 45, 't': 'pk', 'io': 'o', 'ev': 'all'},
    'tokyo-4': {'v': 0, 'd': 75, 't': 'hn', 'io': 'o', 'mo': 1},
    'tokyo-5': {'v': 200, 'd': 60, 't': 'p', 'io': 'm', 'ev': 'all'},
    'tokyo-6': {'k': 'sang,trua', 'v': 400, 'd': 90, 't': 's', 'io': 'o', 'mo': 1, 'cl': [0], 'h': 'Khoảng 6:00–14:00, nhiều quầy nghỉ CN'},
    'tokyo-7': {'k': 'trua,toi,cafe,vat', 'v': 300, 'd': 120, 't': 'sp', 'io': 'm', 'ev': 'all'},
    'tokyo-8': {'v': 85, 'd': 90, 't': 'nrp', 'io': 'o', 'cl': [1], 'h': '9:00–17:30, nghỉ thứ Hai'},
    'tokyo-9': {'v': 1700, 'd': 480, 't': 'p', 'io': 'o', 'trip': 0},
    'tokyo-10': {'v': 0, 'd': 360, 't': 'npk', 'io': 'o', 'trip': 1},
    'tokyo-11': {'v': 0, 'd': 90, 't': 'nr', 'io': 'o'},
    # Osaka – Nara
    'osaka-1': {'v': 100, 'd': 120, 't': 'hk', 'io': 'm', 'a': 'Osaka'},
    'osaka-2': {'k': 'toi,vat', 'v': 300, 'd': 90, 't': 'spk', 'io': 'o', 'ev': 'all', 'a': 'Osaka'},
    'osaka-3': {'v': 1700, 'd': 540, 't': 'p', 'io': 'o', 'a': 'Osaka'},
    'osaka-4': {'k': 'sang,trua,vat', 'v': 400, 'd': 75, 't': 's', 'io': 'm', 'a': 'Osaka'},
    'osaka-5': {'k': 'trua,toi', 'v': 300, 'd': 75, 't': 's', 'io': 'm', 'ev': 'all', 'a': 'Osaka'},
    'osaka-6': {'v': 300, 'd': 60, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all', 'a': 'Osaka'},
    'osaka-7': {'v': 0, 'd': 120, 't': 'npk', 'io': 'o', 'a': 'Nara'},
    'osaka-8': {'v': 140, 'd': 75, 't': 'hk', 'io': 'm', 'a': 'Nara'},
    # Kyoto
    'kyoto-1': {'v': 0, 'd': 120, 't': 'hpk', 'io': 'o', 'f': 'o', 'mo': 1},
    'kyoto-2': {'v': 90, 'd': 60, 't': 'hpk', 'io': 'o'},
    'kyoto-3': {'v': 85, 'd': 90, 't': 'hpk', 'io': 'o', 'ss': 1},
    'kyoto-4': {'v': 0, 'd': 180, 't': 'npk', 'io': 'o', 'mo': 1},
    'kyoto-5': {'v': 0, 'd': 75, 't': 'hp', 'io': 'o', 'ev': 'all'},
    'kyoto-6': {'k': 'trua,vat', 'v': 300, 'd': 75, 't': 's', 'io': 'm', 'h': 'Khoảng 10:00–17:00'},
    'kyoto-7': {'v': 90, 'd': 60, 't': 'hn', 'io': 'o'},
    'kyoto-8': {'v': 0, 'd': 60, 't': 'nr', 'io': 'o'},
    # Singapore
    'singapore-1': {'v': 650, 'd': 60, 't': 'pk', 'io': 'm', 'ss': 1, 'ev': 'all'},
    'singapore-2': {'v': 600, 'd': 150, 't': 'npk', 'io': 'm', 'ev': 'all'},
    'singapore-3': {'v': 0, 'd': 45, 't': 'pk', 'io': 'o', 'ev': 'all'},
    'singapore-4': {'v': 0, 'd': 300, 't': 'br', 'io': 'o', 'ss': 1},
    'singapore-5': {'v': 1700, 'd': 480, 't': 'p', 'io': 'o'},
    'singapore-6': {'k': 'trua,toi,vat', 'v': 200, 'd': 90, 't': 'sh', 'io': 'm', 'ev': 'all'},
    'singapore-7': {'k': 'toi,vat', 'v': 250, 'd': 75, 't': 's', 'io': 'm', 'ev': 'all'},
    'singapore-8': {'k': 'sang,trua', 'v': 120, 'd': 60, 't': 's', 'io': 'm', 'cl': [1]},
    'singapore-9': {'v': 950, 'd': 240, 't': 'n', 'io': 'o'},
    'singapore-10': {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'p', 'io': 'i', 'ev': 'all'},
    'singapore-11': {'k': 'check,trua', 'v': 0, 'd': 75, 't': 'hps', 'io': 'o'},
    # Kuala Lumpur
    'kualalumpur-1': {'v': 600, 'd': 75, 't': 'pk', 'io': 'm', 'ev': 'all', 'cl': [1]},
    'kualalumpur-2': {'v': 0, 'd': 90, 't': 'hpk', 'io': 'o', 'f': 'o', 'mo': 1},
    'kualalumpur-3': {'k': 'toi,vat', 'v': 150, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'kualalumpur-4': {'v': 350, 'd': 75, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all'},
    'kualalumpur-5': {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'ev': 'all'},
    'kualalumpur-6': {'k': 'trua,toi,vat', 'v': 120, 'd': 75, 't': 's', 'io': 'o', 'ev': 'all'},
    'kualalumpur-7': {'v': 0, 'd': 180, 't': 'hp', 'io': 'o', 'trip': 0},
    'kualalumpur-8': {'v': 700, 'd': 420, 't': 'nm', 'io': 'm', 'trip': 1},
    'kualalumpur-9': {'v': 0, 'd': 60, 't': 'hp', 'io': 'o', 'ev': 'all'},
    # Penang
    'penang-1': {'k': 'check,cafe', 'v': 0, 'd': 180, 't': 'hpck', 'io': 'o'},
    'penang-2': {'v': 170, 'd': 150, 't': 'nmp', 'io': 'o', 'ss': 1, 'ev': 'all'},
    'penang-3': {'v': 20, 'd': 90, 't': 'h', 'io': 'o', 'f': 'o'},
    'penang-4': {'k': 'toi,vat', 'v': 120, 'd': 75, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'penang-5': {'v': 140, 'd': 60, 't': 'h', 'io': 'i'},
    'penang-6': {'v': 110, 'd': 60, 't': 'hp', 'io': 'm'},
    'penang-7': {'v': 0, 'd': 150, 't': 'br', 'io': 'o', 'ss': 1, 'ev': 'all'},
    # Đài Bắc
    'taipei-1': {'v': 490, 'd': 90, 't': 'pk', 'io': 'i', 'ss': 1, 'ev': 'all'},
    'taipei-2': {'v': 290, 'd': 150, 't': 'h', 'io': 'i', 'cl': [1]},
    'taipei-3': {'k': 'toi,vat', 'v': 200, 'd': 120, 't': 'sk', 'io': 'o', 'ev': 'all', 'eo': 1},
    'taipei-4': {'k': 'toi,vat', 'v': 150, 'd': 90, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1},
    'taipei-5': {'k': 'check,cafe', 'v': 0, 'd': 240, 't': 'hpk', 'io': 'o', 'ss': 1, 'trip': 0},
    'taipei-6': {'v': 0, 'd': 75, 't': 'hp', 'io': 'o'},
    'taipei-7': {'k': 'trua,toi,vat,cafe', 'v': 180, 'd': 90, 't': 'sp', 'io': 'o', 'ev': 'all'},
    'taipei-8': {'v': 0, 'd': 45, 't': 'h', 'io': 'm'},
    'taipei-9': {'v': 100, 'd': 120, 't': 'np', 'io': 'o', 'trip': 0},
    'taipei-10': {'v': 0, 'd': 120, 't': 'nr', 'io': 'm'},
    # Đài Trung – Nhật Nguyệt Đàm
    'taichung-1': {'v': 0, 'd': 240, 't': 'nprk', 'io': 'o', 'a': 'Nhật Nguyệt Đàm'},
    'taichung-2': {'v': 0, 'd': 45, 't': 'p', 'io': 'o', 'a': 'Đài Trung'},
    'taichung-3': {'k': 'toi,vat', 'v': 150, 'd': 120, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1, 'a': 'Đài Trung'},
    'taichung-4': {'v': 0, 'd': 90, 't': 'np', 'io': 'o', 'ss': 1, 'a': 'Đài Trung'},
    'taichung-5': {'v': 0, 'd': 60, 't': 'p', 'io': 'i', 'a': 'Đài Trung', 'cl': [1]},
    'taichung-6': {'v': 300, 'd': 480, 't': 'nm', 'io': 'o', 'trip': 1, 'a': 'Đài Trung'},
    # Bali
    'bali-1': {'v': 120, 'd': 90, 't': 'hpk', 'io': 'o', 'ss': 1, 'a': 'Nam Bali'},
    'bali-2': {'v': 80, 'd': 120, 't': 'hpb', 'io': 'o', 'ss': 1, 'a': 'Nam Bali'},
    'bali-3': {'k': 'check,cafe,sang,toi', 'v': 0, 'd': 120, 't': 'hcr', 'io': 'o', 'a': 'Ubud'},
    'bali-4': {'v': 50, 'd': 90, 't': 'np', 'io': 'o', 'f': 'o', 'mo': 1, 'a': 'Ubud'},
    'bali-5': {'v': 130, 'd': 75, 't': 'n', 'io': 'o', 'a': 'Ubud'},
    'bali-6': {'v': 120, 'd': 90, 't': 'hnpm', 'io': 'o', 'trip': 1, 'a': 'Ubud'},
    'bali-7': {'v': 80, 'd': 75, 't': 'h', 'io': 'o', 'a': 'Ubud'},
    'bali-8': {'v': 900, 'd': 540, 't': 'bnp', 'io': 'o', 'trip': 1, 'a': 'Nam Bali'},
    'bali-9': {'v': 0, 'd': 120, 't': 'br', 'io': 'o', 'ss': 1, 'a': 'Nam Bali'},
    'bali-10': {'k': 'toi', 'v': 500, 'd': 120, 't': 'sb', 'io': 'o', 'ss': 1, 'a': 'Nam Bali'},
    'bali-11': {'v': 1000, 'd': 420, 't': 'n', 'io': 'o', 'f': 'x', 'trip': 1, 'a': 'Ubud'},
}

# ---------- Địa điểm bổ sung (nối vào cuối danh sách của mỗi thành phố) ----------
# (loại, tên hiển thị, bài Wikipedia tiếng Anh, vì sao nên đến, thêm)
NEW = {
    'bangkok': [
        ('f', 'Chợ Or Tor Kor', 'Or Tor Kor Market', 'Chợ nông sản sạch nổi tiếng, trái cây Thái và món ăn nấu sẵn', {'k': 'sang,trua', 'v': 150, 't': 's', 'io': 'i', 'h': 'Khoảng 6:00–18:00'}),
        ('f', 'Phố Khao San', 'Khao San Road', 'Phố Tây ba lô: pad thai, xoài nếp, quán bar', {'k': 'toi,vat', 'v': 150, 't': 's', 'io': 'o', 'ev': 'all'}),
        ('f', 'Khu Pratunam', 'Pratunam', 'Chợ quần áo sỉ và nhiều quán cơm gà, đồ nướng', {'k': 'trua,toi,vat', 'v': 120, 't': 's', 'io': 'm'}),
        ('f', 'Phố Silom', 'Silom', 'Khu phố ăn đêm, chợ đêm và quán xá ở trung tâm', {'k': 'toi,vat', 'v': 200, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('f', 'Terminal 21 (khu ẩm thực Pier 21)', 'Terminal 21 Asok', 'Trung tâm thương mại theo chủ đề, khu ẩm thực giá rẻ', {'k': 'trua,toi,cafe', 'v': 100, 't': 'sp', 'io': 'i', 'h': '10:00–22:00'}),
        ('f', 'Khu cổ Talat Noi', 'Talat Noi', 'Ngõ cổ ven sông, tranh tường và quán cà phê trong nhà cũ', {'k': 'cafe', 'v': 90, 't': 'cph', 'io': 'm'}),
        ('c', 'Siam Paragon', 'Siam Paragon', 'Trung tâm mua sắm lớn, thủy cung và khu ăn uống', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'pr', 'io': 'i', 'ev': 'all', 'h': '10:00–22:00'}),
        ('s', 'Chùa Saket – Núi Vàng', 'Wat Saket', 'Chùa trên đồi nhân tạo, 344 bậc lên ngắm toàn cảnh phố cổ', {'price': '~100 THB', 'v': 80, 'd': 75, 't': 'hp', 'io': 'o', 'ss': 1, 'f': 'o'}),
        ('s', 'Chùa Cẩm Thạch (Wat Benchamabophit)', 'Wat Benchamabophit', 'Ngôi chùa ốp đá cẩm thạch Ý, kiến trúc Thái tinh tế', {'price': '~50 THB', 'v': 40, 'd': 45, 't': 'hp', 'io': 'm'}),
        ('s', 'Chùa Suthat và Xích đu khổng lồ', 'Wat Suthat', 'Chùa hoàng gia với tượng Phật đồng lớn và cột xích đu đỏ', {'price': '~100 THB', 'v': 80, 'd': 60, 't': 'h', 'io': 'm'}),
        ('s', 'Bảo tàng Quốc gia Bangkok', 'Bangkok National Museum', 'Bảo tàng lịch sử – nghệ thuật lớn nhất Thái Lan', {'price': '~200 THB', 'v': 160, 'd': 120, 't': 'h', 'io': 'i', 'cl': [1, 2], 'h': '9:00–16:00, nghỉ T2, T3'}),
        ('c', 'Công viên Lumphini', 'Lumphini Park', 'Lá phổi xanh giữa phố, hồ nước và kỳ đà', {'v': 0, 'd': 60, 't': 'nr', 'io': 'o', 'mo': 1}),
        ('s', 'Thủy cung Sea Life Bangkok', 'Sea Life Bangkok Ocean World', 'Thủy cung lớn trong Siam Paragon, hợp trẻ em', {'price': '~1.000 THB', 'v': 800, 'd': 120, 't': 'n', 'io': 'i'}),
        ('c', 'Tàu Chao Phraya Express', 'Chao Phraya Express Boat', 'Đi thuyền dọc sông ngắm chùa, cung điện với giá rẻ', {'price': '~16–30 THB', 'v': 25, 'd': 60, 't': 'p', 'io': 'o', 'ss': 1, 'll': [13.7186, 100.5143]}),
        ('s', 'Cố đô Ayutthaya', 'Ayutthaya Historical Park', 'Di sản UNESCO với tượng đầu Phật trong rễ cây, đi trong ngày', {'price': '~50 THB mỗi chùa', 'v': 250, 'd': 360, 't': 'hpk', 'io': 'o', 'trip': 1}),
        ('f', 'Chợ đường ray Maeklong', 'Mae Klong railway station', 'Chợ họp ngay trên đường ray, sạp thu lại khi tàu chạy qua', {'k': 'sang,trua', 'v': 100, 'd': 180, 't': 'sp', 'io': 'o', 'trip': 1}),
    ],
    'pattaya': [
        ('c', 'Bãi biển Pattaya', 'Pattaya Beach', 'Bãi biển trung tâm, dạo bộ và ngắm hoàng hôn', {'v': 0, 'd': 90, 't': 'br', 'io': 'o', 'ss': 1}),
        ('s', 'Công viên nước Ramayana', 'Ramayana Water Park', 'Công viên nước lớn, hợp gia đình có trẻ em', {'price': '~1.300 THB', 'v': 1000, 'd': 300, 't': 'r', 'io': 'o'}),
        ('s', 'Chùa Yansangwararam', 'Wat Yansangwararam', 'Quần thể chùa, hồ và vườn rộng, yên tĩnh', {'v': 0, 'd': 90, 't': 'hn', 'io': 'o'}),
        ('s', 'Mini Siam', 'Mini Siam', 'Mô hình thu nhỏ các công trình nổi tiếng Thái Lan và thế giới', {'price': '~400 THB', 'v': 300, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all'}),
        ('s', 'Thủy cung Underwater World', 'Underwater World Pattaya', 'Đường hầm kính dưới nước, hợp trẻ em', {'price': '~500 THB', 'v': 400, 'd': 90, 't': 'n', 'io': 'i', 'hide': 1}),
        ('f', 'Làng Naklua (hải sản)', 'Naklua', 'Khu hải sản và chợ cá địa phương phía bắc Pattaya', {'k': 'trua,toi', 'v': 300, 't': 's', 'io': 'm', 'hide': 1}),
        ('c', 'Art in Paradise', 'Art in Paradise', 'Bảo tàng tranh 3D chụp ảnh vui nhộn', {'price': '~400 THB', 'v': 300, 'd': 90, 't': 'p', 'io': 'i', 'hide': 1}),
    ],
    'phuket': [
        ('s', 'Bảo tàng Thai Hua', 'Thai Hua Museum', 'Bảo tàng lịch sử người Hoa Phuket trong tòa nhà cổ', {'price': '~200 THB', 'v': 160, 'd': 60, 't': 'h', 'io': 'i', 'hide': 1}),
        ('c', 'Bãi biển Karon', 'Karon Beach', 'Bãi cát dài, ít đông hơn Patong', {'v': 0, 'd': 120, 't': 'br', 'io': 'o', 'ss': 1}),
        ('s', 'Phuket FantaSea', 'Phuket FantaSea', 'Công viên văn hóa và show diễn lớn về đêm', {'price': '~1.800 THB', 'v': 1400, 'd': 180, 't': 'p', 'io': 'm', 'ev': 'all', 'eo': 1, 'cl': [4]}),
        ('s', 'Thủy cung Phuket', 'Phuket Aquarium', 'Thủy cung nhỏ ở mũi Panwa, hợp trẻ em', {'price': '~180 THB', 'v': 140, 'd': 75, 't': 'n', 'io': 'i', 'hide': 1}),
        ('c', 'Bãi biển Kamala', 'Kamala Beach', 'Bãi biển yên bình, nhiều resort', {'v': 0, 'd': 120, 't': 'br', 'io': 'o', 'ss': 1}),
        ('f', 'Rawai (chợ hải sản)', 'Rawai', 'Chợ hải sản: mua tại sạp rồi nhờ quán nấu', {'k': 'trua,toi', 'v': 400, 't': 's', 'io': 'm'}),
        ('s', 'Đền Jui Tui', 'Jui Tui Shrine', 'Đền Đạo giáo nổi tiếng với lễ hội ăn chay', {'v': 0, 'd': 30, 't': 'h', 'io': 'm', 'hide': 1}),
        ('c', 'Đồi Khao Rang', 'Khao Rang', 'Đồi ngắm toàn cảnh thị trấn Phuket, quán ăn trên đồi', {'k': 'check,cafe', 'v': 0, 'd': 60, 't': 'pc', 'io': 'o', 'ss': 1, 'hide': 1}),
    ],
    'chiangmai': [
        ('f', 'Chợ Warorot', 'Warorot Market', 'Chợ lâu đời: xúc xích sai ua, đồ khô, trái cây', {'k': 'sang,trua,vat', 'v': 100, 't': 's', 'io': 'm'}),
        ('f', 'Phố đi bộ Chủ nhật', 'Sunday Walking Street', 'Chợ đêm Chủ nhật trên đường Ratchadamnoen, ăn vặt rẻ', {'k': 'toi,vat', 'v': 120, 't': 'sp', 'io': 'o', 'ev': 'weekend', 'eo': 1, 'cl': [1, 2, 3, 4, 5, 6], 'll': [18.788, 98.988]}),
        ('f', 'Chợ đêm thứ Bảy Wualai', 'Wualai Road', 'Chợ đêm thứ Bảy phố thợ bạc, ăn vặt và đồ bạc', {'k': 'toi,vat', 'v': 120, 't': 'sp', 'io': 'o', 'ev': 'weekend', 'eo': 1, 'cl': [0, 1, 2, 3, 4, 5], 'hide': 1}),
        ('f', 'Chợ Chiang Mai Gate', 'Chiang Mai Gate', 'Chợ ăn uống bình dân sáng và tối ở cổng thành phía nam', {'k': 'sang,toi,vat', 'v': 80, 't': 's', 'io': 'o', 'ev': 'all', 'll': [18.7811, 98.9885]}),
        ('s', 'Chùa Suan Dok', 'Wat Suan Dok', 'Chùa với hàng tháp trắng hoàng gia, đẹp lúc chiều muộn', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'ss': 1}),
        ('s', 'Chùa Umong', 'Wat Umong', 'Chùa trong rừng với đường hầm cổ', {'v': 0, 'd': 60, 't': 'hn', 'io': 'm'}),
        ('s', 'Chùa Chiang Man', 'Wat Chiang Man', 'Ngôi chùa cổ nhất Chiang Mai, tháp voi', {'v': 0, 'd': 30, 't': 'h', 'io': 'o'}),
        ('c', 'Đại học Chiang Mai – hồ Ang Kaew', 'Chiang Mai University', 'Khuôn viên xanh, hồ ngắm núi Doi Suthep', {'v': 0, 'd': 60, 't': 'nr', 'io': 'o', 'ss': 1}),
        ('s', 'Tượng đài Ba Vua & Bảo tàng thành phố', 'Three Kings Monument', 'Bảo tàng lịch sử Chiang Mai trong tòa nhà thuộc địa', {'price': '~90 THB', 'v': 70, 'd': 75, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('c', 'Làng Bo Sang', 'Bo Sang', 'Làng nghề làm ô giấy vẽ tay', {'v': 0, 'd': 90, 't': 'hp', 'io': 'm'}),
    ],
    'beijing': [
        ('s', 'Cảnh Sơn', 'Jingshan Park', 'Đồi nhìn xuống toàn bộ mái vàng Cố Cung', {'price': '~2 CNY', 'v': 10, 'd': 60, 't': 'hp', 'io': 'o', 'ss': 1}),
        ('s', 'Bắc Hải', 'Beihai Park', 'Vườn hoàng gia với tháp Trắng và hồ', {'price': '~10 CNY', 'v': 40, 'd': 90, 't': 'hnr', 'io': 'o'}),
        ('s', 'Văn Miếu – Quốc Tử Giám', 'Beijing Confucius Temple', 'Nơi thờ Khổng Tử và trường học hoàng gia xưa', {'price': '~30 CNY', 'v': 110, 'd': 75, 't': 'h', 'io': 'm', 'cl': [1]}),
        ('s', 'Bảo tàng Quốc gia Trung Quốc', 'National Museum of China', 'Bảo tàng lớn, miễn phí, cần đặt trước bằng hộ chiếu', {'v': 0, 'd': 150, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('c', '798 – Khu nghệ thuật', '798 Art Zone', 'Nhà máy cũ thành phòng tranh, quán cà phê', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'pc', 'io': 'm'}),
        ('f', 'Tiền Môn – phố Đại Sách Lan', 'Qianmen', 'Phố đi bộ cổ với tiệm vịt quay, bánh truyền thống', {'k': 'trua,toi,vat', 'v': 300, 't': 'sh', 'io': 'o', 'ev': 'all'}),
        ('f', 'Phố Quỷ Nhai', 'Gui Street', 'Phố ẩm thực mở khuya: tôm hùm đất, lẩu', {'k': 'toi', 'v': 350, 't': 's', 'io': 'm', 'ev': 'all', 'eo': 1}),
        ('f', 'Tam Lý Đồn', 'Sanlitun', 'Khu ăn chơi hiện đại, quán cà phê và nhà hàng', {'k': 'cafe,toi', 'v': 200, 't': 'cs', 'io': 'm', 'ev': 'all'}),
        ('s', 'Công viên Olympic', 'Beijing Olympic Park', 'Tổ Chim, Khối Nước, tháp Olympic', {'v': 0, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all'}),
        ('s', 'Viên Minh Viên', 'Old Summer Palace', 'Phế tích cung điện kiểu châu Âu trong vườn rộng', {'price': '~25 CNY', 'v': 90, 'd': 120, 't': 'hn', 'io': 'o'}),
        ('s', 'Lăng mộ nhà Minh', 'Ming tombs', 'Thập Tam Lăng, hay đi kết hợp Trường Thành', {'price': '~45–60 CNY', 'v': 200, 'd': 180, 't': 'h', 'io': 'o', 'trip': 1, 'll': [40.295, 116.23]}),
    ],
    'shanghai': [
        ('c', 'Phố Đông – Lục Gia Chủy', 'Lujiazui', 'Khu nhà chọc trời, cầu đi bộ ngắm phố', {'v': 0, 'd': 60, 't': 'p', 'io': 'o', 'ev': 'all', 'll': [31.2397, 121.4998]}),
        ('s', 'Chùa Phật Ngọc', 'Jade Buddha Temple', 'Chùa có tượng Phật ngọc trắng từ Miến Điện', {'price': '~20 CNY', 'v': 80, 'd': 60, 't': 'h', 'io': 'm'}),
        ('s', 'Chùa Tĩnh An', 'Jing\'an Temple', 'Ngôi chùa vàng giữa khu thương mại hiện đại', {'price': '~50 CNY', 'v': 180, 'd': 45, 't': 'hp', 'io': 'm'}),
        ('s', 'Bảo tàng Thượng Hải', 'Shanghai Museum', 'Đồ đồng, gốm sứ, thư pháp Trung Hoa, miễn phí', {'v': 0, 'd': 120, 't': 'h', 'io': 'i', 'll': [31.2283, 121.4753]}),
        ('c', 'Phố Vũ Khang', 'Wukang Road', 'Con phố hàng cây và biệt thự kiểu Pháp, quán cà phê', {'k': 'check,cafe', 'v': 0, 'd': 75, 't': 'pch', 'io': 'o'}),
        ('f', 'Phố Thất Bảo', 'Qibao', 'Cổ trấn trong thành phố, ăn vặt bánh trôi, thịt kho', {'k': 'trua,vat', 'v': 150, 'd': 120, 't': 'sh', 'io': 'o'}),
        ('f', 'Phố ẩm thực Hoàng Hà', 'Huanghe Road', 'Phố tiểu long bao, bánh bao chiên sinh tiên', {'k': 'sang,trua,toi', 'v': 150, 't': 's', 'io': 'i', 'hide': 1}),
        ('s', 'Thủy cung Đại dương Thượng Hải', 'Shanghai Ocean Aquarium', 'Đường hầm kính dài, hợp trẻ em', {'price': '~160 CNY', 'v': 580, 'd': 120, 't': 'n', 'io': 'i'}),
        ('c', 'Du thuyền sông Hoàng Phố', 'Huangpu River', 'Du thuyền đêm ngắm Bến Thượng Hải và Phố Đông', {'price': '~100–150 CNY', 'v': 450, 'd': 60, 't': 'pk', 'io': 'o', 'ev': 'all', 'eo': 1}),
    ],
    'zhangjiajie': [
        ('c', 'Viên Gia Giới (núi Avatar)', 'Yuanjiajie', 'Cột đá Càn Khôn Trụ – "núi bay" trong phim Avatar', {'v': 0, 'd': 180, 't': 'npk', 'io': 'o', 'a': 'Trương Gia Giới', 'hide': 1}),
        ('c', 'Thiên Tử Sơn', 'Tianzi Mountain', 'Biển mây và rừng đá nhìn từ trên cao, có cáp treo', {'v': 270, 'd': 180, 't': 'np', 'io': 'o', 'a': 'Trương Gia Giới'}),
        ('c', 'Suối Kim Tiên', 'Golden Whip Stream', 'Đường đi bộ ven suối giữa rừng cột đá', {'v': 0, 'd': 150, 't': 'nr', 'io': 'o', 'a': 'Trương Gia Giới', 'hide': 1}),
        ('c', 'Hồ Bảo Phong', 'Baofeng Lake', 'Hồ nước xanh giữa núi, đi thuyền nghe hát dân ca', {'price': '~96 CNY', 'v': 350, 'd': 120, 't': 'nr', 'io': 'o', 'a': 'Trương Gia Giới'}),
        ('f', 'Phố Khê Bố', 'Xibu Street', 'Phố ăn đêm người Thổ Gia ở thành phố Trương Gia Giới', {'k': 'toi,vat', 'v': 150, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Trương Gia Giới', 'hide': 1}),
        ('s', 'Cầu Hồng Kiều (Phượng Hoàng)', 'Hong Bridge', 'Cầu có mái biểu tượng của cổ trấn', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'ev': 'all', 'a': 'Phượng Hoàng', 'hide': 1}),
        ('s', 'Nam Phương Trường Thành', 'Southern Great Wall', 'Tường thành cổ nhà Minh trên núi gần Phượng Hoàng', {'price': '~45 CNY', 'v': 160, 'd': 120, 't': 'hp', 'io': 'o', 'f': 'o', 'a': 'Phượng Hoàng'}),
    ],
    'yunnan': [
        ('c', 'Hồ Thúy Hồ (Côn Minh)', 'Green Lake Park', 'Hồ giữa phố, mùa đông có mòng biển bay về', {'v': 0, 'd': 75, 't': 'nr', 'io': 'o', 'a': 'Côn Minh', 'll': [25.051, 102.704]}),
        ('s', 'Tây Sơn – Long Môn', 'Western Hills (Kunming)', 'Đường đá treo vách núi nhìn xuống hồ Điền Trì', {'price': '~30 CNY', 'v': 110, 'd': 180, 't': 'np', 'io': 'o', 'f': 'o', 'a': 'Côn Minh', 'hide': 1}),
        ('f', 'Phố Nam Bình', 'Nanping Street', 'Phố đi bộ trung tâm Côn Minh, mì qua cầu, bánh hoa hồng', {'k': 'trua,toi,vat', 'v': 120, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Côn Minh', 'hide': 1}),
        ('s', 'Chợ hoa Đẩu Nam', 'Dounan Flower Market', 'Chợ hoa lớn nhất châu Á, họp đêm', {'v': 0, 'd': 90, 't': 'p', 'io': 'm', 'ev': 'all', 'a': 'Côn Minh', 'hide': 1}),
        ('s', 'Thương Sơn', 'Cang Mountain', 'Núi sau cổ thành Đại Lý, cáp treo ngắm hồ Nhĩ Hải', {'price': '~100–250 CNY', 'v': 600, 'd': 240, 't': 'nm', 'io': 'o', 'f': 'o', 'a': 'Đại Lý'}),
        ('c', 'Làng Hỷ Châu', 'Xizhou', 'Làng cổ người Bạch, bánh nướng Hỷ Châu', {'k': 'check,trua,vat', 'v': 50, 'd': 120, 't': 'hps', 'io': 'o', 'a': 'Đại Lý', 'll': [25.857, 100.13]}),
        ('c', 'Song Lang', 'Shuanglang', 'Thị trấn ven hồ Nhĩ Hải, ngắm hoàng hôn', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'nprc', 'io': 'o', 'ss': 1, 'a': 'Đại Lý', 'hide': 1}),
        ('c', 'Hồ Lam Nguyệt Cốc', 'Blue Moon Valley', 'Thung lũng hồ xanh ngọc dưới núi tuyết Ngọc Long', {'v': 0, 'd': 120, 't': 'np', 'io': 'o', 'a': 'Lệ Giang', 'hide': 1}),
        ('s', 'Hổ Khiêu Hạp', 'Tiger Leaping Gorge', 'Hẻm núi sâu bậc nhất thế giới trên sông Kim Sa', {'price': '~45 CNY', 'v': 160, 'd': 300, 't': 'n', 'io': 'o', 'f': 'x', 'trip': 1, 'a': 'Lệ Giang'}),
        ('c', 'Núi Sư Tử – lầu Vạn Cổ', 'Lion Hill (Lijiang)', 'Lầu gỗ trên đồi ngắm toàn phố cổ Lệ Giang', {'price': '~35 CNY', 'v': 130, 'd': 60, 't': 'hp', 'io': 'o', 'ss': 1, 'a': 'Lệ Giang', 'hide': 1}),
        ('s', 'Chùa Viên Thông (Côn Minh)', 'Yuantong Temple', 'Ngôi chùa cổ hơn 1.200 năm giữa trung tâm Côn Minh', {'price': '~6 CNY', 'v': 25, 'd': 60, 't': 'h', 'io': 'o', 'a': 'Côn Minh'}),
        ('s', 'Làng dân tộc Vân Nam', 'Yunnan Nationalities Village', 'Làng văn hóa 25 dân tộc bên hồ Điền Trì, múa hát dân gian', {'price': '~90 CNY', 'v': 330, 'd': 180, 't': 'hp', 'io': 'o', 'a': 'Côn Minh'}),
    ],
    'guilin': [
        ('c', 'Hai hồ bốn sông (Nhật Nguyệt Song Tháp)', 'Sun and Moon Pagodas', 'Hai ngọn tháp trên hồ Sam, đẹp lung linh về đêm', {'v': 0, 'd': 60, 't': 'pk', 'io': 'o', 'ev': 'all', 'a': 'Quế Lâm'}),
        ('s', 'Núi Điệp Thái', 'Fubo Mountain', 'Đồi đá vôi ven sông Ly, ngắm toàn cảnh Quế Lâm', {'price': '~30 CNY', 'v': 110, 'd': 75, 't': 'np', 'io': 'o', 'f': 'o', 'a': 'Quế Lâm'}),
        ('s', 'Thất Tinh Nham', 'Seven Star Park', 'Công viên núi đá, hang động và vườn thú nhỏ', {'price': '~55 CNY', 'v': 200, 'd': 120, 't': 'n', 'io': 'm', 'a': 'Quế Lâm', 'll': [25.277, 110.311]}),
        ('f', 'Phố Chính Dương', 'Zhengyang Pedestrian Street', 'Phố đi bộ trung tâm, bún Quế Lâm', {'k': 'sang,trua,toi,vat', 'v': 80, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Quế Lâm', 'hide': 1}),
        ('c', 'Đồi Mặt Trăng (Nguyệt Lượng Sơn)', 'Moon Hill', 'Núi đá có lỗ tròn hình trăng, leo ngắm đồng quê', {'price': '~15 CNY', 'v': 55, 'd': 90, 't': 'np', 'io': 'o', 'f': 'o', 'a': 'Dương Sóc'}),
        ('c', 'Núi Tương Công', 'Xianggong Hill', 'Điểm ngắm sông Ly lúc bình minh nổi tiếng', {'v': 110, 'd': 90, 't': 'np', 'io': 'o', 'mo': 1, 'a': 'Dương Sóc', 'hide': 1}),
        ('s', 'Ấn tượng Lưu Tam Tỷ', 'Impression, Sanjie Liu', 'Show thực cảnh trên sông Ly của Trương Nghệ Mưu', {'price': '~220 CNY', 'v': 800, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1, 'a': 'Dương Sóc'}),
        ('c', 'Hưng Bình cổ trấn', 'Xingping', 'Làng cổ bên sông Ly, cảnh tờ tiền 20 tệ', {'v': 0, 'd': 150, 't': 'hnp', 'io': 'o', 'a': 'Dương Sóc', 'll': [24.930, 110.518]}),
    ],
    'seoul': [
        ('c', 'Suối Cheonggyecheon', 'Cheonggyecheon', 'Dòng suối giữa phố, dạo bộ buổi tối', {'v': 0, 'd': 45, 't': 'pr', 'io': 'o', 'ev': 'all'}),
        ('c', 'Phố Insadong', 'Insadong', 'Phố đồ thủ công, quán trà truyền thống', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'hcp', 'io': 'o'}),
        ('s', 'Bảo tàng Quốc gia Hàn Quốc', 'National Museum of Korea', 'Bảo tàng lớn, miễn phí, nhiều cổ vật', {'v': 0, 'd': 150, 't': 'h', 'io': 'i'}),
        ('s', 'Cung Deoksugung', 'Deoksugung', 'Cung điện pha kiến trúc Tây, lễ đổi gác', {'price': '1.000 KRW', 'v': 20, 'd': 60, 't': 'hp', 'io': 'o', 'cl': [1]}),
        ('f', 'Chợ Namdaemun', 'Namdaemun Market', 'Chợ truyền thống lớn nhất, mì dao, bánh hotteok', {'k': 'sang,trua,vat', 'v': 150, 't': 's', 'io': 'm', 'cl': [0]}),
        ('f', 'Phố Ikseon-dong', 'Ikseon-dong', 'Ngõ hanok cải tạo thành quán cà phê, nhà hàng', {'k': 'cafe,trua', 'v': 200, 't': 'cp', 'io': 'm', 'll': [37.5745, 126.99]}),
        ('c', 'Công viên sông Hàn Yeouido', 'Yeouido Hangang Park', 'Ăn gà rán, mì gói bên sông Hàn lúc hoàng hôn', {'v': 0, 'd': 90, 't': 'rp', 'io': 'o', 'ss': 1, 'ev': 'all', 'll': [37.5284, 126.934]}),
        ('f', 'Phố Gangnam – Garosu-gil', 'Garosu-gil', 'Con đường hàng cây với cửa hàng và quán cà phê', {'k': 'cafe,toi', 'v': 200, 't': 'cp', 'io': 'o', 'll': [37.5205, 127.0229]}),
        ('c', 'COEX & thư viện Starfield', 'COEX Mall', 'Thư viện sách khổng lồ và thủy cung trong trung tâm thương mại', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'p', 'io': 'i', 'ev': 'all'}),
        ('s', 'Chùa Jogyesa', 'Jogyesa', 'Ngôi chùa trung tâm của Phật giáo Hàn Quốc', {'v': 0, 'd': 30, 't': 'h', 'io': 'o'}),
        ('f', 'Chợ đêm Mangwon', 'Mangwon Market', 'Chợ truyền thống nhiều món chiên, gà cay', {'k': 'trua,toi,vat', 'v': 150, 't': 's', 'io': 'm', 'll': [37.5559, 126.9062]}),
    ],
    'busan': [
        ('f', 'Chợ BIFF và Gukje', 'Gukje Market', 'Chợ lớn và phố ăn vặt hotteok hạt, bánh cá', {'k': 'trua,vat', 'v': 120, 't': 's', 'io': 'm'}),
        ('c', 'Làng Huinnyeoul', 'Huinnyeoul Culture Village', 'Làng nhà trắng ven biển như Santorini', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'bpc', 'io': 'o', 'ss': 1, 'll': [35.0785, 129.0445]}),
        ('c', 'Haeundae Blueline Park', 'Haeundae Blueline Park', 'Tàu điện ven biển và cabin trên cao', {'price': '~7.000–35.000 KRW', 'v': 300, 'd': 90, 't': 'bp', 'io': 'o', 'hide': 1}),
        ('s', 'Thủy cung Sea Life Busan', 'Sea Life Busan Aquarium', 'Thủy cung ngay bãi biển Haeundae', {'price': '~30.000 KRW', 'v': 550, 'd': 90, 't': 'n', 'io': 'i'}),
        ('s', 'Chùa Beomeosa', 'Beomeosa', 'Chùa cổ trên núi Geumjeong', {'v': 0, 'd': 90, 't': 'hn', 'io': 'o'}),
        ('f', 'Chợ Haeundae', 'Haeundae Market', 'Chợ nhỏ bán chả cá, bánh gạo, hải sản', {'k': 'sang,trua,toi,vat', 'v': 150, 't': 's', 'io': 'm'}),
        ('c', 'Cầu Gwangan', 'Gwangan Bridge', 'Cây cầu đổi màu về đêm, ngắm từ bãi Gwangalli', {'v': 0, 'd': 45, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('s', 'Shinsegae Centum City', 'Shinsegae Centum City', 'Trung tâm thương mại lớn nhất thế giới, spa', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'r', 'io': 'i', 'll': [35.169, 129.1295]}),
    ],
    'jeju': [
        ('c', 'Bãi biển Hamdeok', 'Hamdeok Beach', 'Biển xanh ngọc, cát trắng gần thành phố Jeju', {'v': 0, 'd': 90, 't': 'br', 'io': 'o', 'ss': 1, 'll': [33.5433, 126.6697]}),
        ('c', 'Bờ biển Jusangjeolli', 'Jusangjeolli Cliff', 'Vách cột đá bazan lục giác bên biển', {'price': '~2.000 KRW', 'v': 40, 'd': 45, 't': 'np', 'io': 'o', 'll': [33.2378, 126.425]}),
        ('c', 'Núi Sanbangsan', 'Sanbangsan', 'Núi đá có chùa trong hang, nhìn ra biển', {'v': 40, 'd': 75, 't': 'nh', 'io': 'o', 'f': 'o'}),
        ('s', 'Bảo tàng gấu Teddy', 'Teddy Bear Museum', 'Bảo tàng gấu bông, hợp trẻ em', {'price': '~12.000 KRW', 'v': 220, 'd': 75, 't': 'p', 'io': 'i', 'll': [33.2507, 126.4129]}),
        ('c', 'Đồi trà O’sulloc', "O'sulloc Tea Museum", 'Bảo tàng và đồi trà xanh, kem trà nổi tiếng', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'cnp', 'io': 'm', 'll': [33.3058, 126.2895]}),
        ('c', 'Bãi biển Woljeongri', 'Woljeong-ri', 'Bãi biển nhiều quán cà phê view biển', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'bcr', 'io': 'o', 'll': [33.5563, 126.7959]}),
        ('f', 'Chợ Olle Seogwipo', 'Seogwipo', 'Chợ ẩm thực ở Seogwipo: cá hố, quýt, thịt lợn đen', {'k': 'trua,toi,vat', 'v': 250, 't': 's', 'io': 'm'}),
        ('s', 'Làng dân gian Seongeup', 'Seongeup Folk Village', 'Làng cổ với nhà đá mái tranh và tượng Dol hareubang', {'v': 0, 'd': 75, 't': 'h', 'io': 'o'}),
    ],
    'tokyo': [
        ('c', 'Ngõ Nakamise (Asakusa)', 'Nakamise-dōri', 'Phố bánh truyền thống dẫn vào chùa Sensō-ji', {'k': 'check,vat,sang', 'v': 150, 'd': 45, 't': 'sh', 'io': 'o', 'll': [35.7117, 139.7966]}),
        ('s', 'Hoàng cung Tokyo – vườn Đông', 'East Gardens of the Imperial Palace', 'Vườn trong khuôn viên Hoàng cung, miễn phí', {'v': 0, 'd': 90, 't': 'hn', 'io': 'o', 'cl': [1, 5], 'll': [35.6852, 139.7556]}),
        ('c', 'Phố Takeshita (Harajuku)', 'Takeshita Street', 'Phố thời trang, bánh crepe cầu vồng', {'k': 'check,vat,cafe', 'v': 150, 'd': 75, 't': 'sp', 'io': 'o'}),
        ('c', 'Shibuya Sky', 'Shibuya Scramble Square', 'Đài quan sát ngoài trời nhìn xuống ngã tư Shibuya', {'price': '~2.500 JPY', 'v': 430, 'd': 75, 't': 'p', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('f', 'Omoide Yokocho (Shinjuku)', 'Omoide Yokochō', 'Ngõ nhỏ quán yakitori nhỏ xíu, không khí Showa', {'k': 'toi', 'v': 450, 't': 's', 'io': 'm', 'ev': 'all', 'eo': 1, 'll': [35.6929, 139.6996]}),
        ('f', 'Ameya-Yokochō (Ueno)', 'Ameya-Yokochō', 'Chợ dưới đường tàu: hải sản, trái cây, đồ ăn vặt', {'k': 'trua,vat', 'v': 250, 't': 's', 'io': 'o', 'll': [35.7101, 139.7745]}),
        ('s', 'Bảo tàng Quốc gia Tokyo', 'Tokyo National Museum', 'Bảo tàng lâu đời nhất Nhật Bản ở công viên Ueno', {'price': '~1.000 JPY', 'v': 170, 'd': 120, 't': 'h', 'io': 'i', 'cl': [1]}),
        ('s', 'teamLab Planets', 'TeamLab Planets', 'Bảo tàng nghệ thuật ánh sáng, lội nước', {'price': '~3.800 JPY', 'v': 650, 'd': 120, 't': 'p', 'io': 'i', 'll': [35.6491, 139.7898]}),
        ('c', 'Odaiba', 'Odaiba', 'Đảo nhân tạo: tượng Gundam, cầu Cầu Vồng, biển nhân tạo', {'v': 0, 'd': 150, 't': 'pr', 'io': 'm', 'ss': 1, 'ev': 'all'}),
        ('f', 'Ginza', 'Ginza', 'Phố mua sắm sang trọng, tầng hầm thực phẩm depachika', {'k': 'trua,cafe', 'v': 350, 't': 'sc', 'io': 'i'}),
        ('c', 'Shinjuku – Kabukichō', 'Kabukichō', 'Khu đèn neon, đầu Godzilla, quán ăn khuya', {'k': 'check,toi', 'v': 400, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('s', 'Kamakura – Đại Phật', 'Kōtoku-in', 'Tượng Đại Phật đồng ngoài trời, đi trong ngày', {'price': '~300 JPY', 'v': 300, 'd': 300, 't': 'hk', 'io': 'o', 'trip': 1}),
        ('s', 'Nikkō', 'Nikkō Tōshō-gū', 'Đền Tōshō-gū chạm khắc dát vàng giữa rừng tuyết tùng', {'price': '~1.600 JPY', 'v': 400, 'd': 360, 't': 'hn', 'io': 'o', 'trip': 1}),
    ],
    'osaka': [
        ('f', 'Phố Shinsaibashi', 'Shinsaibashi-suji', 'Phố mua sắm có mái che, nối với Dōtonbori', {'k': 'trua,cafe,vat', 'v': 250, 't': 'sp', 'io': 'i', 'a': 'Osaka', 'll': [34.6748, 135.5013]}),
        ('c', 'Tháp Tsūtenkaku', 'Tsūtenkaku', 'Tháp biểu tượng khu Shinsekai', {'price': '~1.000 JPY', 'v': 170, 'd': 45, 't': 'p', 'io': 'm', 'ev': 'all', 'a': 'Osaka'}),
        ('s', 'Thủy cung Kaiyukan', 'Osaka Aquarium Kaiyukan', 'Một trong những thủy cung lớn nhất thế giới, có cá mập voi', {'price': '~2.700 JPY', 'v': 460, 'd': 150, 't': 'n', 'io': 'i', 'a': 'Osaka'}),
        ('s', 'Đền Sumiyoshi Taisha', 'Sumiyoshi-taisha', 'Đền cổ với cây cầu cong đỏ', {'v': 0, 'd': 60, 't': 'h', 'io': 'o', 'a': 'Osaka'}),
        ('c', 'Abeno Harukas', 'Abeno Harukas', 'Tòa nhà cao nhất Osaka, đài quan sát tầng 60', {'price': '~2.000 JPY', 'v': 340, 'd': 75, 't': 'p', 'io': 'i', 'ss': 1, 'ev': 'all', 'a': 'Osaka'}),
        ('f', 'Phố Ura-Namba', 'Namba', 'Ngõ quán nhậu nhỏ, okonomiyaki, kushikatsu', {'k': 'toi,vat', 'v': 350, 't': 's', 'io': 'm', 'ev': 'all', 'a': 'Osaka'}),
        ('s', 'Đền Kasuga Taisha (Nara)', 'Kasuga-taisha', 'Đền với hàng nghìn đèn lồng đá giữa rừng', {'price': '~700 JPY', 'v': 120, 'd': 75, 't': 'hn', 'io': 'o', 'a': 'Nara'}),
        ('f', 'Phố Naramachi', 'Naramachi', 'Phố nhà gỗ cổ, quán ăn mochi giã', {'k': 'trua,cafe,vat', 'v': 250, 't': 'sch', 'io': 'o', 'a': 'Nara', 'll': [34.6782, 135.8297]}),
        ('s', 'Chùa Kōfuku-ji (Nara)', 'Kōfuku-ji', 'Tháp gỗ năm tầng cổ kính', {'v': 120, 'd': 45, 't': 'h', 'io': 'o', 'a': 'Nara'}),
    ],
    'kyoto': [
        ('c', 'Dốc Ninenzaka – Sannenzaka', 'Sannenzaka', 'Phố dốc cổ dẫn lên Kiyomizu-dera, quán trà, đồ gốm', {'k': 'check,cafe,vat', 'v': 100, 'd': 75, 't': 'hpc', 'io': 'o', 'll': [34.9966, 135.781]}),
        ('s', 'Lâu đài Nijō', 'Nijō Castle', 'Lâu đài của tướng quân Tokugawa, sàn nhà "chim họa mi"', {'price': '~1.300 JPY', 'v': 220, 'd': 90, 't': 'hk', 'io': 'm', 'cl': [2]}),
        ('s', 'Chùa Ryōan-ji', 'Ryōan-ji', 'Vườn đá thiền nổi tiếng nhất Nhật Bản', {'price': '~600 JPY', 'v': 100, 'd': 60, 't': 'hr', 'io': 'o'}),
        ('s', 'Chùa Sanjūsangen-dō', 'Sanjūsangen-dō', '1.001 tượng Quan Âm trong điện gỗ dài', {'price': '~600 JPY', 'v': 100, 'd': 60, 't': 'h', 'io': 'i'}),
        ('s', 'Đền Yasaka', 'Yasaka Shrine', 'Đền thần đạo ở đầu phố Gion, đèn lồng về đêm', {'v': 0, 'd': 30, 't': 'hp', 'io': 'o', 'ev': 'all'}),
        ('f', 'Phố Pontochō', 'Pontochō', 'Ngõ hẹp ven sông Kamo với nhà hàng truyền thống', {'k': 'toi', 'v': 600, 't': 'sh', 'io': 'i', 'ev': 'all', 'eo': 1}),
        ('c', 'Bờ sông Kamo', 'Kamo River', 'Ngồi bờ sông ngắm hoàng hôn như người Kyoto', {'v': 0, 'd': 45, 't': 'rp', 'io': 'o', 'ss': 1}),
        ('s', 'Chùa Tenryū-ji', 'Tenryū-ji', 'Chùa thiền di sản UNESCO cạnh rừng tre Arashiyama', {'price': '~500 JPY', 'v': 85, 'd': 60, 't': 'hn', 'io': 'o'}),
        ('f', 'Tháp Kyoto – ga Kyoto', 'Kyoto Station', 'Nhà ga kiến trúc hiện đại, phố ramen trên tầng 10', {'k': 'sang,trua,toi', 'v': 250, 't': 's', 'io': 'i'}),
        ('s', 'Chùa Byōdō-in (Uji)', 'Byōdō-in', 'Điện Phượng Hoàng trên đồng 10 yên, trà xanh Uji', {'price': '~700 JPY', 'v': 120, 'd': 180, 't': 'hc', 'io': 'o', 'trip': 1}),
    ],
    'singapore': [
        ('c', 'Clarke Quay', 'Clarke Quay', 'Bến sông với nhà hàng, quán bar, du thuyền đêm', {'k': 'check,toi', 'v': 400, 'd': 90, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('s', 'Bảo tàng Quốc gia Singapore', 'National Museum of Singapore', 'Bảo tàng lịch sử lâu đời nhất Singapore', {'price': '~25 SGD', 'v': 500, 'd': 120, 't': 'h', 'io': 'i'}),
        ('c', 'Vườn bách thảo Singapore', 'Singapore Botanic Gardens', 'Di sản UNESCO, vườn lan quốc gia', {'v': 0, 'd': 120, 't': 'nr', 'io': 'o', 'mo': 1}),
        ('f', 'Phố Kampong Glam – Haji Lane', 'Kampong Glam', 'Khu Mã Lai – Ả Rập, tranh tường, quán cà phê', {'k': 'cafe,trua', 'v': 200, 't': 'cph', 'io': 'o', 'll': [1.3019, 103.859]}),
        ('f', 'Newton Food Centre', 'Newton Food Centre', 'Khu hawker nổi tiếng với cua sốt ớt, sa tế', {'k': 'toi,vat', 'v': 300, 't': 's', 'io': 'm', 'ev': 'all'}),
        ('f', 'Tiong Bahru', 'Tiong Bahru', 'Khu nhà cổ với chợ, tiệm bánh và cà phê', {'k': 'sang,cafe', 'v': 150, 't': 'cs', 'io': 'm', 'll': [1.2851, 103.8325]}),
        ('s', 'Night Safari', 'Night Safari, Singapore', 'Vườn thú đêm đầu tiên trên thế giới', {'price': '~55 SGD', 'v': 1100, 'd': 180, 't': 'n', 'io': 'o', 'ev': 'all', 'eo': 1}),
        ('c', 'Orchard Road', 'Orchard Road', 'Đại lộ mua sắm với hàng chục trung tâm thương mại', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'p', 'io': 'i', 'ev': 'all'}),
        ('s', 'Đền Răng Phật', 'Buddha Tooth Relic Temple and Museum', 'Ngôi chùa lớn ở Chinatown', {'v': 0, 'd': 45, 't': 'h', 'io': 'i', 'll': [1.2814, 103.8442]}),
        ('c', 'Bến Helix và vòng quay Singapore Flyer', 'Singapore Flyer', 'Vòng quay ngắm vịnh Marina', {'price': '~40 SGD', 'v': 800, 'd': 60, 't': 'p', 'io': 'i', 'ss': 1, 'ev': 'all'}),
    ],
    'kualalumpur': [
        ('c', 'Công viên KLCC', 'KLCC Park', 'Công viên dưới chân tháp đôi, show nhạc nước buổi tối', {'v': 0, 'd': 60, 't': 'pr', 'io': 'o', 'ev': 'all', 'll': [3.1543, 101.7146]}),
        ('f', 'Suria KLCC', 'Suria KLCC', 'Trung tâm thương mại dưới tháp đôi, khu ẩm thực', {'k': 'trua,cafe', 'v': 150, 't': 's', 'io': 'i'}),
        ('s', 'Bảo tàng Nghệ thuật Hồi giáo', 'Islamic Arts Museum Malaysia', 'Bảo tàng nghệ thuật Hồi giáo lớn ở Đông Nam Á', {'price': '~20 MYR', 'v': 120, 'd': 90, 't': 'h', 'io': 'i'}),
        ('s', 'Nhà thờ Hồi giáo Quốc gia', 'National Mosque of Malaysia', 'Kiến trúc hiện đại, có áo choàng cho khách', {'v': 0, 'd': 45, 't': 'h', 'io': 'm'}),
        ('f', 'Phố Bukit Bintang', 'Bukit Bintang', 'Khu mua sắm và ăn uống sôi động nhất KL', {'k': 'toi,cafe,vat', 'v': 150, 't': 's', 'io': 'o', 'ev': 'all'}),
        ('f', 'Chợ Trung tâm (Central Market)', 'Central Market, Kuala Lumpur', 'Chợ đồ thủ công, khu ẩm thực địa phương', {'k': 'trua,vat', 'v': 100, 't': 'sh', 'io': 'i'}),
        ('c', 'Kampung Baru', 'Kampung Baru', 'Làng Mã Lai truyền thống giữa phố, nasi lemak', {'k': 'check,sang,toi', 'v': 80, 'd': 75, 't': 'hs', 'io': 'o', 'll': [3.164, 101.704]}),
        ('s', 'Công viên chim KL', 'KL Bird Park', 'Vườn chim bay tự do, hợp trẻ em', {'price': '~90 MYR', 'v': 520, 'd': 120, 't': 'n', 'io': 'o'}),
        ('c', 'Cầu Saloma', 'Saloma Link', 'Cây cầu đi bộ đổi màu, ngắm tháp đôi về đêm', {'v': 0, 'd': 30, 't': 'p', 'io': 'o', 'ev': 'all', 'eo': 1}),
    ],
    'penang': [
        ('f', 'Phố Chulia – Lebuh Chulia', 'Chulia Street', 'Phố hawker đêm: wanton mee, char kway teow', {'k': 'toi,vat', 'v': 100, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1, 'll': [5.418, 100.336]}),
        ('f', 'Phố Kimberley', 'Lebuh Kimberley', 'Phố ăn đêm nổi tiếng với kway chap, cendol', {'k': 'toi,vat', 'v': 80, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1, 'hide': 1}),
        ('f', 'Chợ New Lane', 'New Lane Hawker Centre', 'Khu hawker địa phương, giá rẻ', {'k': 'toi,vat', 'v': 100, 't': 's', 'io': 'o', 'ev': 'all', 'hide': 1}),
        ('c', 'Cầu tàu dòng họ (Clan Jetties)', 'Chew Jetty', 'Làng nhà sàn gỗ trên biển của người Hoa', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'ss': 1, 'll': [5.413, 100.342]}),
        ('s', 'Pháo đài Cornwallis', 'Fort Cornwallis', 'Pháo đài Anh cổ nhất Malaysia', {'price': '~20 MYR', 'v': 120, 'd': 45, 't': 'h', 'io': 'o'}),
        ('s', 'Bảo tàng Pinang Peranakan', 'Pinang Peranakan Mansion', 'Dinh thự xanh lá trưng bày văn hóa Peranakan', {'price': '~25 MYR', 'v': 150, 'd': 60, 't': 'h', 'io': 'i'}),
        ('c', 'Vườn quốc gia Penang', 'Penang National Park', 'Rừng nhiệt đới, bãi Rùa và hải đăng Muka Head', {'v': 0, 'd': 240, 't': 'nb', 'io': 'o', 'f': 'o'}),
        ('f', 'Phố Little India Penang', 'Little India, Penang', 'Cà ri, roti canai, trà kéo teh tarik', {'k': 'sang,trua', 'v': 80, 't': 'sh', 'io': 'm'}),
    ],
    'taipei': [
        ('f', 'Din Tai Fung (Tín Nghĩa)', 'Din Tai Fung', 'Tiểu long bao nổi tiếng thế giới, quán gốc ở đường Tín Nghĩa', {'k': 'trua,toi', 'v': 400, 't': 's', 'io': 'i', 'll': [25.0334, 121.5302]}),
        ('f', 'Chợ đêm Ninh Hạ', 'Ningxia Night Market', 'Chợ đêm nhỏ nhiều món địa phương, trứng nướng', {'k': 'toi,vat', 'v': 150, 't': 's', 'io': 'o', 'ev': 'all', 'eo': 1, 'll': [25.0562, 121.5154]}),
        ('c', 'Núi Tượng Sơn', 'Elephant Mountain (Taipei)', 'Đường bậc thang lên ngắm Taipei 101 lúc hoàng hôn', {'v': 0, 'd': 75, 't': 'np', 'io': 'o', 'ss': 1, 'f': 'o', 'll': [25.0273, 121.5707]}),
        ('s', 'Cáp treo Miêu Không', 'Maokong Gondola', 'Cáp treo lên đồi trà, quán trà ngắm phố', {'price': '~120 TWD', 'v': 100, 'd': 180, 't': 'ncr', 'io': 'o'}),
        ('c', 'Phố cổ Đại Đạo Trình – Địch Hóa', 'Dihua Street', 'Phố cổ bán đồ khô, trà, quán cà phê trong nhà xưa', {'k': 'check,cafe', 'v': 0, 'd': 75, 't': 'hcp', 'io': 'o'}),
        ('c', 'Huashan 1914', 'Huashan 1914 Creative Park', 'Nhà máy rượu cũ thành khu sáng tạo, triển lãm', {'k': 'check,cafe', 'v': 0, 'd': 90, 't': 'pc', 'io': 'm'}),
        ('f', 'Phố Vĩnh Khang', 'Yongkang Street', 'Phố ẩm thực: mì bò, kem xoài, bánh hành', {'k': 'trua,cafe,vat', 'v': 200, 't': 'sc', 'io': 'o', 'll': [25.033, 121.5297]}),
        ('c', 'Đạm Thủy', 'Tamsui District', 'Thị trấn ven sông, ngắm hoàng hôn, ăn vặt', {'k': 'check,vat', 'v': 50, 'd': 180, 't': 'pr', 'io': 'o', 'ss': 1}),
        ('c', 'Thập Phần – thả đèn trời', 'Shifen', 'Thả đèn trời trên đường ray, thác Thập Phần', {'v': 50, 'd': 180, 't': 'pn', 'io': 'o', 'trip': 1, 'll': [25.0418, 121.7756]}),
        ('f', 'Bữa sáng Phụ Hàng Đậu Tương', 'Fuhang Soy Milk', 'Quán sữa đậu nành và bánh nướng sáng nổi tiếng', {'k': 'sang', 'v': 80, 't': 's', 'io': 'i', 'mo': 1, 'cl': [1], 'll': [25.0442, 121.5250]}),
    ],
    'taichung': [
        ('f', 'Chợ đêm Nhất Trung', 'Yizhong Street', 'Chợ đêm khu sinh viên, gà rán, trà sữa', {'k': 'toi,vat,cafe', 'v': 120, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Đài Trung'}),
        ('c', 'Miyahara', 'Miyahara (Taichung)', 'Phòng khám mắt cổ thành tiệm kem và bánh dứa', {'k': 'check,cafe', 'v': 120, 'd': 45, 't': 'cph', 'io': 'i', 'll': [24.1376, 120.6837], 'a': 'Đài Trung'}),
        ('s', 'Bảo tàng Khoa học Tự nhiên', 'National Museum of Natural Science', 'Bảo tàng khoa học lớn, hợp trẻ em', {'price': '~100 TWD', 'v': 85, 'd': 150, 't': 'n', 'io': 'i', 'cl': [1], 'a': 'Đài Trung'}),
        ('c', 'Công viên Đài Trung', 'Taichung Park', 'Công viên cổ có đình trên hồ', {'v': 0, 'd': 45, 't': 'rp', 'io': 'o', 'a': 'Đài Trung'}),
        ('c', 'Cáp treo Nhật Nguyệt Đàm', 'Sun Moon Lake Ropeway', 'Cáp treo qua núi từ hồ lên làng văn hóa thổ dân', {'price': '~300 TWD', 'v': 250, 'd': 120, 't': 'np', 'io': 'o', 'a': 'Nhật Nguyệt Đàm', 'll': [23.8504, 120.9318]}),
        ('s', 'Chùa Văn Võ (Nhật Nguyệt Đàm)', 'Wenwu Temple', 'Ngôi chùa lớn bên hồ, view toàn cảnh mặt hồ', {'v': 0, 'd': 45, 't': 'hp', 'io': 'o', 'a': 'Nhật Nguyệt Đàm', 'll': [23.8724, 120.9259]}),
        ('f', 'Phố cổ Y Đạt Thiệu', 'Ita Thao', 'Phố ẩm thực thổ dân Thiệu bên bến thuyền', {'k': 'trua,toi,vat', 'v': 200, 't': 's', 'io': 'o', 'a': 'Nhật Nguyệt Đàm', 'll': [23.8505, 120.933]}),
        ('c', 'Bến Thủy Xã', 'Shuishe Village', 'Bến thuyền chính, đi tàu quanh hồ và đạp xe ven hồ', {'k': 'check,cafe', 'v': 200, 'd': 120, 't': 'nrc', 'io': 'o', 'ss': 1, 'a': 'Nhật Nguyệt Đàm', 'll': [23.866, 120.911]}),
    ],
    'bali': [
        ('c', 'Bãi biển Seminyak', 'Seminyak', 'Bãi biển với beach club, nhà hàng, hoàng hôn', {'k': 'check,cafe', 'v': 0, 'd': 120, 't': 'brc', 'io': 'o', 'ss': 1, 'a': 'Nam Bali', 'll': [-8.6913, 115.1585]}),
        ('c', 'Bãi biển Nusa Dua', 'Nusa Dua', 'Biển êm, nước trong, khu resort cao cấp', {'v': 0, 'd': 150, 't': 'br', 'io': 'o', 'a': 'Nam Bali'}),
        ('c', 'Garuda Wisnu Kencana', 'Garuda Wisnu Kencana Cultural Park', 'Tượng thần khổng lồ cao 121 m', {'price': '~125.000 IDR', 'v': 200, 'd': 120, 't': 'hp', 'io': 'o', 'a': 'Nam Bali'}),
        ('f', 'Chợ đêm Sindhu (Sanur)', 'Sanur, Bali', 'Chợ đêm và bãi biển Sanur, sate, nasi campur', {'k': 'toi,sang,vat', 'v': 120, 't': 's', 'io': 'o', 'ev': 'all', 'a': 'Nam Bali'}),
        ('f', 'Chợ nghệ thuật Ubud', 'Ubud Art Market', 'Chợ đồ thủ công, gần cung điện Ubud', {'k': 'check,trua', 'v': 120, 'd': 75, 't': 'hs', 'io': 'm', 'a': 'Ubud', 'll': [-8.507, 115.263]}),
        ('s', 'Cung điện Ubud', 'Ubud Palace', 'Cung điện hoàng gia, múa Legong buổi tối', {'v': 0, 'd': 45, 't': 'h', 'io': 'o', 'ev': 'all', 'a': 'Ubud'}),
        ('c', 'Đồi Campuhan', 'Campuhan Ridge Walk', 'Đường mòn trên sườn đồi cỏ, đi sáng sớm hoặc chiều', {'v': 0, 'd': 75, 't': 'np', 'io': 'o', 'mo': 1, 'll': [-8.5039, 115.2540], 'a': 'Ubud'}),
        ('s', 'Đền Goa Gajah', 'Goa Gajah', 'Hang Voi cổ với cửa hang chạm khắc', {'price': '~50.000 IDR', 'v': 80, 'd': 60, 't': 'h', 'io': 'o', 'a': 'Ubud'}),
        ('c', 'Bãi Padang Padang', 'Padang Padang Beach', 'Bãi cát nhỏ giữa vách đá ở Uluwatu', {'v': 25, 'd': 120, 't': 'br', 'io': 'o', 'f': 'o', 'a': 'Nam Bali'}),
    ],
}


def extend(cities):
    """Nối NEW vào danh sách và gắn META cho điểm cũ (gọi từ intl_src.py)."""
    for c in cities:
        base = len(c['places'])
        if c.get('_ext'):
            continue
        out = []
        for i, p in enumerate(c['places']):
            extra = dict(p[4]) if len(p) > 4 else {}
            extra.update(META.get(f"{c['id']}-{i + 1}", {}))
            out.append((p[0], p[1], p[2], p[3], extra))
        out += [(p[0], p[1], p[2], p[3], dict(p[4])) for p in NEW.get(c['id'], [])]
        c['places'] = out
        c['_ext'] = base
    return cities
